# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""The assertion vocabulary a use case may write, and what each entry is allowed to prove.

**This is a registry of contracts, not an implementation.** Executing an assertion against a
live tree is T2.5's job; what lives here is the list of kinds a use-case file may name and the
parameters each one requires, so that `catalog.py` can refuse a typo instead of loading it.

That refusal is the point. A use case whose `kind` is misspelt would otherwise sit in the
catalog looking like coverage and grading nothing — the silent-no-op family of defects the
Checkpoint review found four of in the Stage-1 harness (B2-B4). A kind nobody implements is
caught from the other side too: T2.5's grader has to answer for every name in `KINDS`, and
`test_00_stage2_catalog.py` fails a kind that no use case uses, so the vocabulary cannot grow
speculative entries.

**Grades** (from the Stage-2 design's gate 1). `A` reads the tree over REST or the backup
filesystem and may fail the run. `B` can only be decided from the recorded tool log — it is
worth collecting, it is never allowed to gate, and `coverage.py` already carries the same
distinction per tool.
"""

from __future__ import annotations

from dataclasses import dataclass, field

A = "A"
B = "B"


@dataclass(frozen=True)
class Kind:
    """One assertion kind: what it proves, and what a use-case file has to supply."""

    proves: str
    grade: str = A
    required: tuple[str, ...] = ()
    optional: tuple[str, ...] = field(default=())


KINDS: dict[str, Kind] = {
    "counts": Kind(
        "every namespace moved by exactly the declared delta and no other moved at all — the "
        "per-namespace form T2.3 requires, because `add_person` also creates a tag and a "
        "birth event, so a whole-tree 'nothing else changed' is a false red",
        required=("deltas",),
    ),
    "created": Kind(
        "exactly this many objects appeared in the namespace, and (with `fields`) the one "
        "that appeared carries these values — a create is never proven by a count alone",
        required=("namespace", "count"),
        optional=("fields",),
    ),
    "removed": Kind(
        "exactly these objects are gone and no others. The set, never the count: a delete "
        "that removes the wrong record moves the count by the same one",
        required=("namespace", "subjects"),
    ),
    "person": Kind(
        "named leaf values on one person's record, read back over REST — first_name, "
        "surname, gender, name_type",
        required=("subject", "fields"),
    ),
    "alternates": Kind(
        "a person's alternate names: how many there are, and which (surname, type) pairs are "
        "among them. `count` is what separates an added name from a swapped one",
        required=("subject",),
        optional=("count", "contains"),
    ),
    "family": Kind(
        "who occupies a family's parent slots and who its children are, as subjects rather "
        "than handles",
        required=("subject",),
        optional=("father", "mother", "children"),
    ),
    "tag": Kind(
        "whether one named tag is on a person, and whether the tag object itself survives",
        required=("subject", "tag", "present"),
        optional=("tag_survives",),
    ),
    "note_body": Kind(
        "the text of a source's body note: unchanged but for one declared replacement "
        "(uc17's byte-preserving edit), or merely long enough to be prose",
        required=("subject",),
        optional=("replaces", "min_length"),
    ),
    "source": Kind(
        "named leaf values on one source record — the exact title a prompt asked for",
        required=("subject", "fields"),
    ),
    "names_added": Kind(
        "which (first name, surname) pairs the call added. Names, not ids: an import may "
        "renumber a colliding gramps_id, so the id is not a handle a use case can hold",
        required=("pairs",),
    ),
    "tree_unchanged": Kind(
        "the whole tree is identical to before — the only class-A statement a read-only use "
        "case can make, and the one that catches a read tool that writes"
    ),
    "tree_empty": Kind(
        "every namespace is at zero. Only reachable if `expected_count` matched the live "
        "total, which is what makes it the class-A proof that the counts were read"
    ),
    "backup_file": Kind(
        "what appeared in the mounted backup directory during this call — never 'a file "
        "exists', which a leftover export from an earlier run satisfies for free",
        required=("count",),
        optional=("extension", "min_bytes", "contains"),
    ),
    "tool_log": Kind(
        "which tools the model actually called. Advisory by construction: the tree cannot "
        "tell a `list_people` from a `get_person`, so this may never fail a run",
        grade=B,
        required=("used_any",),
    ),
}

GATING = frozenset(name for name, kind in KINDS.items() if kind.grade == A)

# Which parameters hold subject names rather than values. Listed once, here, because both the
# validator and T2.5's grader have to agree on it: a parameter that holds a subject and is not
# listed would be resolved by nobody and compared as the literal string it is.
ONE_SUBJECT = frozenset({"subject", "father", "mother"})
MANY_SUBJECTS = frozenset({"subjects", "children"})


def unknown_parameters(kind_name: str, given: set[str]) -> set[str]:
    """Parameters a use case supplied that this kind does not know."""
    kind = KINDS[kind_name]
    return given - set(kind.required) - set(kind.optional)


def missing_parameters(kind_name: str, given: set[str]) -> set[str]:
    """Parameters this kind requires and the use case did not supply."""
    return set(KINDS[kind_name].required) - given
