# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""One file per use case, loaded as data (plan T2.2, T2.7).

A Stage-2 use case is a prompt, the tools it is a test *of*, the subjects it is about, what the
tree must look like afterwards, and how much of the tree it is allowed to lose. Keeping that in
YAML rather than in Python is not decoration: T2.7's leak lint reads the prompts, T2.5's grader
reads the assertions, T2.6's gate reads the tier and the assertion ids, and a docstring edit
that changes what a use case can prove then touches **one** file that all four see.

What this module does and does not do:

* it **loads** and rejects a file whose *shape* is wrong — an unknown key, a missing prompt, a
  tier nobody defined. Such a file is not a use case and must not reach the runner;
* it does **not** decide whether the use case is any good. Whether its tools exist, its
  subjects resolve to exactly one person and its assertions name kinds anybody implements is
  `validate.py`'s job, so that a whole catalog can be reported at once instead of one file per
  run.

`maxdrop` and `guards` accept the literal `everything`, which is how uc20 says "this use case
is the wipe". A wildcard that had to be spelt out is a wildcard somebody chose.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml
from harness.docker_util import ProbeError

USE_CASE_DIR = Path(__file__).resolve().parent / "use_cases"
EVERYTHING = "everything"
TIERS = (1, 2, 3)

REQUIRED = frozenset({"id", "tier", "prompt", "primary", "assertions"})
OPTIONAL = frozenset({"decoys", "secondary", "subjects", "guards", "maxdrop", "leak_waivers"})
NAMESPACES = frozenset({"people", "families", "sources"})


@dataclass(frozen=True)
class Assertion:
    """One graded statement about the tree after the call."""

    id: str
    kind: str
    params: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class Waiver:
    """One prompt token the leak lint flags and this use case keeps anyway, with the reason."""

    token: str
    reason: str


@dataclass(frozen=True)
class UseCase:
    """One use case, exactly as its file declares it."""

    id: str
    slug: str
    tier: int
    prompt: str
    primary: tuple[str, ...]
    decoys: tuple[str, ...]
    secondary: tuple[str, ...]
    subjects: dict[str, dict[str, Any]]
    guards: Any
    maxdrop: Any
    assertions: tuple[Assertion, ...]
    waivers: tuple[Waiver, ...]
    path: Path

    @property
    def number(self) -> int:
        return int(self.id[2:])

    @property
    def gates(self) -> bool:
        """Tier 3 is advisory by design — a read use case cannot fail a run."""
        return self.tier in (1, 2)


def load(path: Path) -> UseCase:
    """One use-case file, or a `ProbeError` naming the file and the problem."""
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ProbeError(f"{path.name} is not a mapping")

    unknown = set(raw) - REQUIRED - OPTIONAL
    missing = REQUIRED - set(raw)
    if unknown or missing:
        raise ProbeError(
            f"{path.name}: unknown keys {sorted(unknown)}, missing keys {sorted(missing)}"
        )
    _check_identity(path, raw)

    return UseCase(
        id=str(raw["id"]),
        slug=path.stem,
        tier=_tier(path, raw["tier"]),
        prompt=_prompt(path, raw["prompt"]),
        primary=_tools(path, "primary", raw["primary"], required=True),
        decoys=_tools(path, "decoys", raw.get("decoys", [])),
        secondary=_tools(path, "secondary", raw.get("secondary", [])),
        subjects=_subjects(path, raw.get("subjects", {})),
        guards=_guards(path, raw.get("guards", {})),
        maxdrop=_maxdrop(path, raw.get("maxdrop", 0)),
        assertions=_assertions(path, raw["assertions"]),
        waivers=_waivers(path, raw.get("leak_waivers", [])),
        path=path,
    )


def load_all(directory: Path = USE_CASE_DIR) -> dict[str, UseCase]:
    """Every use case, keyed by id. Sorted by file name so a run is reproducible."""
    loaded = [load(path) for path in sorted(directory.glob("uc*.yaml"))]
    by_id: dict[str, UseCase] = {}
    for use_case in loaded:
        if use_case.id in by_id:
            raise ProbeError(f"{use_case.id} is declared twice: {by_id[use_case.id].slug}")
        by_id[use_case.id] = use_case
    if not by_id:
        raise ProbeError(f"no use cases in {directory}")
    return by_id


def _check_identity(path: Path, raw: dict[str, Any]) -> None:
    """`uc07-...yaml` holds `uc7`, and nothing else. The file name is what a human greps."""
    identifier = str(raw.get("id", ""))
    if not identifier.startswith("uc") or not identifier[2:].isdigit():
        raise ProbeError(f"{path.name}: id {identifier!r} is not `ucN`")
    if not path.stem.startswith(f"uc{int(identifier[2:]):02d}-"):
        raise ProbeError(f"{path.name} does not carry its own id {identifier!r}")


def _tier(path: Path, value: Any) -> int:
    if value not in TIERS:
        raise ProbeError(f"{path.name}: tier {value!r} is not one of {TIERS}")
    return int(value)


def _prompt(path: Path, value: Any) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ProbeError(f"{path.name}: the prompt is empty")
    return value.strip()


def _tools(path: Path, key: str, value: Any, *, required: bool = False) -> tuple[str, ...]:
    if not isinstance(value, list) or any(not isinstance(name, str) for name in value):
        raise ProbeError(f"{path.name}: {key} is not a list of tool names")
    if required and not value:
        raise ProbeError(f"{path.name}: {key} is empty — a use case with no primary tests nothing")
    return tuple(value)


def _subjects(path: Path, value: Any) -> dict[str, dict[str, Any]]:
    if not isinstance(value, dict):
        raise ProbeError(f"{path.name}: subjects is not a mapping")
    for name, selector in value.items():
        if not isinstance(selector, dict):
            raise ProbeError(f"{path.name}: subject {name!r} is not a selector mapping")
        if str(name).startswith("new:"):
            raise ProbeError(f"{path.name}: {name!r} is reserved for what the call creates")
    return dict(value)


def _guards(path: Path, value: Any) -> Any:
    """Whose records this use case may touch, per namespace — or `everything` for the wipe."""
    if value == EVERYTHING:
        return EVERYTHING
    if not isinstance(value, dict) or set(value) - NAMESPACES:
        raise ProbeError(f"{path.name}: guards {value!r} is not a namespace map or {EVERYTHING!r}")
    for namespace, allowed in value.items():
        if not isinstance(allowed, list):
            raise ProbeError(f"{path.name}: guards[{namespace}] is not a list of subjects")
    return {namespace: list(allowed) for namespace, allowed in value.items()}


def _maxdrop(path: Path, value: Any) -> Any:
    if value == EVERYTHING:
        return EVERYTHING
    if not isinstance(value, int) or isinstance(value, bool) or value < 0:
        raise ProbeError(f"{path.name}: maxdrop {value!r} is not a count or {EVERYTHING!r}")
    return value


def _assertions(path: Path, value: Any) -> tuple[Assertion, ...]:
    if not isinstance(value, list) or not value:
        raise ProbeError(f"{path.name}: a use case with no assertions grades nothing")
    parsed: list[Assertion] = []
    for entry in value:
        if not isinstance(entry, dict) or "id" not in entry or "kind" not in entry:
            raise ProbeError(f"{path.name}: assertion {entry!r} has no id or no kind")
        parsed.append(
            Assertion(
                id=str(entry["id"]),
                kind=str(entry["kind"]),
                params={key: item for key, item in entry.items() if key not in ("id", "kind")},
            )
        )
    return tuple(parsed)


def _waivers(path: Path, value: Any) -> tuple[Waiver, ...]:
    if not isinstance(value, list):
        raise ProbeError(f"{path.name}: leak_waivers is not a list")
    waivers: list[Waiver] = []
    for entry in value:
        if not isinstance(entry, dict) or not entry.get("token") or not entry.get("reason"):
            raise ProbeError(
                f"{path.name}: waiver {entry!r} needs a token and a reason — an unexplained "
                "waiver is how a leak becomes permanent"
            )
        waivers.append(Waiver(token=str(entry["token"]), reason=str(entry["reason"])))
    return tuple(waivers)
