# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""The class-A checks that read one named record back (plan T2.5, D16).

A use case names its fields the way a person would — `surname`, `name_type`, `gender` — and this
module is the single place that knows those map onto `primary_name.surname_list.0.surname` and
friends. An unknown field name is a **failure**, not a skip: a mistyped `sur_name` that silently
compared nothing is the same silent-no-op the Stage-1 gate hardening spent four fixes on.

Everything reads from the *after* capture. Nothing here calls the network.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from stage2 import state as state_mod

Params = Mapping[str, Any]

# What a use case may write on the left of a `fields:` entry, and where it lives in the record.
PERSON_FIELDS = {
    "first_name": state_mod.first_name,
    "surname": state_mod.surname,
    "gender": lambda person: person.get("gender"),
    "name_type": lambda person: state_mod.name_type(person.get("primary_name") or {}),
}
SOURCE_FIELDS = {
    "title": lambda source: source.get("title", ""),
    "author": lambda source: source.get("author", ""),
}

UNKNOWN = object()

# What one entry of an `alternates: contains:` list may name. Both are optional — an entry that
# gives one of them means "an alternate with this, whatever the other is".
ALTERNATE_KEYS = frozenset({"surname", "name_type"})


def read_field(record: Mapping[str, Any], field: str) -> Any:
    """One named leaf, or `UNKNOWN` — which never equals anything a use case can write."""
    reader = PERSON_FIELDS.get(field) or SOURCE_FIELDS.get(field)
    return reader(record) if reader else UNKNOWN


def person(params: Params, evidence: Any) -> str | None:
    gramps_id = evidence.ids(params["subject"])
    record = evidence.after.by_id("people").get(gramps_id)
    if record is None:
        return f"people/{gramps_id} is not in the tree after the call"
    for field, expected in dict(params["fields"]).items():
        actual = read_field(record, str(field))
        if actual is UNKNOWN:
            return f"{field!r} is not a field this suite knows how to read"
        if actual != expected:
            return f"people/{gramps_id}.{field} is {actual!r}, expected {expected!r}"
    return None


def alternates(params: Params, evidence: Any) -> str | None:
    """A person's alternate names. `count` is what separates an added name from a swapped one —
    the tempting wrong route through uc13 leaves a second alternate behind."""
    gramps_id = evidence.ids(params["subject"])
    record = evidence.after.by_id("people").get(gramps_id)
    if record is None:
        return f"people/{gramps_id} is not in the tree after the call"
    names = [
        (state_mod.name_surname(name), state_mod.name_type(name))
        for name in record.get("alternate_names") or []
    ]
    if "count" in params and len(names) != int(params["count"]):
        return (
            f"people/{gramps_id} has {len(names)} alternate names {names}, "
            f"expected {params['count']}"
        )
    for wanted in params.get("contains") or []:
        unknown = set(wanted) - ALTERNATE_KEYS
        if unknown:
            return f"{sorted(unknown)} is not something an alternate name has"
        if not any(_matches(wanted, name) for name in names):
            return f"people/{gramps_id} has {names}, none of which matches {dict(wanted)}"
    return None


def _matches(wanted: Mapping[str, Any], name: tuple[str, str]) -> bool:
    """Only the keys the use case wrote.

    uc4 names a surname and deliberately not a type: which type `add_alternate_name` assigns is
    the product's choice (the first live run made it `"Also Known As"`), and a use case that
    pinned it would be asserting the answer instead of asking the question.
    """
    surname, kind = name
    if "surname" in wanted and str(wanted["surname"]) != surname:
        return False
    return not ("name_type" in wanted and str(wanted["name_type"]) != kind)


def family(params: Params, evidence: Any) -> str | None:
    """Who occupies the parent slots and who the children are, as subjects rather than handles."""
    gramps_id = evidence.ids(params["subject"])
    record = evidence.after.by_id("families").get(gramps_id)
    if record is None:
        return f"families/{gramps_id} is not in the tree after the call"
    ids = evidence.after.handle_to_id()
    for slot in ("father", "mother"):
        if slot not in params:
            continue
        want = evidence.ids(params[slot]) if params[slot] else ""
        have = ids.get(str(record.get(f"{slot}_handle") or ""), "")
        if have != want:
            return (
                f"families/{gramps_id} has {slot}={have or 'nobody'}, expected {want or 'nobody'}"
            )
    if "children" in params:
        want_children = sorted(evidence.id_set(params["children"]))
        have_children = state_mod.children(record, ids)
        if have_children != want_children:
            return (
                f"families/{gramps_id} has children {have_children or 'none'}, "
                f"expected {want_children or 'none'}"
            )
    return None


def tag(params: Params, evidence: Any) -> str | None:
    """Whether one named tag is on a person — and, separately, whether the tag object survives.

    The two are not the same question: removing the last use of a tag may or may not delete the
    tag itself, and a use case that means one must not be satisfied by the other.
    """
    gramps_id = evidence.ids(params["subject"])
    record = evidence.after.by_id("people").get(gramps_id)
    if record is None:
        return f"people/{gramps_id} is not in the tree after the call"
    wanted, present = str(params["tag"]), bool(params["present"])
    carried = state_mod.tag_names(record, state_mod.tag_handles(evidence.after))
    if (wanted in carried) is not present:
        return (
            f"people/{gramps_id} carries {list(carried) or 'no tags'}; "
            f"{wanted!r} should be {'present' if present else 'absent'}"
        )
    if "tag_survives" in params:
        names = {str(entry.get("name", "")) for entry in evidence.after.of("tags")}
        if (wanted in names) is not bool(params["tag_survives"]):
            return (
                f"the tag object {wanted!r} is {'still' if wanted in names else 'not'} in the "
                f"tree; the use case expects tag_survives={params['tag_survives']}"
            )
    return None


def source(params: Params, evidence: Any) -> str | None:
    gramps_id = evidence.ids(params["subject"])
    record = evidence.after.by_id("sources").get(gramps_id)
    if record is None:
        return f"sources/{gramps_id} is not in the tree after the call"
    for field, expected in dict(params["fields"]).items():
        actual = read_field(record, str(field))
        if actual is UNKNOWN:
            return f"{field!r} is not a field this suite knows how to read"
        if actual != expected:
            return f"sources/{gramps_id}.{field} is {actual!r}, expected {expected!r}"
    return None


def note_body(params: Params, evidence: Any) -> str | None:
    """The text of a source's body note.

    `replaces` is byte-preserving on purpose (uc17): everything but the one declared correction
    has to come back identical, which is what distinguishes an edit from a rewrite. A model that
    "helpfully" reflows the article fails here, and should.

    It is `{from:, to:}` and never a two-element list, because the list form is silently
    reversible: `['1913', '1912']` finds nothing to replace, so `wanted` is the untouched
    original and a **correct** edit reds. A false red is the one outcome this suite may not
    produce — the catalog's shape contract is what holds the form now.
    """
    gramps_id = evidence.ids(params["subject"])
    before_text = _note_text(evidence.before, gramps_id)
    after_text = _note_text(evidence.after, gramps_id)
    if after_text is None:
        return f"sources/{gramps_id} has no body note after the call"
    if "min_length" in params and len(after_text) < int(params["min_length"]):
        return f"the note is {len(after_text)} characters, expected at least {params['min_length']}"
    if "replaces" in params:
        if before_text is None:
            return f"sources/{gramps_id} had no body note before the call to correct"
        wrong, right = params["replaces"]["from"], params["replaces"]["to"]
        wanted = before_text.replace(str(wrong), str(right))
        if after_text != wanted:
            return (
                "the note is not the original with exactly that one correction applied\n"
                f"  expected: {wanted[:200]!r}\n  actual:   {after_text[:200]!r}"
            )
    return None


def _note_text(capture: Any, source_id: str) -> str | None:
    """The first note a source references, as text. `note["text"]["string"]` — measured."""
    record = capture.by_id("sources").get(source_id)
    if not record:
        return None
    notes = capture.by_handle("notes")
    for handle in record.get("note_list") or []:
        note = notes.get(str(handle))
        if note:
            return str((note.get("text") or {}).get("string", ""))
    return None
