# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""The class-A checks that read the whole tree's movement (plan T2.5).

Every one of these answers from the two captures around the call and from nothing else. The
model's prose is not a parameter; neither is the tool's own report, which is the echo of its
argument in every delete tool this server has (checkpoint B1).

`tool_log` is the single class-B entry and is kept here beside them on purpose, so that the one
check which may **never** fail a run sits where anybody adding a check can see why: the tree
cannot tell a `list_people` from a `get_person`, so a statement about which tool was called is
worth collecting and is not evidence.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from stage2 import state as state_mod

Params = Mapping[str, Any]


def counts(params: Params, evidence: Any) -> str | None:
    """Every namespace moved by exactly the declared delta, and no other moved at all."""
    want = {key: int(value) for key, value in dict(params["deltas"]).items() if value}
    moved = {key: value for key, value in evidence.movement.delta.items() if value}
    if moved != want:
        return f"the tree moved {moved or 'nothing'}, the use case declared {want or 'nothing'}"
    return None


def created(params: Params, evidence: Any) -> str | None:
    """N objects appeared — and with `fields`, the one that appeared carries these values."""
    namespace = str(params["namespace"])
    appeared = evidence.movement.added.get(namespace, [])
    if len(appeared) != int(params["count"]):
        return (
            f"{len(appeared)} objects appeared in {namespace} ({appeared or 'none'}), "
            f"the use case expects {params['count']}"
        )
    fields = params.get("fields")
    if not fields:
        return None
    if len(appeared) != 1:
        return f"`fields` names one record, but {len(appeared)} appeared in {namespace}"
    record = evidence.after.by_id(namespace).get(appeared[0], {})
    return _leaves(namespace, appeared[0], record, fields)


def removed(params: Params, evidence: Any) -> str | None:
    """Exactly these objects are gone. The set, never the count: a delete of the wrong record
    moves the count by the same one."""
    namespace = str(params["namespace"])
    want = sorted(evidence.id_set(params["subjects"]))
    gone = sorted(evidence.movement.removed.get(namespace, []))
    if gone != want:
        return f"{namespace} lost {gone or 'nothing'}, the use case named {want or 'nothing'}"
    return None


def names_added(params: Params, evidence: Any) -> str | None:
    """Which people the call added, by name.

    Names and not ids: an import renumbers a colliding `gramps_id`, so the id is not something
    a use case can hold on to across the call it is testing.
    """
    arrived = evidence.movement.added.get("people", [])
    people = evidence.after.by_id("people")
    have = {
        (state_mod.first_name(people[i]), state_mod.surname(people[i]))
        for i in arrived
        if i in people
    }
    want = {(str(pair["first_name"]), str(pair["surname"])) for pair in params["pairs"]}
    if not want <= have:
        return f"the call added {sorted(have) or 'nobody'}, which does not cover {sorted(want)}"
    return None


def tree_unchanged(_params: Params, evidence: Any) -> str | None:
    """The only class-A statement a read-only use case can make — and the one that catches a
    read tool that writes.

    Compared over signatures rather than whole records: a record's `change` stamp moves on any
    write, including one that wrote the value that was already there. The consequence is stated
    rather than hidden — a PUT that alters nothing but that stamp is invisible here.
    """
    if evidence.before.counts != evidence.after.counts:
        return f"counts moved {evidence.before.counts} → {evidence.after.counts}"
    if evidence.movement.added or evidence.movement.removed or evidence.movement.renamed:
        return (
            f"identity moved: added={evidence.movement.added or 'nothing'}, "
            f"removed={evidence.movement.removed or 'nothing'}, "
            f"renamed={evidence.movement.renamed or 'nothing'}"
        )
    touched = evidence.touched()
    if touched:
        return f"records were rewritten in place: {sorted(touched)}"
    return None


def tree_empty(_params: Params, evidence: Any) -> str | None:
    """Only reachable if `expected_count` matched the live total, which is what makes this the
    class-A proof that the model read the counts before wiping."""
    left = {key: value for key, value in evidence.after.counts.items() if value}
    if left:
        return f"the tree still holds {left}"
    return None


def backup_file(params: Params, evidence: Any) -> str | None:
    """What appeared in the mounted backup directory *during this call*.

    Never "a file exists": an export left behind by an earlier run satisfies that for free, and
    the directory survives the tree reset by design (D17).
    """
    appeared = list(evidence.backup)
    if len(appeared) != int(params["count"]):
        return (
            f"{len(appeared)} files appeared in the backup directory "
            f"({[entry.name for entry in appeared] or 'none'}), expected {params['count']}"
        )
    extension = params.get("extension")
    for entry in appeared:
        if extension and not entry.name.endswith(str(extension)):
            return f"{entry.name} does not end in {extension!r}"
        if entry.size < int(params.get("min_bytes", 0)):
            return f"{entry.name} is {entry.size} bytes, expected at least {params['min_bytes']}"
        if params.get("contains") and str(params["contains"]) not in entry.text:
            return f"{entry.name} does not contain {params['contains']!r}"
    return None


def tool_log(params: Params, evidence: Any) -> str | None:
    """Class B. Collected, reported, and never allowed to fail a run."""
    wanted = {str(name) for name in params["used_any"]}
    if not wanted & set(evidence.calls):
        return (
            f"the model called {sorted(set(evidence.calls)) or 'nothing'}, none of {sorted(wanted)}"
        )
    return None


def _leaves(
    namespace: str, gramps_id: str, record: Mapping[str, Any], fields: Params
) -> str | None:
    """Named leaf values on one record, via the shared accessors."""
    from stage2.checks_record import read_field  # local: the two modules are peers

    if not record:
        return f"{namespace}/{gramps_id} is not in the tree after the call"
    for field, expected in fields.items():
        actual = read_field(record, str(field))
        if actual != expected:
            return f"{namespace}/{gramps_id}.{field} is {actual!r}, expected {expected!r}"
    return None
