# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""Which use case is each tool's primary, and what the assertion can honestly prove (T2.1).

Stage 2 shows the model only the docstrings and lets it choose. That is only a *test* of a tool
where a failing assertion pins the blame on that tool — so every one of the 31 needs a use case
in which it is primary, or a written reason why no such use case can exist. This file is that
map, as data rather than prose, because the failure it guards against is a **new tool shipping
with no Stage-2 slot at all** — the same silence that put a broken image out twice.

Three grades, from the design (§0), and the difference between them is what a red assertion
licenses you to say:

* `A` — a class-A assertion (tree state over REST, or the backup filesystem) fails if any other
  tool was used. Blame lands on this tool.
* `A_TWIN` — the outcome is gate-eligible, the *identity* is not: the tool's behavioural twin
  produces a byte-identical tree. `set_gender_bulk` and N × `set_gender` call the same
  `_write_person` with the same mutation (`gramps_client.py:714-760`); only the call count
  differs, and the call count is class B.
* `B` — only the recorded `tool_use` log can tell it apart, so it may never gate. Six read tools
  are here because a read leaves no delta *and* they are mutually substitutable: `list_people`
  with `keys` omitted returns full records (`gramps_client.py:645-665`), a strict superset of
  `get_person` and `search_person`.

**A discrepancy carried over deliberately.** The source design's summary sentence says "22 of 31
have a gate-eligible primary … the 9 that don't are the six substitutable reads and the three
behavioural twins". Its own itemised table says 20 `A` + 4 `A_TWIN` + 7 `B`, which is what is
encoded here, because the per-tool rows carry per-tool reasons and the sentence carries only a
count. `test_00_stage2_coverage.py` pins the real distribution so that neither number can drift
again in silence.
"""

from __future__ import annotations

from dataclasses import dataclass, field

A = "A"
A_TWIN = "A_TWIN"
B = "B"

SUBSTITUTABLE_READ = (
    "a read leaves no tree delta, and these six are mutually substitutable — `list_people` "
    "without `keys` returns full person records (gramps_client.py:645-665), a strict superset "
    "of what `get_person` and `search_person` return, and get_relations/get_ancestors/"
    "get_descendants all answer a one-generation family question. No assertion over tree state "
    "can say which one was used."
)
BEHAVIOURAL_TWIN = (
    "its twin produces a byte-identical record: `_bulk_write` calls the same `_write_person` "
    "with the same mutation as the single-person tool (gramps_client.py:714-760), so N singles "
    "and one bulk call converge. Only the call count differs, and the call count is class B."
)
BIRTH_NAME_TWIN = (
    "`add_birth_name(x)` and `add_alternate_name(x, is_birth_name=True)` write the same record "
    "(gramps_client.py:799-801). Identical resulting tree state — no assertion can separate "
    "them, ever."
)


@dataclass(frozen=True)
class Slot:
    """One tool's place in Stage 2."""

    primary: str
    grade: str
    reason: str = ""
    decoy_in: tuple[str, ...] = ()
    secondary_in: tuple[str, ...] = field(default=())


# Verbatim from the design's coverage table (§1), one row per registered tool.
COVERAGE: dict[str, Slot] = {
    "gramps_add_person": Slot("uc1", A, secondary_in=("uc3",)),
    "gramps_add_family": Slot("uc2", A, decoy_in=("uc3", "uc14")),
    "gramps_add_child_to_family": Slot("uc3", A),
    "gramps_set_family_parent": Slot("uc14", A, decoy_in=("uc2",)),
    "gramps_remove_child_from_family": Slot("uc15", A),
    "gramps_set_surname": Slot(
        "uc4", A_TWIN, BEHAVIOURAL_TWIN, decoy_in=("uc10", "uc11", "uc13", "uc23")
    ),
    "gramps_set_first_name": Slot("uc10", A),
    "gramps_set_gender": Slot("uc9", A_TWIN, BEHAVIOURAL_TWIN),
    "gramps_set_surname_bulk": Slot("uc21", A_TWIN, BEHAVIOURAL_TWIN, decoy_in=("uc4",)),
    "gramps_set_gender_bulk": Slot("uc22", A_TWIN, BEHAVIOURAL_TWIN, decoy_in=("uc9",)),
    "gramps_add_alternate_name": Slot(
        "uc11", A, decoy_in=("uc10", "uc13"), secondary_in=("uc4", "uc23")
    ),
    "gramps_add_birth_name": Slot("uc23", B, BIRTH_NAME_TWIN),
    "gramps_swap_primary_name": Slot("uc13", A, decoy_in=("uc4", "uc10")),
    "gramps_confirm_person": Slot("uc12", A),
    "gramps_create_blog_post": Slot("uc6", A, decoy_in=("uc17",)),
    "gramps_update_blog_post": Slot("uc17", A),
    "gramps_get_blog_post": Slot("uc17", A, secondary_in=("uc18",)),
    "gramps_list_blog_posts": Slot("uc17", A, secondary_in=("uc18",)),
    "gramps_delete_blog_post": Slot("uc18", A),
    "gramps_delete_person": Slot("uc5", A, decoy_in=("uc15", "uc16")),
    "gramps_delete_family": Slot("uc16", A, decoy_in=("uc15",)),
    "gramps_delete_all_objects": Slot("uc20", A, decoy_in=("uc5", "uc16", "uc18")),
    "gramps_export_tree": Slot("uc7", A, secondary_in=("uc20",)),
    "gramps_import_file": Slot("uc19", A),
    "gramps_get_object_counts": Slot("uc20", A, secondary_in=("uc27",)),
    "gramps_get_relations": Slot(
        "uc8", B, SUBSTITUTABLE_READ, secondary_in=("uc3", "uc14", "uc15")
    ),
    "gramps_get_ancestors": Slot("uc8", B, SUBSTITUTABLE_READ, secondary_in=("uc3",)),
    "gramps_get_descendants": Slot("uc24", B, SUBSTITUTABLE_READ),
    "gramps_search_person": Slot("uc25", B, SUBSTITUTABLE_READ),
    "gramps_list_people": Slot("uc27", B, SUBSTITUTABLE_READ),
    "gramps_get_person": Slot("uc26", B, SUBSTITUTABLE_READ),
}


def gating(grade: str) -> bool:
    """Whether a red assertion in this slot may fail the gate (D24). `B` never can."""
    return grade in (A, A_TWIN)
