# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""When a Stage-2 failure is allowed to become a report (plan T2.6, D24, decision e).

The repo is public and every issue on it is visible, so the bar is deliberately not "a run went
red". Three gates stand between a red assertion and a filed issue, and only the first two live
here — the third is the user, because Stage 2 never files by itself.

1. **Class A only.** A statement about the tree state, read over REST. `grading.failures()` is
   what enforces that; the model's account of what it did is not evidence and neither is the
   tool log.
2. **K of N.** A model is not a deterministic function, so one red run is a coin, not a finding.
   `K=3` failures out of at most `N=5` runs (D24), *sequentially* with early stop in **both**
   directions: stop as soon as the third failure lands, and stop as soon as three failures can
   no longer happen. Worst case is 5 runs, the common case is 1.
3. **Dedup on `(use_case, assertion_id)`.** An open issue for the same pair is commented on, not
   duplicated. Matched with a local `contains` over `gh issue list` output — never `gh search`,
   whose index lags by minutes and would file a second issue for a finding just reported.

An **inconclusive** run consumes an attempt and votes for nothing. That asymmetry is deliberate:
counting it as a pass would let a flaky harness bury a real defect, and counting it as a failure
would let a timeout file an issue.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from typing import Any

K_FAILURES = 3
N_RUNS = 5
WATCH_AT = 2

MARKER = "stage2-finding"


@dataclass(frozen=True)
class Attempt:
    """One run of one use case, already graded."""

    verdict: str
    failures: tuple[str, ...] = ()
    cost_usd: float = 0.0

    @property
    def failed(self) -> bool:
        return self.verdict == "OK" and bool(self.failures)

    @property
    def passed(self) -> bool:
        return self.verdict == "OK" and not self.failures


@dataclass(frozen=True)
class Verdict:
    """What N attempts of one use case add up to."""

    use_case: str
    attempts: tuple[Attempt, ...] = ()
    recurring: tuple[str, ...] = field(default=())

    @property
    def failures(self) -> int:
        return sum(1 for attempt in self.attempts if attempt.failed)

    @property
    def passes(self) -> int:
        return sum(1 for attempt in self.attempts if attempt.passed)

    @property
    def inconclusive(self) -> int:
        return len(self.attempts) - self.failures - self.passes

    @property
    def cost_usd(self) -> float:
        return sum(attempt.cost_usd for attempt in self.attempts)

    @property
    def reportable(self) -> bool:
        """Enough independent failures to be worth a human's attention."""
        return self.failures >= K_FAILURES and bool(self.recurring)

    @property
    def watch(self) -> bool:
        """Seen twice and not three times: a line in the report, never an issue (D24)."""
        return not self.reportable and self.failures >= WATCH_AT


def keep_going(
    failures: int, passes: int, attempts: int, *, k: int = K_FAILURES, n: int = N_RUNS
) -> bool:
    """Sequential escalation with early stop, in three directions rather than two.

    Repetition exists to **confirm a failure**, never to hunt for one — so a first run that
    passes ends the use case then and there. Stopping only on "k is now unreachable" would run
    a perfectly healthy use case four times and multiply the sweep's cost by four for nothing.

    An inconclusive run is not a result: while nothing conclusive has happened, the use case is
    retried, because a timeout has said neither yes nor no.
    """
    if attempts >= n or failures >= k:
        return False
    if failures == 0:
        return passes == 0  # nothing conclusive yet; a pass ends it
    return failures + (n - attempts) >= k


def escalate(
    use_case: str,
    attempt: Callable[[int], Attempt],
    *,
    k: int = K_FAILURES,
    n: int = N_RUNS,
) -> Verdict:
    """Run until the answer is settled. `attempt` is called with the attempt number, from 1."""
    attempts: list[Attempt] = []
    while True:
        attempts.append(attempt(len(attempts) + 1))
        failures = sum(1 for one in attempts if one.failed)
        passes = sum(1 for one in attempts if one.passed)
        if not keep_going(failures, passes, len(attempts), k=k, n=n):
            return Verdict(use_case, tuple(attempts), recurring(attempts, k=k))


def recurring(attempts: Sequence[Attempt], *, k: int = K_FAILURES) -> tuple[str, ...]:
    """The assertions that failed in at least `k` attempts.

    Per assertion, not per run: three runs that each failed a *different* assertion are three
    coins, and reporting them as one finding would put a claim in a public issue that no single
    run supports.
    """
    counted: dict[str, int] = {}
    for attempt in attempts:
        for failure in set(attempt.failures):
            counted[failure] = counted.get(failure, 0) + 1
    return tuple(sorted(name for name, seen in counted.items() if seen >= k))


def dedup_key(use_case: str, assertion_id: str) -> str:
    """The identity of a finding, as it appears verbatim in the issue body."""
    return f"{MARKER}: {use_case} / {assertion_id}"


def already_filed(key: str, issues: Sequence[dict[str, Any]]) -> int | None:
    """The open issue that already carries this finding, matched locally.

    `gh issue list --json number,title,body` is the input on purpose: `gh search` is served by
    an index that lags minutes behind, so a sweep that filed two findings in a row would not see
    its own first issue and would open a second for it.
    """
    for issue in issues:
        haystack = f"{issue.get('title', '')}\n{issue.get('body', '')}"
        if key in haystack:
            return int(issue["number"])
    return None
