# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""Grading: what the tree says, and nothing else (plan T2.5, gate 1).

The model's prose is not a parameter of any function here. Only the two captures around the
call are, plus — for the one class-B kind — the list of tools it called. That is decision (e)'s
first gate made structural: what can trigger a report is a deterministic statement about the
*tree state*, never the model's account of it.

Three things this module gets right that the design left implicit:

* **Subjects resolve against the `before` capture.** uc15 picks its household by the child the
  call is about to remove; resolved afterwards, that selector matches nothing and the use case
  reds for the reason it exists to test.
* **`new:<namespace>` comes from the movement difference**, not from the tool's report. The
  report echoes its own argument in every delete tool this server has, and a created id it
  merely repeats proves nothing about what arrived (checkpoint B1, D16).
* **`guards` are read.** They were validated as data by T2.2 and consumed by nobody, which
  makes an accidentally emptied `guards:` invisible. Here they are the standing check that the
  call touched nobody it was not about.

A failed check yields a failed `Outcome`; it does not raise. Raising is reserved for the harness
being wrong — a subject that no longer resolves against the fixture is not a finding about the
product, and it must stop the run rather than be reported as one.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from typing import Any

from harness.docker_util import ProbeError
from harness.movement import Movement, movement_of

from stage2 import checks_record, checks_tree, subjects
from stage2 import state as state_mod
from stage2.assertion_kinds import KINDS, A
from stage2.catalog import EVERYTHING, UseCase

CHECKS = {
    "counts": checks_tree.counts,
    "created": checks_tree.created,
    "removed": checks_tree.removed,
    "names_added": checks_tree.names_added,
    "tree_unchanged": checks_tree.tree_unchanged,
    "tree_empty": checks_tree.tree_empty,
    "backup_file": checks_tree.backup_file,
    "tool_log": checks_tree.tool_log,
    "person": checks_record.person,
    "alternates": checks_record.alternates,
    "family": checks_record.family,
    "tag": checks_record.tag,
    "source": checks_record.source,
    "note_body": checks_record.note_body,
}

GUARDED = ("people", "families", "sources")
GUARDS_ID = "guards"
MAXDROP_ID = "maxdrop"


@dataclass(frozen=True)
class BackupEntry:
    """One file that appeared in the mounted backup directory during the call."""

    name: str
    size: int
    text: str = ""


@dataclass(frozen=True)
class Outcome:
    """One graded statement. `grade` decides whether it may fail a run at all."""

    id: str
    kind: str
    grade: str
    passed: bool
    detail: str = ""


@dataclass(frozen=True)
class Evidence:
    """Everything a check may read, and the resolution rules it shares."""

    before: state_mod.State
    after: state_mod.State
    movement: Movement
    named: Mapping[str, Any]
    calls: tuple[str, ...] = ()
    backup: tuple[BackupEntry, ...] = ()

    def ids(self, name: str) -> str:
        """One subject's id. `new:<namespace>` is whatever arrived during this call."""
        resolved = self.id_set([name])
        if len(resolved) != 1:
            raise ProbeError(f"subject {name!r} names {len(resolved)} objects where one is meant")
        return resolved[0]

    def id_set(self, names: Iterable[str]) -> list[str]:
        """Several subjects, flattened — a `count:` subject stands for all of its matches."""
        found: list[str] = []
        for name in names:
            if str(name).startswith(subjects.NEW):
                found.append(self._arrival(str(name)))
                continue
            if name not in self.named:
                raise ProbeError(f"subject {name!r} is not declared by this use case")
            value = self.named[name]
            found.extend(value if isinstance(value, tuple) else [value])
        return sorted(found)

    def touched_in(self, namespace: str) -> set[str]:
        """Records that survived the call with a different signature — rewritten in place.

        Arrivals and departures are not "touched": they are the movement, and the `created`,
        `removed` and `counts` checks are what answer for them.
        """
        tags_before = state_mod.tag_handles(self.before)
        tags_after = state_mod.tag_handles(self.after)
        was, now = self.before.by_id(namespace), self.after.by_id(namespace)
        return {
            gramps_id
            for gramps_id in was.keys() & now.keys()
            if state_mod.signature(namespace, was[gramps_id], tags_before)
            != state_mod.signature(namespace, now[gramps_id], tags_after)
        }

    def touched(self) -> set[str]:
        return {
            f"{namespace}/{gramps_id}"
            for namespace in GUARDED
            for gramps_id in self.touched_in(namespace)
        }

    def _arrival(self, name: str) -> str:
        namespace = name[len(subjects.NEW) :]
        arrived = self.movement.added.get(namespace, [])
        if len(arrived) != 1:
            raise ProbeError(
                f"{name!r} means the one object that appeared in {namespace}, but "
                f"{len(arrived)} did ({arrived or 'none'})"
            )
        return arrived[0]


def evidence_for(
    use_case: UseCase,
    before: state_mod.State,
    after: state_mod.State,
    *,
    calls: Sequence[str] = (),
    backup: Sequence[BackupEntry] = (),
) -> Evidence:
    """Resolve the use case against the tree it started from. Raises if it no longer fits."""
    return Evidence(
        before=before,
        after=after,
        movement=movement_of(before.snapshot, after.snapshot),
        named=subjects.resolve_all(dict(use_case.subjects), before.tree),
        calls=tuple(calls),
        backup=tuple(backup),
    )


def grade(use_case: UseCase, evidence: Evidence) -> list[Outcome]:
    """Every declared assertion, plus the two standing ones the catalog carries as data."""
    outcomes = [_run(assertion, evidence) for assertion in use_case.assertions]
    outcomes.append(_guards(use_case, evidence))
    outcomes.append(_maxdrop(use_case, evidence))
    return outcomes


def failures(outcomes: Sequence[Outcome]) -> list[Outcome]:
    """What may fail a run: class A only. Class B is collected and never gates."""
    return [outcome for outcome in outcomes if not outcome.passed and outcome.grade == A]


def _run(assertion: Any, evidence: Evidence) -> Outcome:
    kind = KINDS[assertion.kind]
    try:
        detail = CHECKS[assertion.kind](assertion.params, evidence)
    except ProbeError as error:
        # A subject that cannot be resolved *after* the call is a statement about the call —
        # `new:people` with nothing new is exactly the failure the use case is looking for.
        detail = str(error)
    return Outcome(assertion.id, assertion.kind, kind.grade, detail is None, detail or "")


def _guards(use_case: UseCase, evidence: Evidence) -> Outcome:
    """Nobody but the declared subjects was rewritten."""
    if use_case.guards == EVERYTHING:
        return Outcome(f"{use_case.id}/{GUARDS_ID}", GUARDS_ID, A, True, "")
    stray: dict[str, list[str]] = {}
    for namespace, names in dict(use_case.guards).items():
        allowed = set(evidence.id_set(names))
        wrongly = sorted(evidence.touched_in(namespace) - allowed)
        if wrongly:
            stray[namespace] = wrongly
    detail = f"records outside this use case's subjects were rewritten: {stray}" if stray else ""
    return Outcome(f"{use_case.id}/{GUARDS_ID}", GUARDS_ID, A, not stray, detail)


def _maxdrop(use_case: UseCase, evidence: Evidence) -> Outcome:
    """The standing no-mass-deletion guard, per namespace (T2.3)."""
    identifier = f"{use_case.id}/{MAXDROP_ID}"
    if use_case.maxdrop == EVERYTHING:
        return Outcome(identifier, MAXDROP_ID, A, True, "")
    lost = {
        namespace: len(gone)
        for namespace, gone in evidence.movement.removed.items()
        if len(gone) > int(use_case.maxdrop)
    }
    detail = f"lost {lost}, more than maxdrop={use_case.maxdrop}" if lost else ""
    return Outcome(identifier, MAXDROP_ID, A, not lost, detail)
