# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""No prompt may name the tool it expects (plan T2.7). No Docker, no LLM, no cost.

Stage 2 measures one thing: whether a model that sees **only the docstrings** picks the right
tool. A prompt that contains a token belonging to exactly one tool's *name* does not measure
that — it hands the answer over, the run comes back green, and the green says nothing about
the docstring. That failure is invisible from the outside: the use case still passes, still
costs its dollar, still appears in the coverage map.

So the rule is mechanical and runs with the linters:

    a prompt token that appears in the name of exactly one registered tool is a leak.

Two escape hatches, both built so they cannot rot:

* **`DOMAIN_WORDS`** — words that *are* the domain and no user can avoid. There are two of
  them, and a test asserts that each is actually needed by some prompt.
* **per-use-case waivers** — `leak_waivers:` in the use-case file, each with a written reason.
  A waiver for a token the lint does not flag is itself an error, so a rewritten prompt cannot
  leave a permanent exemption behind.

**What this does not do.** It reads tool *names*, not docstrings: a prompt that borrows a
distinctive phrase out of one docstring (the design's severity L2) still needs a human to
notice. And a leak-free prompt can still be unfair in the other direction. This lint closes
the mechanical half, which is the half that silently comes back green.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

PREFIX = "gramps_"
WORD = re.compile(r"[a-z]+")

# The two nouns the domain is made of. `people` belongs to `gramps_list_people` alone and
# `tree` to `gramps_export_tree` alone, so the rule flags them — but a genealogist asking
# anything at all says "in my tree" and "the people in it", and there is no paraphrase that is
# not more obscure. Kept short deliberately: every entry is a hole in the guard, and
# `test_00_stage2_leak.py` deletes one that stops being necessary.
#
# **The exemption stops at the use case's own primary.** A word may be unavoidable and still be
# the name of the tool under test — uc7 asking for a copy of "the tree" would hand
# `gramps_export_tree` over, and a green run would then say nothing about its docstring. So
# `leaks()` takes the primaries and refuses to exempt a token they own.
DOMAIN_WORDS = frozenset({"people", "tree"})

# English glue that happens to sit in a tool name: `add_child_to_family` owns "to" and
# `remove_child_from_family` owns "from". Nobody writes a prompt without them, and neither word
# carries a gram of signal about which tool to reach for. Not the same concession as
# DOMAIN_WORDS — those are nouns a use case really is about.
FUNCTION_WORDS = frozenset({"to", "from"})


@dataclass(frozen=True)
class Leak:
    """One prompt token and the single tool whose name it gives away."""

    token: str
    tool: str


def fold(word: str) -> str:
    """Crude singular fold, applied to both sides so `objects` still meets `object`."""
    return word[:-1] if len(word) > 3 and word.endswith("s") else word


def tokens(text: str) -> list[str]:
    """Every word of a text, lowercased, folded, in order and without repeats."""
    seen: dict[str, None] = {}
    for word in WORD.findall(text.lower()):
        seen.setdefault(fold(word), None)
    return list(seen)


def name_tokens(tool: str) -> frozenset[str]:
    """A tool name's own words — `gramps_add_child_to_family` is add/child/to/family."""
    return frozenset(fold(part) for part in tool.removeprefix(PREFIX).split("_") if part)


def owners(tools: list[str] | set[str]) -> dict[str, set[str]]:
    """token -> the tools whose names contain it. A token owned by one tool is the leak."""
    index: dict[str, set[str]] = {}
    for tool in tools:
        for token in name_tokens(tool):
            index.setdefault(token, set()).add(tool)
    return index


def leaks(
    prompt: str, tools: list[str] | set[str], primary: list[str] | set[str] = ()
) -> list[Leak]:
    """Every token of this prompt that points at exactly one tool.

    `primary` is the tools the use case is a test of: a domain word they own is reported
    anyway, because that is the one place the exemption would cost the measurement.
    """
    index = owners(tools)
    found = []
    for token in tokens(prompt):
        if token in FUNCTION_WORDS:
            continue
        candidates = index.get(token, set())
        if len(candidates) != 1:
            continue
        owner = next(iter(candidates))
        if token in DOMAIN_WORDS and owner not in set(primary):
            continue
        found.append(Leak(token=token, tool=owner))
    return found


def unwaived(found: list[Leak], waived: set[str]) -> list[Leak]:
    """The leaks nobody wrote a reason for — these fail the lint."""
    return [leak for leak in found if leak.token not in waived]


def stale(found: list[Leak], waived: set[str]) -> set[str]:
    """Waivers for tokens this prompt no longer contains.

    A rewritten prompt that leaves its waiver behind quietly re-arms the leak: the next edit
    that reintroduces the word passes the lint because an exemption is already sitting there.
    """
    return waived - {leak.token for leak in found}
