# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""The `--mcp-config` file Stage 2 hands to `claude -p` (plan T2.4, D9).

**One spawn shape.** The argv is `McpContainer.run_args()` — the same one Stage 1 spawns and
asserts against, reused rather than re-typed. Two hand-written spawn lines would drift, and the
one that drifts is the one nobody runs by hand.

**The working tree, not the copy in the image.** What Stage 2 grades is a docstring, and the
docstring lives in `server.py`; the image holds a copy made at build time. So every root-level
module is bind-mounted read-only over `/app` (D9) and the Stage-2 loop — edit docstring, rerun
— grades the edit instead of the last build.

The mount list is **derived** from the repo root, never enumerated. The Dockerfile's explicit
`COPY` list is the enumeration that has shipped a broken image twice by falling behind the
tree. A second list here would fall behind it the same way, except the failure would be
silent: a new module would simply be graded as whatever the image happens to hold.

The consequence is stated rather than hidden: because the tree is mounted over the image,
Stage 2 **cannot** see a module missing from that `COPY` list. That is Stage 1's job, and
`test_04_mcp_container.py` does it on the unmounted image.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from harness.mcp_container import ImageRef, McpContainer, container_name

REPO_ROOT = Path(__file__).resolve().parents[3]

SERVER_NAME = "gramps"
IMAGE_WORKDIR = "/app"
BACKUP_TARGET = "/backup"
LABEL = "stage2"


def module_mounts(repo_root: Path = REPO_ROOT) -> tuple[tuple[str, str], ...]:
    """One read-only `-v` pair per root module (D9).

    The container side carries the `:ro` option because that is docker's own `src:dst:opts`
    syntax — the run reaches `/app/server.py` and cannot write back into the working tree.
    """
    return tuple(
        (str(path), f"{IMAGE_WORKDIR}/{path.name}:ro") for path in sorted(repo_root.glob("*.py"))
    )


def build(
    image: ImageRef,
    *,
    network: str,
    gramps_env: Mapping[str, str],
    backup_dir: Path,
    runid: str = "",
    repo_root: Path = REPO_ROOT,
) -> dict[str, Any]:
    """The whole config, as the object `claude -p` reads."""
    env = {
        # uc5 and uc20 are delete use cases; without the flag those tools are not registered,
        # and "the model did not call it" would be indistinguishable from a docstring defect.
        "GRAMPS_ENABLE_DESTRUCTIVE": "1",
        "GRAMPS_BACKUP_DIR": BACKUP_TARGET,
        **gramps_env,
    }
    container = McpContainer(
        container_name(runid, LABEL),
        image.run_reference,
        env,
        network=network,
        mounts=(*module_mounts(repo_root), (str(backup_dir), BACKUP_TARGET)),
        runid=runid or None,
    )
    args = container.run_args()
    return {
        "mcpServers": {
            SERVER_NAME: {
                "type": "stdio",
                "command": args[0],
                "args": args[1:],
                "env": {},
            }
        }
    }


def write(path: Path, config: dict[str, Any]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
    return path
