# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""One use case, run against a real model, written down (plan T2.4).

What this module owns is the part that must be the same for every use case: an empty working
directory, one config, the guarded invocation, and a directory per run holding the evidence —
`argv.json`, `run.jsonl`, `run.err`. Decision (d) makes that log mandatory: a non-deterministic
failure nobody can read afterwards is worth nothing.

It deliberately does **not** grade. Grading reads the tree over REST (T2.5, class A only); the
model's prose is not a parameter of it. What this module produces is a verdict about the *run*:

* `OK` — a clean, finished run. The only kind T2.5 may grade and T2.6 may count.
* `HARNESS_BROKEN` — the run proves nothing (see `selfcheck`). Abort the sweep; fix the harness.
* `INCONCLUSIVE` — clean but unfinished: the wall-clock cap fired, or the CLI died without a
  result event. Not evidence either way, and never a K-of-N vote.

The subprocess is injected (`spawn=`) for the same reason time is injected in the product's
polling loops: the tests that keep this honest must not need a subscription, a model or Docker.
"""

from __future__ import annotations

import json
import os
import subprocess
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol

from harness.docker_util import ProbeError
from harness.mcp_container import ImageRef

from stage2 import driver, mcp_config, selfcheck, transcript
from stage2.catalog import UseCase

OK = "OK"
HARNESS_BROKEN = "HARNESS_BROKEN"
INCONCLUSIVE = "INCONCLUSIVE"

CWD_NAME = "cwd"
CONFIG_NAME = "mcp.json"


class Spawn(Protocol):
    """The seam. Returns the exit code and whatever the process wrote to stderr."""

    def __call__(
        self,
        argv: list[str],
        *,
        cwd: Path,
        env: Mapping[str, str],
        stdout: Path,
        timeout: float,
    ) -> tuple[int, str]: ...


@dataclass(frozen=True)
class Run:
    """One use case, once. `transcript` is `None` only when there was nothing to parse."""

    use_case: str
    verdict: str
    reason: str | None
    run_dir: Path
    argv: tuple[str, ...]
    transcript: transcript.Transcript | None

    @property
    def cost_usd(self) -> float:
        return self.transcript.cost_usd if self.transcript else 0.0

    @property
    def gradeable(self) -> bool:
        return self.verdict == OK


def spawn_claude(
    argv: list[str],
    *,
    cwd: Path,
    env: Mapping[str, str],
    stdout: Path,
    timeout: float,
) -> tuple[int, str]:
    """The real one. `stdin=DEVNULL` is not cosmetic — without it the CLI waits 3 s per run."""
    with stdout.open("w", encoding="utf-8") as sink:
        try:
            done = subprocess.run(
                argv,
                cwd=cwd,
                env=dict(env),
                stdin=subprocess.DEVNULL,
                stdout=sink,
                stderr=subprocess.PIPE,
                text=True,
                timeout=timeout,
            )
        except subprocess.TimeoutExpired:
            return 124, f"timed out after {timeout:.0f}s"
    return done.returncode, done.stderr


class Runner:
    """The Stage-2 driver for one instance: prepared once, run per use case."""

    def __init__(
        self,
        *,
        image: ImageRef,
        network: str,
        gramps_env: Mapping[str, str],
        backup_dir: Path,
        run_root: Path,
        runid: str = "",
        spawn: Spawn = spawn_claude,
        environ: Mapping[str, str] | None = None,
        timeout_s: float = driver.TIMEOUT_S,
    ) -> None:
        self.run_root = run_root
        self.cwd = run_root / CWD_NAME
        self.config_path = run_root / CONFIG_NAME
        self.spawn = spawn
        self.timeout_s = timeout_s
        self.environ = dict(environ if environ is not None else os.environ)
        self._config = mcp_config.build(
            image,
            network=network,
            gramps_env=gramps_env,
            backup_dir=backup_dir,
            runid=runid,
        )

    def prepare(self) -> Path:
        """Write the config and make the empty working directory the invocation requires."""
        self.cwd.mkdir(parents=True, exist_ok=True)
        driver.assert_clean_cwd(self.cwd)
        return mcp_config.write(self.config_path, self._config)

    def run(self, use_case: UseCase) -> Run:
        """One use case: spawn, keep the evidence, decide whether the run counts."""
        run_dir = self.run_root / use_case.slug
        run_dir.mkdir(parents=True, exist_ok=True)
        log, errors = run_dir / "run.jsonl", run_dir / "run.err"

        argv = driver.build_argv(use_case.prompt, config=self.config_path)
        environment = driver.run_env(self.environ)
        driver.assert_usable(argv, environment)
        (run_dir / "argv.json").write_text(json.dumps(argv, indent=2), encoding="utf-8")

        code, stderr = self.spawn(
            argv, cwd=self.cwd, env=environment, stdout=log, timeout=self.timeout_s
        )
        errors.write_text(stderr, encoding="utf-8")

        return self._verdict(use_case, argv, run_dir, log, code, stderr)

    def _verdict(
        self,
        use_case: UseCase,
        argv: list[str],
        run_dir: Path,
        log: Path,
        code: int,
        stderr: str,
    ) -> Run:
        def result(verdict: str, reason: str | None, parsed: Any = None) -> Run:
            return Run(use_case.id, verdict, reason, run_dir, tuple(argv), parsed)

        try:
            parsed = transcript.load(log)
        except ProbeError as error:
            # No parsable log: the process was killed, or never started. Either way this says
            # nothing about the docstrings, so it must not reach the counter as a failure.
            return result(INCONCLUSIVE, f"exit {code}: {error} | stderr: {stderr.strip()[:400]}")

        try:
            selfcheck.verify(parsed, cwd=str(self.cwd))
        except selfcheck.HarnessBroken as broken:
            return result(HARNESS_BROKEN, str(broken), parsed)

        reason = selfcheck.inconclusive_reason(parsed)
        if reason:
            return result(INCONCLUSIVE, reason, parsed)
        return result(OK, None, parsed)
