# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""Prove the run was a Stage-2 run before grading it (plan T2.4).

Five flag configurations were measured to leave the model with **no gramps tools at all**, and
so does a missing `--strict-mcp-config` that quietly attaches somebody else's server. Every one
of them produces the same symptom as a catastrophic docstring defect: no calls, every assertion
red. This module is what stands between that symptom and a filed issue.

Two outcomes, deliberately not merged into one:

* **`HarnessBroken`** — the run proves nothing about the product. It is not a failure of the
  thing under test, it is a failure to test it. Abort; never count it towards K-of-N.
* **inconclusive** — the run was clean but did not finish arguing (too many turns, an errored
  result). Also not evidence, and also not a harness fault.

Everything checked here is a **measured** fact of `claude 2.1.220`'s init event, not a
transcription of the design note. Two of the note's claims did not survive contact:

* the wire keys are the lists `skills` / `plugins` / `slash_commands`, not `n_skills` /
  `n_plugins` / `n_slash`. A check written from the note would have read a key nobody emits and
  passed on every contaminated run there is — so an **absent** key is treated as broken here;
* at init the gramps server's status is `pending` and `tools` is `["ToolSearch"]`, because MCP
  tools are deferred. "Connected" is therefore not observable in the init event, and gating on
  it would red every run. The evidence used instead is behavioural: a `tool_reference` naming
  `mcp__gramps__…`, or a call to one.
"""

from __future__ import annotations

import re

from harness.docker_util import ProbeError

from stage2 import transcript
from stage2.driver import MODEL, VERIFIED_CLI_VERSION
from stage2.mcp_config import SERVER_NAME

# The observed signature of the user's global CLAUDE.md steering the run: every reply opened
# with the German echo rule. If isolation ever slips, this is what it looks like.
CANARY = re.compile(r"^\s*Verstanden")

# Measured on the clean run: the five built-in agents and nothing else. An uncontrolled run
# reported 41.
BUILT_IN_AGENTS = 5

# Undocumented `--max-turns` is not built on (salvage §1); the ceiling is observed instead.
MAX_TURNS = 12

MUST_BE_EMPTY = ("skills", "plugins", "slash_commands")

MUST_EQUAL = {
    "permissionMode": "bypassPermissions",
    "apiKeySource": "none",
    "claude_code_version": VERIFIED_CLI_VERSION,
    "model": MODEL,
}

WHY = {
    "permissionMode": "an unattended run that can be asked for permission is a run that stalls",
    "apiKeySource": "an inherited API key moves the run off the subscription — different "
    "account, different billing, and `total_cost_usd` then measures the wrong thing",
    "claude_code_version": "every flag in the invocation was validated by execution against "
    "this build; another build may reinterpret one of them silently",
    "model": "an unpinned model moves the Stage-2 baseline between runs",
}


class HarnessBroken(ProbeError):
    """The run cannot be graded. Not a product finding — a harness fault."""


def verify(run: transcript.Transcript, *, cwd: str) -> None:
    """Refuse a run that proves nothing. Raises `HarnessBroken`, or returns."""
    _verify_isolation(run)
    _verify_servers(run)
    _verify_configuration(run, cwd=cwd)
    _verify_reachability(run)
    _verify_no_leaked_memory(run)

    if run.permission_denials:
        raise HarnessBroken(
            f"the run recorded permission denials ({run.permission_denials}) — the model was "
            "fenced in, so what it did not do says nothing about the docstrings"
        )


def inconclusive_reason(run: transcript.Transcript) -> str | None:
    """Why this run is not evidence either way, or `None` if it is."""
    if run.num_turns > MAX_TURNS:
        return (
            f"the model took {run.num_turns} turns (ceiling {MAX_TURNS}) — it ran out of room "
            "rather than reaching a conclusion"
        )
    if run.is_error or run.subtype != "success":
        return f"the run ended as {run.subtype!r} (is_error={run.is_error})"
    return None


def _verify_isolation(run: transcript.Transcript) -> None:
    for field in MUST_BE_EMPTY:
        if field not in run.init:
            raise HarnessBroken(
                f"the init event carries no {field!r} — an absent key is an unknown "
                "configuration, not a clean one"
            )
        if run.init[field]:
            raise HarnessBroken(
                f'{field} is not empty ({run.init[field]!r}) — `--setting-sources ""` did not '
                "take, and the run is steered by whatever it loaded"
            )

    if "agents" not in run.init:
        raise HarnessBroken("the init event carries no 'agents'")
    if len(run.init["agents"]) > BUILT_IN_AGENTS:
        raise HarnessBroken(
            f"agents: {len(run.init['agents'])} are loaded, more than the {BUILT_IN_AGENTS} "
            "built-ins — the user's own agent definitions are in the run"
        )


def _verify_servers(run: transcript.Transcript) -> None:
    if "mcp_servers" not in run.init:
        raise HarnessBroken("the init event carries no 'mcp_servers'")

    names = [str(server.get("name", "")) for server in run.init["mcp_servers"]]
    if names != [SERVER_NAME]:
        raise HarnessBroken(
            f"mcp_servers is {names} — expected exactly [{SERVER_NAME!r}]. Anything else means "
            "`--strict-mcp-config` did not hold and the run is grading another server's tools"
        )


def _verify_configuration(run: transcript.Transcript, *, cwd: str) -> None:
    for field, expected in MUST_EQUAL.items():
        actual = run.init.get(field)
        if actual != expected:
            raise HarnessBroken(f"{field} is {actual!r}, expected {expected!r} — {WHY[field]}")

    if run.init.get("cwd") != cwd:
        raise HarnessBroken(
            f"cwd is {run.init.get('cwd')!r}, expected {cwd!r} — the run must sit in an empty "
            "scratch directory, or it discovers a CLAUDE.md, an .mcp.json and a memory of its own"
        )


def _verify_reachability(run: transcript.Transcript) -> None:
    """The single most expensive false red there is, turned into an abort."""
    surfaced = any(name.startswith(transcript.MCP_PREFIX) for name in run.references)
    if not run.gramps_calls and not surfaced:
        raise HarnessBroken(
            "no gramps tool was ever called or even surfaced by ToolSearch — the server was "
            "not reachable from this run, which reads exactly like a total docstring failure "
            "and is not one"
        )


def _verify_no_leaked_memory(run: transcript.Transcript) -> None:
    if CANARY.match(run.text):
        raise HarnessBroken(
            "the CLAUDE.md canary fired: the reply opens with 'Verstanden', which is the user's "
            "global memory steering a run that is supposed to see none of it"
        )
