# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""The tree as the grader sees it: one capture before the call, one after (plan T2.5).

Grading is **pure** over these two captures. Nothing in `checks_*.py` may reach for the network,
for the same reason the product's polling loops take an injected clock: a grader that makes its
own REST calls can only be tested against a live instance, and the checks that decide whether a
public issue gets filed are exactly the ones that must be testable for free.

It also fixes an ordering trap the design walked into. Subjects are resolved against the
**before** capture — uc15 picks its household by the child the call is about to remove, so a
selector resolved afterwards matches nothing and the use case reds for the reason it exists to
test.

`snapshot` is the `{counts, objects}` shape `harness/movement.py` already eats, so identity
movement is computed by the same code Stage 1 uses rather than a second implementation of the
same set difference.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from stage2 import subjects

# Everything a class-A assertion can read. `notes` and `tags` are counted namespaces and both
# move on writes nobody asked for — a blog post creates a tag, `add_person` creates another.
NAMESPACES = ("people", "families", "sources", "notes", "tags")


@dataclass(frozen=True)
class State:
    """Counts and full records, taken at one instant."""

    counts: dict[str, int]
    records: dict[str, tuple[dict[str, Any], ...]]

    def of(self, namespace: str) -> tuple[dict[str, Any], ...]:
        return self.records.get(namespace, ())

    def by_id(self, namespace: str) -> dict[str, dict[str, Any]]:
        return {str(record.get("gramps_id", "")): record for record in self.of(namespace)}

    def by_handle(self, namespace: str) -> dict[str, dict[str, Any]]:
        return {str(record.get("handle", "")): record for record in self.of(namespace)}

    def handle_to_id(self, namespace: str = "people") -> dict[str, str]:
        return {
            str(record.get("handle", "")): str(record.get("gramps_id", ""))
            for record in self.of(namespace)
        }

    @property
    def snapshot(self) -> dict[str, Any]:
        """The identity view `movement_of` diffs — same shape as `GrampsRest.snapshot()`."""
        return {
            "counts": dict(self.counts),
            "total": sum(self.counts.values()),
            "objects": {
                namespace: sorted(
                    (str(record.get("gramps_id", "")), str(record.get("handle", "")))
                    for record in self.of(namespace)
                )
                for namespace in sorted(self.records)
            },
        }

    @property
    def tree(self) -> subjects.Tree:
        """The selector view, so a use case's subjects resolve against the live tree."""
        ids = self.handle_to_id()
        return subjects.Tree(
            people=tuple(
                {
                    "gramps_id": str(person.get("gramps_id", "")),
                    "first_name": first_name(person),
                    "surname": surname(person),
                }
                for person in self.of("people")
            ),
            families=tuple(
                {
                    "gramps_id": str(family.get("gramps_id", "")),
                    "members": frozenset(members(family, ids)),
                    "children": frozenset(children(family, ids)),
                }
                for family in self.of("families")
            ),
            sources=tuple(
                {"gramps_id": str(source.get("gramps_id", "")), "title": source.get("title", "")}
                for source in self.of("sources")
            ),
        )


def capture(rest: Any) -> State:
    """One REST read per namespace. The only place in T2.5 that touches the network."""
    counts = rest.object_counts()
    return State(
        counts=dict(counts),
        records={namespace: tuple(rest.objects(namespace)) for namespace in NAMESPACES},
    )


def first_name(person: Mapping[str, Any]) -> str:
    return str((person.get("primary_name") or {}).get("first_name", ""))


def surname(person: Mapping[str, Any]) -> str:
    return name_surname(person.get("primary_name") or {})


def name_surname(name: Mapping[str, Any]) -> str:
    entries = name.get("surname_list") or []
    return str(entries[0].get("surname", "")) if entries else ""


def name_type(name: Mapping[str, Any]) -> str:
    """Measured 2026-07-31: the API answers with a bare string (`"Married Name"`)."""
    return str(name.get("type", ""))


def members(family: Mapping[str, Any], ids: Mapping[str, str]) -> list[str]:
    """Both parent slots, as ids. Never *which* slot — that assignment is what uc2 tests."""
    return sorted(
        ids[handle]
        for handle in (family.get("father_handle"), family.get("mother_handle"))
        if handle and handle in ids
    )


def children(family: Mapping[str, Any], ids: Mapping[str, str]) -> list[str]:
    return sorted(
        ids[str(ref.get("ref", ""))]
        for ref in family.get("child_ref_list") or []
        if str(ref.get("ref", "")) in ids
    )


def tag_names(record: Mapping[str, Any], tags: Mapping[str, str]) -> tuple[str, ...]:
    """A record's tags by name.

    By name and not by handle on purpose: an import re-creates an identical tag as a *new*
    object (measured — uc19's import brings its own `Unbestätigt` and Gramps does not merge),
    and a bystander whose tag handle moved underneath them has not been touched by the call.
    """
    return tuple(sorted(tags[handle] for handle in record.get("tag_list") or [] if handle in tags))


def person_signature(person: Mapping[str, Any], tags: Mapping[str, str]) -> tuple[Any, ...]:
    """What "this person was not touched" means.

    `family_list` is deliberately **not** in it. Deleting a family rewrites the membership of
    both spouses, and uc16 does exactly that on purpose; including it would red every bystander
    of a legitimate call. Family membership is asserted where it is the point, by the `family`
    kind, against named subjects.
    """
    alternates = tuple(
        (name_surname(name), name_type(name)) for name in person.get("alternate_names") or []
    )
    return (
        first_name(person),
        surname(person),
        name_type(person.get("primary_name") or {}),
        person.get("gender"),
        tag_names(person, tags),
        alternates,
    )


def family_signature(family: Mapping[str, Any], ids: Mapping[str, str]) -> tuple[Any, ...]:
    """Both parent slots *and* which slot each sits in: a swap is a change, and uc2 says so."""
    return (
        ids.get(str(family.get("father_handle") or ""), ""),
        ids.get(str(family.get("mother_handle") or ""), ""),
        tuple(children(family, ids)),
    )


def source_signature(source: Mapping[str, Any], tags: Mapping[str, str]) -> tuple[Any, ...]:
    """Title, author and which notes hang off it — the note's *text* belongs to the note."""
    return (
        source.get("title", ""),
        source.get("author", ""),
        tuple(source.get("note_list") or []),
        tag_names(source, tags),
    )


def signature(
    namespace: str, record: Mapping[str, Any], tags: Mapping[str, str]
) -> tuple[Any, ...]:
    """What "this record was not touched" means, per namespace.

    `people` needs the handle→id map for nothing, `families` needs it for everything; the map is
    rebuilt from the record's own capture by the caller that holds it.
    """
    if namespace == "families":
        return family_signature(record, _ids_of(record))
    if namespace == "sources":
        return source_signature(record, tags)
    return person_signature(record, tags)


def _ids_of(family: Mapping[str, Any]) -> dict[str, str]:
    """Families are compared by *handle* rather than id: the map belongs to a capture, and a
    signature is per record. Handles are stable across a call, which is the property needed."""
    return {
        handle: handle
        for handle in (
            str(family.get("father_handle") or ""),
            str(family.get("mother_handle") or ""),
            *(str(ref.get("ref", "")) for ref in family.get("child_ref_list") or []),
        )
        if handle
    }


def tag_handles(state: State) -> dict[str, str]:
    """`handle -> tag name`, which is how a person's `tag_list` becomes readable."""
    return {str(tag.get("handle", "")): str(tag.get("name", "")) for tag in state.of("tags")}
