# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""Who a use case is about, resolved from the tree rather than written down (plan T2.2).

The Stage-2 design wires `I0001…I0005` into its use cases. Real ids start at `I0000` — the
bootstrap probe caught that — and the deeper problem is that an id is not a property of the
person: regrow the fixture, add one subject in the middle, import a file that renumbers a
collision, and every hardcoded id now points at somebody else while every assertion stays
green. So a use case names its subjects by what a *user* would say about them, and this module
turns that into ids against the tree the run actually starts from.

Two rules, both there to make a wrong selector loud:

* **Exactly one match, or `ProbeError`.** Zero matches is a fixture that moved; two matches is
  a prompt the model cannot disambiguate either, which makes the use case unfair rather than
  merely broken. Both must stop the run instead of grading it.
* **Only known terms.** A mistyped `firstname:` would match nobody and read as "the fixture
  changed"; it is rejected as what it is.

Families are selected by their *members*, never by which slot a member sits in. The slot
assignment is the product's own rule (`server.py:134-141`, female becomes the mother) and
several use cases exist to test exactly that — a selector that assumed it would be asserting
the answer it is supposed to be asking.
"""

from __future__ import annotations

import re
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from harness.docker_util import ProbeError

# `{target}` in a prompt is filled with that subject's id at run time. uc26 asks for a record
# *by* id, which makes it the one prompt that has to carry one — and an id is exactly what a
# use case may not write down, so it has to be substituted from the tree the run starts on.
PLACEHOLDER = re.compile(r"\{([a-z_]+)\}")

TERMS: dict[str, frozenset[str]] = {
    "people": frozenset({"first_name", "surname", "count"}),
    "families": frozenset({"members", "children"}),
    "sources": frozenset({"title"}),
}
# `count: 7` makes a subject plural — "every Aschenblum", which uc21 rewrites in one bulk call.
# It is not a relaxation: the number is still exact, and it is the only way to name a group
# whose members are not individually distinguishable by name (the fixture holds two people
# called Anselm Aschenblum, which is also why the model cannot be asked to pick one).
COUNT = "count"
# A subject that does not exist yet: `new:people` is whatever appeared in that namespace
# during the call. Assertions may name it, `subjects:` may not declare it.
NEW = "new:"


@dataclass(frozen=True)
class Tree:
    """The three namespaces a selector can point into, in one shape.

    Built from `cast.py` for the Docker-free checks and from a REST snapshot at run time, so
    the catalog is validated against the same view it is later resolved against.
    """

    people: tuple[dict[str, Any], ...]
    families: tuple[dict[str, Any], ...]
    sources: tuple[dict[str, Any], ...]

    def namespace(self, name: str) -> tuple[dict[str, Any], ...]:
        return {"people": self.people, "families": self.families, "sources": self.sources}[name]


def from_cast(cast: Any) -> Tree:
    """The committed fixture, as the state every Stage-2 run is reset to."""
    return Tree(
        people=tuple(
            {
                "gramps_id": person["gramps_id"],
                "first_name": person["first_name"],
                "surname": person["surname"],
            }
            for person in cast.PEOPLE
        ),
        families=tuple(
            {
                "gramps_id": family["gramps_id"],
                "members": frozenset(
                    member
                    for member in (family["spouse_a"], family["spouse_b"])
                    if member is not None
                ),
                "children": frozenset(family["children"]),
            }
            for family in cast.FAMILIES
        ),
        sources=tuple(
            {"gramps_id": source["gramps_id"], "title": source["title"]} for source in cast.SOURCES
        ),
    )


def selector_namespace(selector: dict[str, Any]) -> str:
    namespace = selector.get("namespace")
    if namespace not in TERMS:
        raise ProbeError(f"selector {selector!r} names no known namespace {sorted(TERMS)}")
    return str(namespace)


def check_terms(name: str, selector: dict[str, Any]) -> None:
    """Every term this selector uses is one the namespace understands."""
    namespace = selector_namespace(selector)
    unknown = set(selector) - {"namespace"} - TERMS[namespace]
    if unknown:
        raise ProbeError(
            f"subject {name!r} uses {sorted(unknown)}, which {namespace} selectors do not know "
            f"— known terms are {sorted(TERMS[namespace])}"
        )
    if not set(selector) - {"namespace"}:
        raise ProbeError(f"subject {name!r} selects the whole {namespace} namespace")


def resolve(name: str, selector: dict[str, Any], tree: Tree, known: dict[str, Any]) -> Any:
    """One subject's gramps_id — or, with `count`, exactly that many of them."""
    check_terms(name, selector)
    namespace = selector_namespace(selector)
    wanted = int(selector[COUNT]) if COUNT in selector else 1
    matched = [
        record
        for record in tree.namespace(namespace)
        if _matches(namespace, selector, record, known)
    ]
    if len(matched) != wanted:
        raise ProbeError(
            f"subject {name!r} ({selector!r}) matches {len(matched)} objects in {namespace}"
            f"{': ' + ', '.join(str(m['gramps_id']) for m in matched) if matched else ''} — it "
            f"has to match exactly {wanted}, and so does the model reading the prompt"
        )
    if COUNT in selector:
        return tuple(str(record["gramps_id"]) for record in matched)
    return str(matched[0]["gramps_id"])


def resolve_all(subjects: dict[str, dict[str, Any]], tree: Tree) -> dict[str, Any]:
    """Every subject of one use case. People first: a family selector references them."""
    resolved: dict[str, Any] = {}
    for wanted in ("people", "families", "sources"):
        for name, selector in subjects.items():
            if selector.get("namespace") == wanted:
                resolved[name] = resolve(name, selector, tree, resolved)
    unresolved = set(subjects) - set(resolved)
    if unresolved:
        raise ProbeError(f"{sorted(unresolved)} name no known namespace")
    return resolved


def fill(prompt: str, resolved: Mapping[str, Any]) -> str:
    """The prompt a model actually gets: every `{subject}` replaced by the id it resolved to."""
    return PLACEHOLDER.sub(lambda found: _written(resolved, found), prompt)


def unfilled(prompt: str) -> list[str]:
    """Placeholders still standing in a prompt that is about to be sent.

    Never a formality. `validate.py` checked that `{target}` named a declared subject and the
    docstring said it was "filled at run time" — and **nothing filled it**. uc26 went to a real
    model with a literal `{target}` in it; the model asked what that was supposed to mean and
    called no tool, which from outside is indistinguishable from every gramps tool being
    undiscoverable. The sweep aborted on evidence about itself, after paying for the run.
    """
    return sorted(set(PLACEHOLDER.findall(prompt)))


def _written(resolved: Mapping[str, Any], found: re.Match[str]) -> str:
    """A plural subject (`count: 7`) is written out as the list a person would say."""
    value = resolved.get(found.group(1))
    if value is None:
        return found.group(0)
    return ", ".join(str(item) for item in value) if isinstance(value, tuple) else str(value)


def _matches(namespace: str, selector: dict[str, Any], record: dict[str, Any], known: dict) -> bool:
    if namespace == "families":
        return _family_matches(selector, record, known)
    return all(
        record.get(term) == value
        for term, value in selector.items()
        if term not in ("namespace", COUNT)
    )


def _family_matches(selector: dict[str, Any], record: dict[str, Any], known: dict) -> bool:
    for term in ("members", "children"):
        if term not in selector:
            continue
        if record[term] != {_referenced(name, known) for name in selector[term]}:
            return False
    return True


def _referenced(name: str, known: dict[str, str]) -> str:
    if name not in known:
        raise ProbeError(f"a family selector references {name!r} before it is resolved")
    return known[name]
