# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""The sweep: reset, run, capture, grade — once per use case, K times if it fails (T2.6).

The plan names T2.4 (the runner) and T2.5 (the grader) and then assumes the thing between them.
This is that thing, and it owns the three concerns neither of the others can:

* **The reset belongs to the harness, not to the model.** Each use case starts from the
  committed fixture, because a use case that inherits the previous one's tree is a use case
  whose subjects resolve to whatever the last model happened to do.
* **Spend is a hard cap, not a report.** `max_spend_usd` aborts (D24's mid-session decision
  makes this the expensive combination — it comes out of the user's own working window).
* **The backup directory is diffed around the call.** What matters is what appeared *during*
  it; a file an earlier run left behind satisfies "a file exists" for free (D17). Exports are
  **gzip** — measured — so `contains:` reads through the compression rather than against it,
  which would fail on a perfectly correct export.

`HARNESS_BROKEN` aborts the sweep. That is the difference between "the product is wrong" and
"we did not test the product", and it must not be averaged into a K-of-N count.
"""

from __future__ import annotations

import gzip
from collections.abc import Callable, Sequence
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any

from harness.docker_util import ProbeError

from stage2 import grading, runner, subjects
from stage2.catalog import UseCase
from stage2.gates import Attempt, Verdict, escalate
from stage2.gates import recurring as gates_recurring
from stage2.grading import BackupEntry, Outcome
from stage2.state import State

GZIP_MAGIC = b"\x1f\x8b"


class SpendExceeded(ProbeError):
    """The run's own budget is spent. Not a finding — a stop."""


class HarnessAborted(ProbeError):
    """A run proved nothing about the product; grading anything after it would be a guess."""


@dataclass(frozen=True)
class Graded:
    """One attempt with everything it produced, kept for the report."""

    use_case: str
    run: runner.Run
    outcomes: tuple[Outcome, ...] = ()

    @property
    def failures(self) -> tuple[Outcome, ...]:
        return tuple(grading.failures(self.outcomes))


class Sweep:
    """One instance, many use cases. Every seam is injected so this is testable for nothing."""

    def __init__(
        self,
        *,
        driver: runner.Runner,
        reset: Callable[[], None],
        capture: Callable[[], State],
        backup_dir: Path | None = None,
        max_spend_usd: float | None = None,
    ) -> None:
        self.driver = driver
        self.reset = reset
        self.capture = capture
        self.backup_dir = backup_dir
        self.max_spend_usd = max_spend_usd
        self.spent = 0.0
        self.graded: list[Graded] = []
        self.aborted = ""
        self.stopped = ""

    def attempt(self, use_case: UseCase) -> Attempt:
        """One reset, one model run, one grading pass."""
        self._check_budget()
        self.reset()
        listed = self._backup_listing()
        before = self.capture()

        run = self.driver.run(self._addressed(use_case, before))
        self.spent += run.cost_usd

        after = self.capture()
        appeared = self._appeared(listed)

        if run.verdict == runner.HARNESS_BROKEN:
            raise HarnessAborted(f"{use_case.id}: {run.reason}")
        if not run.gradeable:
            self.graded.append(Graded(use_case.id, run))
            return Attempt(run.verdict, (), run.cost_usd)

        evidence = grading.evidence_for(
            use_case,
            before,
            after,
            calls=[call.name for call in (run.transcript.gramps_calls if run.transcript else ())],
            backup=appeared,
        )
        try:
            outcomes = tuple(grading.grade(use_case, evidence))
        except grading.GradingError as error:
            raise HarnessAborted(f"{use_case.id}: {error}") from error
        self.graded.append(Graded(use_case.id, run, outcomes))
        failed = tuple(outcome.id for outcome in grading.failures(outcomes))
        return Attempt(run.verdict, failed, run.cost_usd)

    def verdict(self, use_case: UseCase, **limits: int) -> Verdict:
        """K of N with early stop — one run when it passes, five at the very most."""
        return escalate(use_case.id, lambda _attempt: self.attempt(use_case), **limits)

    def repeat(self, use_case: UseCase, times: int) -> Verdict:
        """`--only ucNN --repeats 5`: the prescribed post-fix proof, without the early stop.

        Escalation asks "is this a finding"; a post-fix proof asks "is it gone", and stopping
        after the first green run would answer that with one sample.
        """
        attempts = [self.attempt(use_case) for _ in range(times)]
        return Verdict(use_case.id, tuple(attempts), gates_recurring(attempts))

    def run(self, cases: Sequence[UseCase], **limits: int) -> list[Verdict]:
        """Every use case in order, K of N each."""
        return self._each(cases, lambda use_case: self.verdict(use_case, **limits))

    def repeat_all(self, cases: Sequence[UseCase], times: int) -> list[Verdict]:
        """`--repeats N` over several use cases, stopping the same way `run` does."""
        return self._each(cases, lambda use_case: self.repeat(use_case, times))

    def _each(self, cases: Sequence[UseCase], one: Callable[[UseCase], Verdict]) -> list[Verdict]:
        """Both kinds of stop keep what they already have.

        `SpendExceeded` always did. `HarnessAborted` did not — it escaped this loop, escaped
        `main()`, and the report was never written: 26 finished use cases and the money they
        cost, discarded because the 27th proved nothing about the product. Aborting the sweep
        is the design (a broken run must not vote); throwing away the evidence never was.

        The same was still true one path over. Subject resolution happens in `_addressed` and
        in `evidence_for`, both outside the grading `try`, and raises a plain `ProbeError` when
        the catalog and the fixture have drifted apart — so every harness fault that is *not*
        a check discarded the run the old way. A fault is named and kept here, whichever of
        the three it is; only `SpendExceeded` is a stop rather than an abort.
        """
        verdicts: list[Verdict] = []
        for use_case in cases:
            try:
                verdicts.append(one(use_case))
            except SpendExceeded as stop:
                self.stopped = str(stop)
                break
            except HarnessAborted as broken:
                self.aborted = str(broken)
                break
            except ProbeError as broken:
                # Prefixed, because these are raised out of the resolver and carry a selector
                # rather than a use case: a report that cannot say which one stopped it sends
                # the reader back through every artifact directory by hand.
                self.aborted = f"{use_case.id}: {broken}"
                break
        return verdicts

    def _addressed(self, use_case: UseCase, before: State) -> UseCase:
        """The use case with its prompt's `{subject}` placeholders filled from *this* tree.

        Resolved against the before-capture for the same reason grading is: the ids belong to
        the tree the run starts on, and a use case may not write one down.
        """
        filled = subjects.fill(
            use_case.prompt, subjects.resolve_all(dict(use_case.subjects), before.tree)
        )
        standing = subjects.unfilled(filled)
        if standing:
            raise HarnessAborted(
                f"{use_case.id}: the prompt still carries {standing} — a model cannot answer a "
                "placeholder, and a run that spends money on one proves nothing"
            )
        return replace(use_case, prompt=filled)

    def _check_budget(self) -> None:
        if self.max_spend_usd is not None and self.spent >= self.max_spend_usd:
            raise SpendExceeded(
                f"${self.spent:.2f} spent of the ${self.max_spend_usd:.2f} allowed — stopping "
                "before another model run rather than reporting the overrun afterwards"
            )

    def _backup_listing(self) -> dict[str, int]:
        if self.backup_dir is None or not self.backup_dir.is_dir():
            return {}
        return {path.name: path.stat().st_size for path in self.backup_dir.iterdir()}

    def _appeared(self, before: dict[str, int]) -> tuple[BackupEntry, ...]:
        now = self._backup_listing()
        return tuple(
            BackupEntry(name=name, size=size, text=self._text(name))
            for name, size in sorted(now.items())
            if name not in before
        )

    def _text(self, name: str) -> str:
        """The file's content, read through gzip when it is one.

        A Gramps export is gzipped (measured), so a `contains:` assertion tested against the raw
        bytes would fail on every correct export — a false red that looks like a broken exporter.
        """
        if self.backup_dir is None:
            return ""
        path = self.backup_dir / name
        raw = path.read_bytes()
        if raw[:2] == GZIP_MAGIC:
            try:
                raw = gzip.decompress(raw)
            except OSError:  # truncated or not actually gzip — report what is there
                pass
        return raw.decode("utf-8", errors="replace")


def by_tier(cases: dict[str, UseCase], tier: int | None) -> list[UseCase]:
    """Tier 1 is the ~4.5-minute smoke tier; no tier at all means every use case."""
    chosen = [case for case in cases.values() if tier is None or case.tier == tier]
    return sorted(chosen, key=lambda case: case.number)


def only(cases: dict[str, UseCase], names: Sequence[str]) -> list[UseCase]:
    """`--only uc7 uc19` — the prescribed cheap post-fix proof, instead of a whole sweep."""
    missing = [name for name in names if name not in cases]
    if missing:
        raise ProbeError(f"no such use case: {missing} — known ids are {sorted(cases)}")
    return sorted((cases[name] for name in names), key=lambda case: case.number)


def total_cost(verdicts: Sequence[Any]) -> float:
    return sum(verdict.cost_usd for verdict in verdicts)
