# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""The `stream-json` run log, read back as evidence (plan T2.4, decision d).

This JSONL *is* the mandated wire log: every `assistant` event carries the `tool_use` blocks
with their full arguments, every `user` event the matching `tool_result`. Nothing else in the
suite may claim what the model did.

Three shapes here were measured on 2026-07-31 rather than assumed, and each of the three is a
place where the obvious guess is wrong:

* a `tool_result`'s `content` is **either** a string **or** a list of blocks — both appeared in
  the same run, so a parser that handles one silently loses the other;
* `ToolSearch` answers with `tool_reference` blocks naming `mcp__gramps__…`. That is the only
  observable proof that a tool was *findable*, which is half of what "docstrings are the
  contract" means and is not the same defect as a tool that was found and misused;
* a truncated log is a **hard error**, never "the model called nothing". A killed process ends
  mid-line, and the difference between "no calls" and "no log" is the difference between a
  product finding and a harness fault.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from harness.docker_util import ProbeError

MCP_PREFIX = "mcp__gramps__"


@dataclass(frozen=True)
class ToolUse:
    """One call the model made, with the arguments it chose."""

    name: str
    arguments: dict[str, Any]
    id: str


@dataclass(frozen=True)
class ToolResult:
    """What came back — flattened to text, because that is all the grader may read from it."""

    tool_use_id: str
    text: str
    is_error: bool


@dataclass(frozen=True)
class Transcript:
    """One `claude -p` run, parsed. Facts only; no judgement about them."""

    events: tuple[dict[str, Any], ...]
    init: dict[str, Any]
    result: dict[str, Any]
    tool_uses: tuple[ToolUse, ...]
    tool_results: tuple[ToolResult, ...]
    references: frozenset[str]

    @property
    def gramps_calls(self) -> tuple[ToolUse, ...]:
        """The calls into the server under test, named as `server.py` registers them."""
        return tuple(
            ToolUse(use.name[len(MCP_PREFIX) :], use.arguments, use.id)
            for use in self.tool_uses
            if use.name.startswith(MCP_PREFIX)
        )

    @property
    def text(self) -> str:
        return str(self.result.get("result", ""))

    @property
    def num_turns(self) -> int:
        return int(self.result.get("num_turns", 0))

    @property
    def cost_usd(self) -> float:
        return float(self.result.get("total_cost_usd", 0.0))

    @property
    def subtype(self) -> str:
        return str(self.result.get("subtype", ""))

    @property
    def is_error(self) -> bool:
        return bool(self.result.get("is_error", False))

    @property
    def permission_denials(self) -> list[Any]:
        return list(self.result.get("permission_denials", []))


def read_events(path: Path) -> list[dict[str, Any]]:
    """Every event, or a `ProbeError` naming the line that could not be read."""
    raw = path.read_text(encoding="utf-8")
    if not raw.strip():
        raise ProbeError(f"{path} is empty — the run produced no wire log at all")

    events: list[dict[str, Any]] = []
    for number, line in enumerate(raw.splitlines(), start=1):
        if not line.strip():
            continue
        try:
            events.append(json.loads(line))
        except json.JSONDecodeError as error:
            raise ProbeError(
                f"{path} line {number} is not valid JSON ({error.msg}) — a truncated log is a "
                "killed run, not a run in which the model called nothing"
            ) from error
    return events


def from_events(events: list[dict[str, Any]]) -> Transcript:
    """Assemble the parsed run. Missing bookends are refused, not defaulted."""
    init = _one(events, "system", subtype="init")
    if init is None:
        raise ProbeError("the run has no system/init event — its isolation cannot be checked")
    result = _one(events, "result")
    if result is None:
        raise ProbeError(
            "the run has no result event — it was killed before it finished, so its cost, its "
            "turn count and its final text are all unknown"
        )

    uses: list[ToolUse] = []
    results: list[ToolResult] = []
    references: set[str] = set()
    for event in events:
        for block in _blocks(event):
            if block.get("type") == "tool_use":
                uses.append(
                    ToolUse(
                        name=str(block.get("name", "")),
                        arguments=dict(block.get("input", {})),
                        id=str(block.get("id", "")),
                    )
                )
            elif block.get("type") == "tool_result":
                results.append(_tool_result(block))
                references |= _references(block)

    return Transcript(
        events=tuple(events),
        init=init,
        result=result,
        tool_uses=tuple(uses),
        tool_results=tuple(results),
        references=frozenset(references),
    )


def load(path: Path) -> Transcript:
    return from_events(read_events(path))


def _one(events: list[dict[str, Any]], kind: str, subtype: str = "") -> dict[str, Any] | None:
    for event in events:
        if event.get("type") == kind and (not subtype or event.get("subtype") == subtype):
            return event
    return None


def _blocks(event: dict[str, Any]) -> list[dict[str, Any]]:
    content = event.get("message", {}).get("content", [])
    return [block for block in content if isinstance(block, dict)]


def _tool_result(block: dict[str, Any]) -> ToolResult:
    content = block.get("content", "")
    if isinstance(content, list):
        text = "".join(str(part.get("text", "")) for part in content if isinstance(part, dict))
    else:
        text = str(content)
    return ToolResult(
        tool_use_id=str(block.get("tool_use_id", "")),
        text=text,
        is_error=bool(block.get("is_error", False)),
    )


def _references(block: dict[str, Any]) -> set[str]:
    """The tool names `ToolSearch` handed back for the model's own query."""
    content = block.get("content", "")
    if not isinstance(content, list):
        return set()
    return {
        str(part["tool_name"])
        for part in content
        if isinstance(part, dict) and part.get("type") == "tool_reference" and "tool_name" in part
    }
