# Generated by OrchestKit Claude Plugin
# Created: 2026-07-30

"""A minimal, deliberately rude MCP server over stdio — test fixture, not harness code.

It exists so the JSON-RPC framing can be tested against a *real* pipe and real reader
threads without Docker. Rude on purpose: every reply is preceded by a line of noise and by
a reply carrying a foreign id, because that is what the framing has to survive. The shipped
server logs to stderr and the `mcp` library is free to emit notifications at any time, so a
driver that assumes "the next line is my answer" would pass its tests and fail in the suite.
"""

from __future__ import annotations

import json
import sys
from typing import Any

SERVER_INFO = {"name": "stub", "version": "0"}
TOOLS = [{"name": "echo"}, {"name": "boom"}, {"name": "rpcfail"}, {"name": "silent"}]


def emit(payload: dict[str, Any]) -> None:
    sys.stdout.write(json.dumps(payload) + "\n")
    sys.stdout.flush()


def noise(msg_id: int) -> None:
    """A log line and somebody else's reply, ahead of the real one."""
    sys.stdout.write("this line is not JSON at all\n")
    emit({"jsonrpc": "2.0", "id": msg_id + 10_000, "result": {"not": "yours"}})


def result(msg_id: int, payload: dict[str, Any]) -> None:
    emit({"jsonrpc": "2.0", "id": msg_id, "result": payload})


def handle(msg: dict[str, Any]) -> None:
    method, msg_id = msg.get("method"), msg.get("id")
    if msg_id is None:  # a notification — notifications/initialized, never answered
        return
    noise(msg_id)

    if method == "initialize":
        result(msg_id, {"protocolVersion": "2025-06-18", "serverInfo": SERVER_INFO})
        return
    if method == "tools/list":
        cursor = (msg.get("params") or {}).get("cursor")
        page: dict[str, Any] = {"tools": TOOLS if not cursor else []}
        if not cursor:
            page["nextCursor"] = "page-2"
        result(msg_id, page)
        return
    if method != "tools/call":
        result(msg_id, {})
        return

    params = msg.get("params") or {}
    name, arguments = params.get("name"), params.get("arguments", {})
    if name == "silent":
        sys.stderr.write("stub: refusing to answer 'silent'\n")
        sys.stderr.flush()
        return
    if name == "rpcfail":
        emit({"jsonrpc": "2.0", "id": msg_id, "error": {"code": -32602, "message": "no such tool"}})
        return
    if name == "boom":
        result(msg_id, {"content": [{"type": "text", "text": "it blew up"}], "isError": True})
        return
    result(
        msg_id,
        {
            "content": [
                {"type": "text", "text": json.dumps(arguments, sort_keys=True)},
                {"type": "image", "data": "ignored-by-.text"},
            ],
            "structuredContent": {"result": arguments},
        },
    )


def main() -> None:
    for line in sys.stdin:
        try:
            msg = json.loads(line)
        except ValueError:
            continue
        handle(msg)


if __name__ == "__main__":
    main()
