# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""Tools that write but report nothing usable about it (checkpoint B5, B6).

`unguarded` is not one tool's quirk. Five shipped tools take no count snapshot and hand back
no before/after: `add_child_to_family`, `remove_child_from_family`, `set_family_parent`
(`gramps_client.py:979-1048`), `update_blog_post` (`{gramps_id, updated}`, `gramps_blog.py:191`)
and `export_tree` (`{path, bytes, counts}`, `server.py:286`). For the first four the evidence is
in the tree and has to be named; for `export_tree` it is a file, and no re-read of the tree can
stand in for it.

Two of the switches model mutations rather than shipped behaviour, which is the point of a
double: `skip_family_put` is the family analogue of `skip_put`, and `write_then_refuse` moves a
validation *after* its write — shipped code validates first everywhere (`gramps_client.py:701`
before `:702`, `:985` before `:997`), so the only way to see whether a refusal would be caught
having already changed something is to build one.
"""

from __future__ import annotations

from typing import Any

from harness.mcp_session import ToolResult

from .fake_tree import FakeMcp

BLOG_POST = "S0000"
BODY_NOTE = "N0000"


class FakeWriteMcp(FakeMcp):
    """`FakeMcp` plus the shapes whose whole report is `{some id, "it worked"}`."""

    def __init__(self, tree: Any) -> None:
        super().__init__(tree)
        # Reports the child as added and never writes the family — `self._put_family(...)`
        # removed (`gramps_client.py:997`). Nothing in the report can betray it.
        self.skip_family_put = False
        # A refusal that already changed something: the title PUT landed, then the call
        # raised. `gramps_blog.py:173` is where that write really sits.
        self.write_then_refuse = False

    def _t_gramps_add_child_to_family(self, family_id: str, child_id: str) -> ToolResult:
        if self.skip_family_put:
            return self._dict_result({"family_id": family_id, "child_id": child_id})
        return super()._t_gramps_add_child_to_family(family_id, child_id)

    def _t_gramps_update_blog_post(
        self, gramps_id: str, title: str | None = None, body: str | None = None
    ) -> ToolResult:
        """A body update on a post that has no note yet *creates* one (+1 notes).

        That is the call form the old gate made inexpressible: `unguarded` refused to accept a
        delta, and no other report shape fits `{gramps_id, updated}`.
        """
        source = self.tree.namespaces["sources"][gramps_id]
        updated = []
        if title is not None:
            source["title"] = title
            updated.append("title")
        if body is not None:
            self.tree.namespaces["notes"][BODY_NOTE] = {
                "handle": f"h-{BODY_NOTE}",
                "gramps_id": BODY_NOTE,
                "text": {"string": body},
            }
            source["note_list"] = [f"h-{BODY_NOTE}"]
            updated.append("body")
        return self._dict_result({"gramps_id": gramps_id, "updated": updated})

    def _t_gramps_delete_blog_post(
        self, gramps_id: str, confirm: bool = False, title: str | None = None
    ) -> ToolResult:
        """The refusal that is not clean: with `write_then_refuse` the title write happens
        first, and then the confirmation check rejects the call."""
        if self.write_then_refuse and title is not None:
            self.tree.namespaces["sources"][gramps_id]["title"] = title
        if not confirm:
            raise ValueError("delete_blog_post requires confirm=True (destructive)")
        sources = self.tree.namespaces["sources"]
        count_before = len(sources)
        sources.pop(gramps_id)
        return self._dict_result(
            {
                "gramps_id": gramps_id,
                "deleted": True,
                "count_before": count_before,
                "count_after": len(sources),
            }
        )

    def _t_gramps_export_tree(self, filename: str = "") -> ToolResult:
        """Writes a file and touches no object. The tree is the wrong place to look for it,
        which is why this shape is declared rather than silently unchecked."""
        counts = self.tree.counts()
        return self._dict_result({"path": f"/backup/{filename}", "bytes": 1159, "counts": counts})
