# Generated by OrchestKit Claude Plugin
# Created: 2026-07-30

"""An in-memory tree and a fake MCP server — test fixture for the assertions, not harness code.

`assertions.py` exists to catch a *lying* server, so its own tests need a server that can be
told to lie. Every switch on `FakeMcp` is one measured failure mode:

* `skip_put` — reports a successful write and does not perform it. This is D16's whole reason
  for existing: `_guarded_write` snapshots the **local dict** after the mutation
  (`gramps_client.py:699-704`), so the shipped report says "before != after" whether or not
  the PUT went out. Deleting `self._put_person(...)` turns seven tools into silent no-ops.
* `lie_before` / `wrong_id` / `phantom_id` — the report contradicts the tree in the three other
  ways a self-report can: wrong prior state, wrong subject, an id that never landed.

The wire shapes are the measured ones (`probes/observed.json::u3_structured_content`), not the
ones the plan assumed: a bare-`str` tool carries `structuredContent={"result": …}`, a `dict`
tool carries **none** and puts JSON in the text part, and a `list` tool emits one text part per
element. An assertion helper that only ever saw one of those shapes would be fiction.
"""

from __future__ import annotations

import copy
import json
import re
from typing import Any

from harness.mcp_session import ToolResult
from harness.rest import GrampsRest

UNCONFIRMED_TAG = "Unbestätigt"


def person_record(gramps_id: str, first_name: str, surname: str, gender: int = 1) -> dict[str, Any]:
    return {
        "handle": f"h-{gramps_id}",
        "gramps_id": gramps_id,
        "gender": gender,
        "primary_name": {"first_name": first_name, "surname_list": [{"surname": surname}]},
        "alternate_names": [],
        "tag_list": [],
    }


class FakeTree:
    """Namespaces of `gramps_id -> record`, which is all the oracle ever reads."""

    def __init__(self) -> None:
        self.namespaces: dict[str, dict[str, dict[str, Any]]] = {
            "people": {
                p["gramps_id"]: p
                for p in (
                    person_record("I0000", "Alwine", "Brehmer", gender=0),
                    person_record("I0001", "Cordt", "Brehmer", gender=1),
                    person_record("I0002", "Edda", "Brehmer", gender=0),
                )
            },
            "families": {
                "F0000": {"handle": "h-F0000", "gramps_id": "F0000", "child_ref_list": []}
            },
            "notes": {},
            "tags": {},
        }

    def counts(self) -> dict[str, int]:
        return {name: len(records) for name, records in self.namespaces.items()}

    def person(self, gramps_id: str) -> dict[str, Any]:
        return self.namespaces["people"][gramps_id]

    def add_person(self, gramps_id: str, first_name: str, surname: str) -> None:
        self.namespaces["people"][gramps_id] = person_record(gramps_id, first_name, surname)

    def next_person_id(self) -> str:
        used = [int(gid[1:]) for gid in self.namespaces["people"]]
        return f"I{max(used) + 1:04d}"


class FakeRest(GrampsRest):
    """The real oracle over a fake transport.

    Subclassing rather than reimplementing is the point: `snapshot`, `fingerprint` and
    `by_gramps_id` are the code the suite trusts, so the assertion tests have to exercise
    *them*, not a second implementation that agrees with the assertions by construction.
    """

    def __init__(self, tree: FakeTree) -> None:
        super().__init__("http://fake.invalid", "oracle", "secret")
        self.tree = tree
        self.reads = 0

    def token(self, *, force: bool = False) -> str:  # pragma: no cover - never authenticates
        raise AssertionError("the fake oracle must not touch the network")

    def get_json(self, path: str) -> Any:
        self.reads += 1
        if path == "/api/metadata/":
            return {"object_counts": self.tree.counts()}
        namespace, _, tail = path.removeprefix("/api/").partition("/")
        records = self.tree.namespaces[namespace]
        if not tail:
            return copy.deepcopy(list(records.values()))
        for record in records.values():
            if record["handle"] == tail:
                return copy.deepcopy(record)
        raise LookupError(f"no {namespace} record with handle {tail!r}")


class FakeMcp:
    """A fake `McpContainer.call` that can be told to misreport."""

    def __init__(self, tree: FakeTree) -> None:
        self.tree = tree
        self.skip_put = False
        self.lie_before = False
        self.lie_after = False
        self.wrong_id = False
        self.phantom_id = False
        # A tool that refuses *after* it already changed something — the one refusal outcome
        # an `is_error` + text assertion on its own reports as a clean rejection.
        self.leaky_refusal = False
        # A counts-reporting tool whose `before` is really its `after`: the operation looks
        # like it added nothing, which is how a no-op import reads as a successful one.
        self.lie_counts = False
        # A delete that reports the count it started with. The record really is gone, so the
        # namespace delta is right and only the tool's own arithmetic is wrong.
        self.lie_delete_counts = False
        # The bulk guard is reported rather than raised (`gramps_client.py:737-743`), so a
        # batch can hand back `count_guard_ok: False` and still look like a successful call.
        self.break_bulk_guard = False
        # A batch that writes its first item and silently drops the rest — without raising, so
        # `errors` stays empty and `count_guard_ok` stays true. A field write moves no counts,
        # so nothing outside `expect_person` can see the missing four fifths of the work.
        self.drop_bulk_tail = False
        self.calls: list[tuple[str, dict[str, Any]]] = []

    # -- wire shapes (measured) --------------------------------------------------

    @staticmethod
    def _dict_result(payload: dict[str, Any]) -> ToolResult:
        content = [{"type": "text", "text": json.dumps(payload)}]
        return ToolResult(is_error=False, content=content, structured=None, raw={})

    @staticmethod
    def _str_result(value: str) -> ToolResult:
        content = [{"type": "text", "text": value}]
        return ToolResult(is_error=False, content=content, structured={"result": value}, raw={})

    @staticmethod
    def _list_result(values: list[Any]) -> ToolResult:
        content = [{"type": "text", "text": json.dumps(value)} for value in values]
        return ToolResult(is_error=False, content=content, structured=None, raw={})

    @staticmethod
    def _error(tool: str, message: str) -> ToolResult:
        """The shipped envelope, measured: `Error executing tool <name>: <str(exc)>`."""
        content = [{"type": "text", "text": f"Error executing tool {tool}: {message}"}]
        return ToolResult(is_error=True, content=content, structured=None, raw={})

    # -- the tools ---------------------------------------------------------------

    def call(self, tool: str, arguments: dict[str, Any] | None = None, **_: Any) -> ToolResult:
        self.calls.append((tool, dict(arguments or {})))
        handler = getattr(self, f"_t_{tool}", None)
        if handler is None:
            return self._error(tool, f"Unknown tool: {tool}")
        try:
            return handler(**(arguments or {}))
        except ValueError as exc:
            return self._error(tool, str(exc))

    def _snapshot(self, person: dict[str, Any]) -> dict[str, Any]:
        """The product's own projection (`gramps_client.py:683-691`)."""
        return copy.deepcopy(
            {
                key: person.get(key)
                for key in ("gender", "primary_name", "alternate_names", "tag_list")
            }
        )

    def _write_person(self, gramps_id: str, mutate: Any) -> dict[str, Any]:
        stored = self.tree.person(gramps_id)
        working = copy.deepcopy(stored)
        before = self._snapshot(working)
        mutate(working)
        if not self.skip_put:
            self.tree.namespaces["people"][gramps_id] = working
        after = self._snapshot(working)
        if self.lie_before:
            before = after
        if self.lie_after:
            # Wrote correctly, tells a different story. The tree agrees with the test, so the
            # re-read is happy and only the report is wrong — a Stage-2 use case that chains
            # off the reported value would then carry the wrong one forward.
            after = before
        reported_id = "I9999" if self.wrong_id else gramps_id
        return {"gramps_id": reported_id, "before": before, "after": after}

    def _t_gramps_set_first_name(self, gramps_id: str, first_name: str) -> ToolResult:
        def mutate(person: dict[str, Any]) -> None:
            person["primary_name"]["first_name"] = first_name

        return self._dict_result(self._write_person(gramps_id, mutate))

    def _t_gramps_set_gender_bulk(self, items: list[dict[str, Any]]) -> ToolResult:
        count_before = len(self.tree.namespaces["people"])
        handled = items[:1] if self.drop_bulk_tail else items
        results = []
        for item in handled:

            def mutate(person: dict[str, Any], gender: int = item["gender"]) -> None:
                person["gender"] = gender

            results.append(self._write_person(item["gramps_id"], mutate))
        count_after = len(self.tree.namespaces["people"])
        return self._dict_result(
            {
                "count_before": count_before,
                "count_after": count_after,
                "count_guard_ok": count_after == count_before and not self.break_bulk_guard,
                "results": results,
                "errors": [],
            }
        )

    def _t_gramps_add_person(self, first_name: str = "", surname: str = "") -> ToolResult:
        """`phantom_id` creates the person but hands back a different id — the counts move
        exactly as expected, so only looking the id up catches it."""
        gramps_id = self.tree.next_person_id()
        self.tree.add_person(gramps_id, first_name, surname)
        return self._str_result("I9999" if self.phantom_id else gramps_id)

    def _t_gramps_delete_person(self, gramps_id: str, confirm: bool = False) -> ToolResult:
        if not confirm:
            raise ValueError("delete_person requires confirm=True (destructive)")
        people = self.tree.namespaces["people"]
        count_before = len(people)
        people.pop(gramps_id)
        return self._dict_result(
            {
                "gramps_id": gramps_id,
                "deleted": True,
                "count_before": count_before,
                "count_after": count_before if self.lie_delete_counts else len(people),
            }
        )

    def _t_gramps_replace_person(self, gramps_id: str) -> ToolResult:
        """Delete one person and create another: every count is exactly where it started, and
        only the *identity* of what exists has moved."""
        # The id is taken before the removal on purpose: computing it afterwards hands back
        # the id that was just freed, and re-creating the same id is not an identity change.
        replacement = self.tree.next_person_id()
        self.tree.namespaces["people"].pop(gramps_id)
        self.tree.add_person(replacement, "Ersatz", "Brehmer")
        return self._dict_result({"replaced": gramps_id, "with": replacement})

    def _t_gramps_add_child_to_family(self, family_id: str, child_id: str) -> ToolResult:
        family = self.tree.namespaces["families"][family_id]
        if any(ref["ref"] == f"h-{child_id}" for ref in family["child_ref_list"]):
            raise ValueError((family_id, child_id))
        family["child_ref_list"].append({"ref": f"h-{child_id}"})
        return self._dict_result({"family_id": family_id, "child_id": child_id})

    def _t_gramps_list_people(self) -> ToolResult:
        return self._list_result(list(self.tree.namespaces["people"].values()))

    def _t_gramps_import_file(self, filename: str) -> ToolResult:
        before = self.tree.counts()
        escapes = not re.fullmatch(r"[\w.\-]+", filename)
        if escapes and not self.leaky_refusal:
            raise ValueError(f"Path escapes backup directory: {filename!r}")
        self.tree.add_person(self.tree.next_person_id(), "Imported", "Brehmer")
        if escapes:
            raise ValueError(f"Path escapes backup directory: {filename!r}")
        after = self.tree.counts()
        return self._dict_result({"before": after if self.lie_counts else before, "after": after})
