# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""The sweep driver and the report it leaves (T2.6, T2.8). No Docker, no model, no money.

Every seam the driver has — the runner, the reset, the capture, the backup directory — is
injected, so the loop that would otherwise cost $5.85 and 24 minutes of the user's window is
exercised in milliseconds. What is tested is what the loop *decides*: when to stop, when to
abort, what counts as evidence, and what the report is allowed to claim.
"""

from __future__ import annotations

import gzip
import json
from pathlib import Path
from typing import Any

import pytest
from fixtures import stage2_records as make
from stage2 import gates, report, runner, sweep, transcript
from stage2.catalog import Assertion, UseCase

FIXTURE = Path(__file__).parent / "fixtures" / "stage2" / "clean-run.jsonl"
TREE = make.state(people=(make.person("I0000", "Rosalind", "Steinbrecht"),))


def use_case(*assertions: Assertion, tier: int = 1, identifier: str = "uc1") -> UseCase:
    return UseCase(
        id=identifier,
        slug=f"{identifier}-probe",
        tier=tier,
        prompt="p",
        primary=("gramps_add_person",),
        decoys=(),
        secondary=(),
        subjects={},
        guards={"people": [], "families": [], "sources": []},
        maxdrop=0,
        assertions=assertions or (Assertion("uc1/counts", "counts", {"deltas": {}}),),
        waivers=(),
        path=Path("uc1.yaml"),
    )


class FakeRunner:
    """Hands out canned runs, records that it was asked, and can act while it "runs"."""

    def __init__(self, *verdicts: str, during: Any = None) -> None:
        self.verdicts = list(verdicts) or [runner.OK]
        self.during = during
        self.calls = 0

    def run(self, case: UseCase) -> runner.Run:
        verdict = self.verdicts[min(self.calls, len(self.verdicts) - 1)]
        self.calls += 1
        if self.during:
            self.during()
        parsed = transcript.load(FIXTURE) if verdict != runner.INCONCLUSIVE else None
        return runner.Run(case.id, verdict, None, Path("/tmp/run"), (), parsed)


def build(driver: Any, **kwargs: Any) -> sweep.Sweep:
    calls: list[str] = []
    driven = sweep.Sweep(
        driver=driver,
        reset=lambda: calls.append("reset"),
        capture=lambda: TREE,
        **kwargs,
    )
    driven.resets = calls  # type: ignore[attr-defined]
    return driven


def test_a_passing_use_case_is_reset_once_and_run_once() -> None:
    driven = build(FakeRunner(runner.OK))

    verdict = driven.verdict(use_case())

    assert len(verdict.attempts) == 1 and verdict.passes == 1
    assert driven.resets == ["reset"], "every attempt starts from the committed fixture"


def test_a_failing_assertion_escalates_and_the_tree_is_reset_each_time() -> None:
    """The reset is the harness's job: a use case inheriting the last model's tree resolves its
    subjects against whatever that model happened to do."""
    failing = use_case(Assertion("uc1/counts", "counts", {"deltas": {"people": 1}}))

    verdict = build(FakeRunner(runner.OK)).verdict(failing)

    assert verdict.reportable
    assert verdict.recurring == ("uc1/counts",)
    assert len(verdict.attempts) == gates.K_FAILURES


def test_a_broken_harness_aborts_the_sweep_instead_of_being_averaged_in() -> None:
    driven = build(FakeRunner(runner.HARNESS_BROKEN))

    with pytest.raises(sweep.HarnessAborted, match="uc1"):
        driven.verdict(use_case())


def test_an_inconclusive_run_is_recorded_but_not_graded() -> None:
    driven = build(FakeRunner(runner.INCONCLUSIVE, runner.INCONCLUSIVE, runner.OK))

    verdict = driven.verdict(use_case())

    assert verdict.inconclusive == 2 and verdict.passes == 1
    assert driven.graded[0].outcomes == (), "there was nothing to grade"


def test_the_spend_cap_stops_before_the_next_run_not_after_the_overrun() -> None:
    driven = build(FakeRunner(runner.OK), max_spend_usd=0.05)

    with pytest.raises(sweep.SpendExceeded, match="0.05"):
        for _ in range(3):
            driven.attempt(use_case())

    assert driven.driver.calls == 1, "the cap stopped a run rather than reporting it"


def test_a_spent_budget_ends_the_sweep_and_keeps_what_it_has() -> None:
    driven = build(FakeRunner(runner.OK), max_spend_usd=0.05)

    verdicts = driven.run([use_case(identifier="uc1"), use_case(identifier="uc2")])

    assert [verdict.use_case for verdict in verdicts] == ["uc1"]


def test_only_the_files_that_appeared_during_the_call_are_evidence(tmp_path: Path) -> None:
    """A leftover export from an earlier run satisfies "a file exists" for free (D17). The
    baseline is taken *after* the reset, so a file the reset itself drops there is not evidence
    either."""
    (tmp_path / "old.gramps").write_bytes(b"x" * 2000)
    exporting = FakeRunner(
        runner.OK, during=lambda: (tmp_path / "new.gramps").write_bytes(b"x" * 2000)
    )
    driven = build(exporting, backup_dir=tmp_path)

    driven.attempt(use_case(Assertion("uc1/file", "backup_file", {"count": 1})))

    assert driven.graded[0].failures == ()


def test_a_gzipped_export_is_read_through_its_compression(tmp_path: Path) -> None:
    """Measured: a Gramps export is gzip. `contains:` against the raw bytes would fail on every
    correct export — a false red that reads as a broken exporter."""
    exporting = FakeRunner(
        runner.OK,
        during=lambda: (tmp_path / "tree.gramps").write_bytes(
            gzip.compress(b"<person>Aschenblum</person>")
        ),
    )
    driven = build(exporting, backup_dir=tmp_path)

    driven.attempt(
        use_case(Assertion("uc1/file", "backup_file", {"count": 1, "contains": "Aschenblum"}))
    )

    assert driven.graded[0].failures == ()


def test_a_post_fix_proof_runs_every_repeat_without_the_early_stop() -> None:
    """Escalation asks "is this a finding"; `--repeats` asks "is it gone" — and one green run
    is not an answer to the second question."""
    driven = build(FakeRunner(runner.OK))

    verdict = driven.repeat(use_case(), 5)

    assert len(verdict.attempts) == 5 and verdict.passes == 5
    assert driven.resets == ["reset"] * 5


def test_the_tier_filter_is_what_makes_the_cheap_run_cheap() -> None:
    cases = {"uc1": use_case(identifier="uc1", tier=1), "uc2": use_case(identifier="uc2", tier=3)}

    assert [case.id for case in sweep.by_tier(cases, 1)] == ["uc1"]
    assert [case.id for case in sweep.by_tier(cases, None)] == ["uc1", "uc2"]


def test_naming_a_use_case_that_does_not_exist_is_refused() -> None:
    with pytest.raises(Exception, match="uc99"):
        sweep.only({"uc1": use_case()}, ["uc99"])


def test_the_report_says_what_it_is_not_claiming() -> None:
    """Three sentences that are cheap to omit and expensive to omit."""
    text = report.summary([], [], spent=1.25, budget=6.0)

    assert "$1.2500 of $6.00 allowed" in text
    assert "Tier 3 is advisory" in text
    assert "Coverage is not gating" in text
    assert "Nothing here was filed" in text


def test_a_finding_becomes_a_draft_that_carries_its_dedup_key() -> None:
    driven = build(FakeRunner(runner.OK))
    failing = use_case(Assertion("uc1/counts", "counts", {"deltas": {"people": 1}}))
    verdict = driven.verdict(failing)

    (title, body), *rest = report.drafts([verdict], driven.graded)

    assert rest == []
    assert "uc1/counts" in title and "3/3" in title
    assert gates.dedup_key("uc1", "uc1/counts") in body
    assert "class-A assertion" in body


def test_a_watch_line_is_reported_and_never_drafted() -> None:
    """The same assertion twice, named as recurring — everything a draft needs except the third
    run. `reportable` is the only thing standing between it and a public issue, so this hands
    the drafter a verdict that would otherwise sail through."""
    verdict = gates.Verdict(
        "uc1",
        (
            gates.Attempt("OK", ("uc1/counts",)),
            gates.Attempt("OK", ("uc1/counts",)),
            gates.Attempt("OK", ()),
        ),
        ("uc1/counts",),
    )

    text = report.summary([verdict], [], spent=0.0)

    assert verdict.watch and not verdict.reportable
    assert "watch" in text
    assert report.drafts([verdict], []) == []


def test_the_summary_table_carries_every_use_case_and_its_cost() -> None:
    driven = build(FakeRunner(runner.OK))
    verdicts = driven.run([use_case(identifier="uc1"), use_case(identifier="uc2")])

    text = report.summary(verdicts, driven.graded, spent=driven.spent)

    assert "| uc1 |" in text and "| uc2 |" in text
    assert "$0.0792" in text


def test_the_recorded_run_is_the_one_that_paid_for_these_numbers() -> None:
    """The fixture is a real run; its cost is what a single Stage-2 call actually cost."""
    events = transcript.read_events(FIXTURE)

    assert json.loads(json.dumps(events[-1]))["total_cost_usd"] == pytest.approx(0.0791895)
