# Generated by OrchestKit Claude Plugin
# Created: 2026-08-01

"""Which failure breaks a chain, and what the skip says (plan D5, T4.0). No Docker.

The rule these two functions encode decides how a 44-case matrix reads when one thing is wrong:
one red naming the defect, or eight reds of which seven are consequences. That is worth a test
of its own, and `conftest.py` cannot have one — a conftest is not importable — which is why the
logic is in `harness/chain.py` and the hooks there are three lines that call it.

The wiring itself (that pytest actually reaches these with a class collector's stash) is proven
live by `test_10_seeded_tree.py` for the intact path, and by the mutation probe recorded in
`.claude/worknotes/e2e-suite/mutation-probes/probe_chain_skip.py` for the broken one.
"""

from __future__ import annotations

import pytest
from harness.chain import BROKEN, note_outcome, skip_reason


@pytest.fixture
def stash() -> pytest.Stash:
    return pytest.Stash()


def test_an_intact_chain_has_no_reason_to_skip(stash: pytest.Stash) -> None:
    note_outcome(stash, name="test_first", when="call", failed=False)

    assert skip_reason(stash) is None


def test_a_failure_names_itself_in_the_skip(stash: pytest.Stash) -> None:
    note_outcome(stash, name="test_second", when="call", failed=True)

    assert skip_reason(stash) == "earlier step in this chain failed: test_second"


def test_the_first_failure_is_the_one_named(stash: pytest.Stash) -> None:
    """The later ones are consequences, and naming a consequence sends the reader to a test
    that is fine."""
    note_outcome(stash, name="test_second", when="call", failed=True)
    note_outcome(stash, name="test_third", when="call", failed=True)

    assert skip_reason(stash) == "earlier step in this chain failed: test_second"


@pytest.mark.parametrize("when", ["setup", "teardown"])
def test_a_failure_outside_the_call_breaks_the_chain_too(stash: pytest.Stash, when: str) -> None:
    """Setup means the substrate was never built; teardown means it was left in a state nobody
    described. Either way the next step reads something other than what it was promised."""
    note_outcome(stash, name="test_second", when=when, failed=True)

    assert skip_reason(stash) == f"earlier step in this chain failed: test_second ({when})"


def test_the_phase_is_only_named_when_it_is_not_the_call(stash: pytest.Stash) -> None:
    """`test_second (call)` would be noise on every single skip line."""
    note_outcome(stash, name="test_second", when="call", failed=True)

    assert stash[BROKEN] == "test_second"


def test_a_pass_after_a_failure_does_not_heal_the_chain(stash: pytest.Stash) -> None:
    """A later step passing proves nothing about the state the failed one was supposed to leave
    — and in a chain that skips, a step after the break should not have run at all."""
    note_outcome(stash, name="test_second", when="call", failed=True)
    note_outcome(stash, name="test_third", when="call", failed=False)

    assert skip_reason(stash) == "earlier step in this chain failed: test_second"


def test_two_chains_do_not_see_each_other() -> None:
    """The stash is the *class* collector's, not the module's: two classes in one matrix file
    are two chains, and one breaking must not silently empty the other."""
    first, second = pytest.Stash(), pytest.Stash()

    note_outcome(first, name="test_second", when="call", failed=True)

    assert skip_reason(first) is not None
    assert skip_reason(second) is None
