# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""The use-case catalog says what it means, and agrees with the coverage map (T2.2). No Docker.

Stage 2 is the expensive stage: real inference, real money, ~24 minutes of the same window the
user is working in. Everything about a use case that can be decided without spending any of
that is decided here — whether its tools exist, whether the people it talks about are in the
fixture exactly once, whether its assertions name kinds a grader implements, and whether its
prompt gives the answer away.

The pairing with `coverage.py` is the load-bearing part. That file says which use case each of
the 31 tools is tested by; this one says which tools each use case tests. Two files that
disagree would each look complete on its own — which is precisely how a tool ends up with a
slot pointing at a use case that does not exist, or a use case that tests nothing.
"""

from __future__ import annotations

from unittest.mock import MagicMock

import pytest
from fixtures import cast
from stage2 import subjects, validate
from stage2.assertion_kinds import KINDS
from stage2.catalog import UseCase, load_all
from stage2.coverage import COVERAGE

import server

# From the design's tiering (§6): tier 1 is chosen by predicted risk and runs on every
# invocation, tier 2 is the rest of the write coverage, tier 3 is the read canaries that never
# gate. Pinned because the cost and wall-clock claims in the report header are per tier.
EXPECTED_TIERS = {1: 8, 2: 14, 3: 5}


@pytest.fixture(scope="module")
def catalog() -> dict[str, UseCase]:
    return load_all()


@pytest.fixture(scope="module")
def registered() -> set[str]:
    """Every tool Stage 2 sees — the destructive flag is on for the whole run (design §7)."""
    return set(server.create_server(MagicMock(), enable_destructive=True)[1])


def test_the_catalog_holds_no_use_case_that_measures_nothing(
    catalog: dict[str, UseCase], registered: set[str]
) -> None:
    """The whole validator in one assertion, reported as a list rather than as the first
    failure: a catalog fixed one red run at a time is a catalog written half-blind."""
    found = validate.problems(catalog, registered, subjects.from_cast(cast))

    assert found == []


def test_every_tool_slot_points_at_a_use_case_that_exists(catalog: dict[str, UseCase]) -> None:
    """`coverage.py` claims all 31 tools are covered. A slot naming a use case nobody wrote
    would keep that claim true on paper while testing nothing at all."""
    missing = sorted({slot.primary for slot in COVERAGE.values()} - set(catalog))

    assert missing == [], f"{missing} are named as a tool's primary but have no use-case file"


def test_every_use_case_is_some_tool_s_primary(catalog: dict[str, UseCase]) -> None:
    """The other direction: a use case nobody's slot points at costs a run and covers nothing."""
    claimed = {slot.primary for slot in COVERAGE.values()}
    orphans = sorted(set(catalog) - claimed)

    assert orphans == [], f"{orphans} are in the catalog but no tool names them as its primary"


def test_the_two_files_agree_on_which_tools_each_use_case_tests(
    catalog: dict[str, UseCase],
) -> None:
    """`primary` in the use case must be exactly the tools whose slot names that use case."""
    for identifier, use_case in catalog.items():
        expected = {tool for tool, slot in COVERAGE.items() if slot.primary == identifier}

        assert set(use_case.primary) == expected, (
            f"{identifier} calls {sorted(use_case.primary)} its primary, the coverage map says "
            f"{sorted(expected)}"
        )


def test_the_two_files_agree_on_the_decoys(catalog: dict[str, UseCase]) -> None:
    """A decoy is a tool the use case asserts was *not* the effective route. If only one file
    knows about it, the assertion that would catch it may never have been written."""
    for identifier, use_case in catalog.items():
        expected = {tool for tool, slot in COVERAGE.items() if identifier in slot.decoy_in}

        assert set(use_case.decoys) == expected, f"{identifier} disagrees about its decoys"


def test_the_two_files_agree_on_the_incidental_lookups(catalog: dict[str, UseCase]) -> None:
    for identifier, use_case in catalog.items():
        expected = {tool for tool, slot in COVERAGE.items() if identifier in slot.secondary_in}

        assert set(use_case.secondary) == expected, f"{identifier} disagrees about its secondary"


def test_every_assertion_kind_is_used_by_somebody(catalog: dict[str, UseCase]) -> None:
    """A registered kind nobody writes is a contract T2.5 would have to implement for nothing —
    and an invitation to reach for the vague one when a sharp assertion is what is needed."""
    used = {assertion.kind for use_case in catalog.values() for assertion in use_case.assertions}
    unused = sorted(set(KINDS) - used)

    assert unused == [], f"{unused} are in the vocabulary and no use case uses them"


def test_the_tiers_are_the_ones_the_cost_model_assumes(catalog: dict[str, UseCase]) -> None:
    counted = {tier: sum(1 for u in catalog.values() if u.tier == tier) for tier in EXPECTED_TIERS}

    assert counted == EXPECTED_TIERS
    assert len(catalog) == sum(EXPECTED_TIERS.values())


def test_the_import_use_case_expects_the_delta_the_fixture_measured(
    catalog: dict[str, UseCase],
) -> None:
    """uc19's per-namespace delta is a measurement — `test_07` takes it against a live import
    of the committed file — and this is the one place the two copies of it meet. Without this,
    a rebuilt fixture whose import behaves differently leaves uc19 asserting the old numbers."""
    imports = [
        use_case for use_case in catalog.values() if "gramps_import_file" in use_case.primary
    ]
    counts = [a for use_case in imports for a in use_case.assertions if a.kind == "counts"]

    assert len(counts) == 1
    assert counts[0].params["deltas"] == cast.COUSINS["delta"]


def test_every_count_delta_names_a_namespace_the_tree_actually_has(
    catalog: dict[str, UseCase],
) -> None:
    """A typo'd namespace (`sourcs: 1`) asserts nothing at all while looking like the sharpest
    assertion in the file — the same silence a misspelt assertion kind would have."""
    unknown = sorted(
        {
            namespace
            for use_case in catalog.values()
            for assertion in use_case.assertions
            if assertion.kind == "counts"
            for namespace in assertion.params["deltas"]
            if namespace not in cast.COUNTS
        }
    )

    assert unknown == [], f"{unknown} are not namespaces this tree counts"


def test_the_wipe_is_the_only_use_case_allowed_to_empty_the_tree(
    catalog: dict[str, UseCase],
) -> None:
    """G1 is the cheapest assertion in the suite and guards the only irreversible outcome the
    tool set permits: a model that answers a scoped request with `delete_all_objects`. Exactly
    one use case may suspend it, and it has to be the one that asked for a wipe."""
    suspended = sorted(u.id for u in catalog.values() if u.maxdrop == "everything")

    assert len(suspended) == 1, f"{suspended} suspend the no-mass-deletion guard"
    assert "gramps_delete_all_objects" in catalog[suspended[0]].primary
