# Generated by OrchestKit Claude Plugin
# Created: 2026-08-01

"""The image contract: what must be true of the artifact itself (plan T3.3, D19).

Needs Docker and nothing else — no Gramps Web, no credentials, no secrets. That is the point:
this is the leg that can be *required* on every pull request from day one, and it covers the
class of defect this repository has actually shipped twice.

`import backup_store, gramps_client, gramps_blog, server` inside the image is D19's chosen
form. The alternative that was considered and dropped was auditing the Dockerfile's `COPY`
line as text; it is a false-red generator (any root-level module that must *not* ship, or a
second `COPY … ./`, breaks it) and it proves less. The import either resolves in the image or
it does not, which is exactly the question.

The `mcp<2` pin is here rather than in the unit suite because the pin is only worth anything
where it is installed. `mcp 2.0.0` removed `mcp.server.fastmcp` outright — no shim, no rename —
so an image built after an unpinned bump crashes on `server.py`'s third line while every mocked
test on the host stays green.
"""

from __future__ import annotations

import re

import pytest
from harness.docker_util import docker
from harness.mcp_container import ImageRef
from harness.tool_contract import REPO_ROOT

SHIPPED_MODULES = ("backup_store", "gramps_client", "gramps_blog", "server")
REQUIREMENTS = REPO_ROOT / "requirements.txt"


def in_image(image: ImageRef, code: str) -> str:
    """Run Python inside the artifact, with no network and nothing mounted."""
    return docker(
        "run", "--rm", "--network", "none", "--entrypoint", "python",
        image.run_reference, "-c", code, timeout=120,
    ).strip()  # fmt: skip


def test_every_shipped_module_imports_inside_the_image(mcp_image: ImageRef) -> None:
    """D19. A module missing from the COPY list builds fine and dies on the first spawn."""
    modules = ", ".join(SHIPPED_MODULES)

    assert in_image(mcp_image, f"import {modules}; print('ok')") == "ok"


@pytest.mark.parametrize("module", SHIPPED_MODULES)
def test_each_module_is_named_one_at_a_time(mcp_image: ImageRef, module: str) -> None:
    """One import statement names the first module that is missing and stops.

    Four separate runs name all four, which is the difference between "the image is broken"
    and "the image is missing `backup_store`" — and the second one is a fix.
    """
    assert in_image(mcp_image, f"import {module}; print('ok')") == "ok"


def test_the_image_runs_a_one_point_x_mcp(mcp_image: ImageRef) -> None:
    """`mcp.server.fastmcp` is what `server.py` imports, and 2.0 deleted it.

    Both halves are asserted: the version the resolver landed on, and that the module the
    server actually needs is importable. A version test alone would pass a 1.x release that
    moved the package; an import test alone would pass a 2.x that happened to keep a stub.
    """
    # The package exposes no `__version__`; the installed distribution's metadata is the
    # only place the resolved version can be read from inside the image.
    version = in_image(mcp_image, "import importlib.metadata as m; print(m.version('mcp'))")
    fastmcp = in_image(mcp_image, "from mcp.server.fastmcp import FastMCP; print('importable')")

    assert int(version.split(".")[0]) == 1, f"the image installed mcp {version}"
    assert fastmcp == "importable"


def test_the_requirements_still_carry_the_upper_bound_and_its_reason() -> None:
    """The pin is a decision, and the comment above it is why nobody may quietly raise it.

    Deleting the bound is a one-character edit that no mocked test can see: the host venv is
    already resolved, so the next *image* build is where it lands. This is the cheapest place
    that notices.
    """
    text = REQUIREMENTS.read_text(encoding="utf-8")
    pin = re.search(r"^mcp>=[\d.]+,<2\s*$", text, re.MULTILINE)

    assert pin, "requirements.txt no longer pins mcp below 2.x"
    assert "fastmcp" in text.lower(), "the reason for the upper bound is no longer written down"
