# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""Before anything is graded, prove the run was a Stage-2 run (T2.4). No Docker, no model.

Stage 2's failure mode is not "the model got it wrong" — that is its *output*. Its failure mode
is a run that never had the tools, never had the isolation, or never finished, and whose
symptom is byte-identical to a catastrophic docstring defect: no calls, every assertion red.
The five forbidden flags each produce exactly that, and so does a `--strict-mcp-config` that
silently attached somebody else's server.

So the self-check runs first and refuses rather than grades. Two outcomes are kept apart on
purpose: `HarnessBroken` means *this run proves nothing about the product* — abort, fix the
harness. Inconclusive means the run was clean but did not finish arguing; it is not evidence
either way and must never reach the K-of-N counter.

An absent key is treated as broken, not as clean. The design note this suite was written from
named `n_skills` / `n_plugins`, which are not the wire keys (`skills` / `plugins` are) — a
`.get(key, 0)` check would have passed on every contaminated run there is.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest
from stage2 import selfcheck, transcript

FIXTURE = Path(__file__).parent / "fixtures" / "stage2" / "clean-run.jsonl"
CWD = "/tmp/gwe2e-stage2/cwd"


def run_with(**init: Any) -> transcript.Transcript:
    """The recorded clean run with one thing changed — same shape, one fact wrong."""
    events = transcript.read_events(FIXTURE)
    events[0].update(init)
    return transcript.from_events(events)


@pytest.fixture(scope="module")
def clean() -> transcript.Transcript:
    return transcript.load(FIXTURE)


def test_the_recorded_clean_run_passes(clean: transcript.Transcript) -> None:
    """The positive control. Without it every assertion below is satisfied by a broken check."""
    selfcheck.verify(clean, cwd=CWD)
    assert selfcheck.inconclusive_reason(clean) is None


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("skills", ["superpowers:brainstorming"]),
        ("plugins", ["ork"]),
        ("slash_commands", ["commit"]),
        ("agents", ["claude"] * 41),
    ],
)
def test_a_contaminated_session_is_refused(field: str, value: list[str]) -> None:
    """`--setting-sources ""` is the lever; these lists are how one sees whether it moved."""
    with pytest.raises(selfcheck.HarnessBroken, match=field):
        selfcheck.verify(run_with(**{field: value}), cwd=CWD)


@pytest.mark.parametrize("field", ["skills", "plugins", "slash_commands", "mcp_servers"])
def test_a_missing_field_is_refused_rather_than_read_as_clean(field: str) -> None:
    """The `n_skills` trap: a key nobody emits is not a key nobody violated."""
    events = transcript.read_events(FIXTURE)
    del events[0][field]

    with pytest.raises(selfcheck.HarnessBroken, match=field):
        selfcheck.verify(transcript.from_events(events), cwd=CWD)


def test_a_second_mcp_server_is_refused() -> None:
    """Without `--strict-mcp-config` the developer's own servers attach and get graded."""
    with pytest.raises(selfcheck.HarnessBroken, match="context-mode"):
        selfcheck.verify(
            run_with(
                mcp_servers=[
                    {"name": "gramps", "status": "pending"},
                    {"name": "context-mode", "status": "connected"},
                ]
            ),
            cwd=CWD,
        )


def test_the_pending_status_of_the_gramps_server_is_not_a_failure(
    clean: transcript.Transcript,
) -> None:
    """Measured: at init the server is `pending` — it connects later. Gating on `connected`
    here would red every single run."""
    assert clean.init["mcp_servers"] == [{"name": "gramps", "status": "pending"}]
    selfcheck.verify(clean, cwd=CWD)


def test_a_run_that_never_reached_the_gramps_tools_is_a_harness_fault() -> None:
    """The expensive false red, caught: no call and no reference means no tools existed."""
    events = [event for event in transcript.read_events(FIXTURE) if event["type"] != "user"]
    events = [
        event
        for event in events
        if not (
            event["type"] == "assistant"
            and any(
                block.get("name", "").startswith("mcp__gramps__")
                for block in event["message"]["content"]
            )
        )
    ]

    with pytest.raises(selfcheck.HarnessBroken, match="no gramps tool"):
        selfcheck.verify(transcript.from_events(events), cwd=CWD)


def test_a_search_that_surfaced_the_tools_is_enough(clean: transcript.Transcript) -> None:
    """A use case may legitimately end without a call — a refusal case, or a read the model
    answered from an earlier result. What may not happen is the tools never existing."""
    events = [event for event in transcript.read_events(FIXTURE) if "msg_02" not in str(event)]

    selfcheck.verify(transcript.from_events(events), cwd=CWD)


@pytest.mark.parametrize(
    ("field", "value", "expected"),
    [
        ("permissionMode", "default", "permissionMode"),
        ("apiKeySource", "ANTHROPIC_API_KEY", "apiKeySource"),
        ("claude_code_version", "2.2.0", "2.1.220"),
        ("model", "claude-opus-5", "claude-sonnet-5"),
        ("cwd", "/home/julian-prentl/projects/gramps-remote-mcp", "cwd"),
    ],
)
def test_a_run_that_is_not_the_verified_configuration_is_refused(
    field: str, value: str, expected: str
) -> None:
    """Each of these silently changes what the run measures: the permission surface, who pays
    and which account, the flag semantics, the baseline, and which memory the session sees."""
    with pytest.raises(selfcheck.HarnessBroken, match=expected):
        selfcheck.verify(run_with(**{field: value}), cwd=CWD)


def test_the_claude_md_canary_fires(clean: transcript.Transcript) -> None:
    """The observed signature of the user's global memory leaking back in."""
    events = transcript.read_events(FIXTURE)
    events[-1]["result"] = "Verstanden: ich lege die Person an."

    with pytest.raises(selfcheck.HarnessBroken, match="Verstanden"):
        selfcheck.verify(transcript.from_events(events), cwd=CWD)


def test_a_permission_denial_is_a_harness_fault() -> None:
    """`bypassPermissions` was verified to produce none; one means the run was fenced in."""
    events = transcript.read_events(FIXTURE)
    events[-1]["permission_denials"] = [{"tool_name": "mcp__gramps__gramps_add_person"}]

    with pytest.raises(selfcheck.HarnessBroken, match="permission"):
        selfcheck.verify(transcript.from_events(events), cwd=CWD)


def test_too_many_turns_is_inconclusive_not_failed() -> None:
    """A model that flailed for 13 turns did not disprove the docstring; it ran out of room."""
    events = transcript.read_events(FIXTURE)
    events[-1]["num_turns"] = 13

    reason = selfcheck.inconclusive_reason(transcript.from_events(events))

    assert reason is not None and "13" in reason


def test_an_errored_result_is_inconclusive() -> None:
    events = transcript.read_events(FIXTURE)
    events[-1] |= {"subtype": "error_during_execution", "is_error": True}

    assert selfcheck.inconclusive_reason(transcript.from_events(events)) is not None


def test_inconclusive_is_not_broken() -> None:
    """The distinction is the whole point: a timeout is not evidence of a harness fault."""
    events = transcript.read_events(FIXTURE)
    events[-1]["num_turns"] = 13

    selfcheck.verify(transcript.from_events(events), cwd=CWD)
