# Generated by OrchestKit Claude Plugin
# Created: 2026-07-30

"""The canonical fixture reads back exactly as built (plan D2, T1.6). Needs Docker.

Named `test_05_` rather than the plan's `test_00_fixture.py` because `test_00_*` means
Docker-free in this suite, and this one imports through the shipped container on purpose: it
is the product's own import path, so a fixture that only a hand-written REST call can load
would be a fixture the suite cannot actually use.

The size is load-bearing. `count_people`/`count_families`/`count_sources` in the product are
`len(unpaginated list)` and the server's default pagesize is 20 — at 20 objects or fewer the
pagination assumption is simply untested, which is the vacuity class this suite exists to kill.
"""

from __future__ import annotations

import shutil
from collections.abc import Iterator
from pathlib import Path

import pytest
from fixtures import cast
from harness.gramps_instance import OWNER_PW, OWNER_USER, ROLE_OWNER, GrampsInstance
from harness.mcp_container import ImageRef, McpContainer, container_name
from harness.rest import GrampsRest
from harness.runid import new_runid

TREE_FILE = Path(__file__).parent / "fixtures" / "synthetic-tree.gramps"
PAGESIZE = 20


@pytest.fixture(scope="module")
def instance() -> Iterator[GrampsInstance]:
    started = GrampsInstance(new_runid())
    started.start()
    assert started.add_user(OWNER_USER, OWNER_PW, ROLE_OWNER)["rc"] == 0
    try:
        yield started
    finally:
        started.teardown()


@pytest.fixture(scope="module")
def imported(
    instance: GrampsInstance, mcp_image: ImageRef, tmp_path_factory: pytest.TempPathFactory
) -> Iterator[GrampsRest]:
    """Import the committed fixture through `gramps_import_file`, then hand over the oracle."""
    backup = tmp_path_factory.mktemp("backup")
    shutil.copy(TREE_FILE, backup / TREE_FILE.name)
    backup.chmod(0o777)  # the container runs as a different uid than the test process

    mcp = McpContainer(
        container_name(instance.runid, "fixture"),
        mcp_image.run_reference,
        {
            "GRAMPS_BASE_URL": instance.internal_url,
            "GRAMPS_USERNAME": OWNER_USER,
            "GRAMPS_PASSWORD": OWNER_PW,
            "GRAMPS_BACKUP_DIR": "/data",
        },
        network=instance.network,
        mounts=((str(backup), "/data"),),
        runid=instance.runid,
    )
    try:
        result = mcp.call("gramps_import_file", {"filename": TREE_FILE.name}, timeout=600)
        assert not result.is_error, result.text
        yield GrampsRest(instance.url, OWNER_USER, OWNER_PW)
    finally:
        assert mcp.close() == [], "the MCP container outlived its test"


def test_the_fixture_is_plain_xml() -> None:
    """A gzipped export is not diff-stable — its wrapper carries a UUID, so a rebuild would
    show a wall of changed bytes whether or not the tree changed."""
    head = TREE_FILE.read_bytes()[:64]

    assert head[:2] != b"\x1f\x8b", "still gzipped"
    assert head.startswith(b"<?xml")


def test_every_namespace_is_larger_than_one_page() -> None:
    """Under 21 the `len(unpaginated list)` assumption in the product is untestable."""
    assert cast.COUNTS["people"] > PAGESIZE
    assert cast.COUNTS["families"] > PAGESIZE
    assert cast.COUNTS["sources"] > PAGESIZE


def test_the_import_lands_exactly_the_cast(imported: GrampsRest) -> None:
    """Every namespace, not just the three the cast is named for. Gramps records a repaired
    dangling reference as an extra **note**, so the note count is what turns a subtly damaged
    fixture red — measured: deleting a whole `<family>` element leaves people, families and
    sources untouched and shows up only there."""
    assert imported.object_counts() == cast.COUNTS


def test_the_unpaginated_lists_agree_with_the_counts(imported: GrampsRest) -> None:
    """The product counts by `len(list)`; if the server ever paginates that list by default,
    every count-based guard in the server silently starts reporting 20."""
    counts = imported.object_counts()

    assert len(imported.people()) == counts["people"]
    assert len(imported.families()) == counts["families"]
    assert len(imported.sources()) == counts["sources"]


def test_the_gramps_ids_survive_the_import(imported: GrampsRest) -> None:
    """Ids are assigned by the server in creation order and are the cast's whole point — an
    import that renumbers them would leave every later test asserting against nothing."""
    landed = {record["gramps_id"] for record in imported.people()}

    assert {person["gramps_id"] for person in cast.PEOPLE} <= landed
    assert cast.PEOPLE[0]["gramps_id"] == "I0000", "ids start at I0000, not I0001"


def test_a_person_reads_back_with_the_name_the_cast_records(imported: GrampsRest) -> None:
    expected = cast.PEOPLE[0]
    person = imported.person(str(expected["gramps_id"]))
    name = person["primary_name"]

    assert name["first_name"] == expected["first_name"]
    assert name["surname_list"][0]["surname"] == expected["surname"]
    assert person["gender"] == expected["gender"]


def test_every_family_reads_back_with_the_members_the_cast_records(imported: GrampsRest) -> None:
    """Counting families cannot detect a damaged one. Each person carries a `<parentin>` or
    `<childof>` reference, so deleting a whole `<family>` element leaves the count at 21 — the
    importer rebuilds one from the dangling reference. Measured: that mutation survived a
    count-only assertion. Only the membership catches it."""
    families = {family["gramps_id"]: family for family in imported.families()}
    person_id = {person["handle"]: person["gramps_id"] for person in imported.people()}

    for expected in cast.FAMILIES:
        family = families[str(expected["gramps_id"])]
        parents = {
            person_id.get(handle)
            for handle in (family["father_handle"], family["mother_handle"])
            if handle
        }
        children = {person_id.get(ref["ref"]) for ref in family["child_ref_list"]}

        assert parents == {expected["spouse_a"], expected["spouse_b"]}
        assert children == set(expected["children"])


def test_the_families_carry_their_children(imported: GrampsRest) -> None:
    """Without child links the fixture is 21 unrelated couples, and every descendant or
    ancestor test built on it would walk a graph with no edges."""
    with_children = [family for family in imported.families() if family["child_ref_list"]]

    assert len(with_children) == len([f for f in cast.FAMILIES if f["children"]])
    assert with_children, "no family has a child"


def test_both_tags_the_tools_create_are_already_seeded(imported: GrampsRest) -> None:
    """`add_person` creates `Unbestätigt` on first use and a blog post creates `Blog`. If the
    fixture seeded neither, the first write in any later test would move the tag count by one
    and read as a failure."""
    names = {tag["name"] for tag in imported.tags()}

    assert {"Blog", "Unbestätigt"} <= names
