# Generated by OrchestKit Claude Plugin
# Created: 2026-07-30

"""The assertion helpers against the shipped container and a live tree (T1.7). Needs Docker.

`test_00_assertions.py` proves the helpers catch a lying server; this proves they agree with
the honest one. The two are not interchangeable. The fake cannot show that `assert_guarded_write`
survives the *real* wire — where the product snapshots the person it read from
`/api/people/?gramps_id=…` while the oracle re-reads `/api/people/<handle>`, and the two
projections need not be byte-identical. If comparing whole records were wrong, only this file
would say so.

Its second job is to be the target of the mutation probe: with `self._put_person(...)` removed
from `gramps_client._write_person`, the person write here has to go red.
"""

from __future__ import annotations

from collections.abc import Iterator

import pytest
from fixtures import cast
from harness.assertions import assert_guarded_write, assert_refusal
from harness.backup_dir import BackupDir
from harness.gramps_instance import OWNER_PW, OWNER_USER, ROLE_OWNER, GrampsInstance
from harness.mcp_container import ImageRef, McpContainer, container_name
from harness.rest import GrampsRest
from harness.runid import new_runid

# Needs a live Gramps Web instance, not merely Docker. Declared rather than inferred: the
# required CI leg selects `-m 'e2e and not gramps'`, and a module that forgets this marker
# would drag a whole instance bring-up into the job that is meant to need no services.
pytestmark = pytest.mark.gramps

FIXTURE = "synthetic-tree.gramps"
SUBJECT = cast.PEOPLE[0]["gramps_id"]
FIRST_NAME = "primary_name.first_name"


@pytest.fixture(scope="module")
def instance() -> Iterator[GrampsInstance]:
    started = GrampsInstance(new_runid())
    started.start()
    assert started.add_user(OWNER_USER, OWNER_PW, ROLE_OWNER)["rc"] == 0
    try:
        yield started
    finally:
        started.teardown()


@pytest.fixture(scope="module")
def backup(tmp_path_factory: pytest.TempPathFactory) -> BackupDir:
    """D17: the directory the container sees starts as exactly the declared input set."""
    directory = BackupDir(tmp_path_factory.mktemp("mount") / "data")
    directory.reset()
    return directory


@pytest.fixture(scope="module")
def mcp(instance: GrampsInstance, mcp_image: ImageRef, backup: BackupDir) -> Iterator[McpContainer]:
    """One container for the module, with the destructive tools registered so the refusal
    case has something to refuse."""
    container = McpContainer(
        container_name(instance.runid, "assertions"),
        mcp_image.run_reference,
        {
            "GRAMPS_BASE_URL": instance.internal_url,
            "GRAMPS_USERNAME": OWNER_USER,
            "GRAMPS_PASSWORD": OWNER_PW,
            "GRAMPS_BACKUP_DIR": "/data",
            "GRAMPS_ENABLE_DESTRUCTIVE": "1",
        },
        network=instance.network,
        mounts=((str(backup.path), "/data"),),
        runid=instance.runid,
    )
    try:
        imported = container.call("gramps_import_file", {"filename": FIXTURE}, timeout=600)
        assert not imported.is_error, imported.text
        yield container
    finally:
        assert container.close() == [], "the MCP container outlived its test"


@pytest.fixture(scope="module")
def rest(instance: GrampsInstance) -> GrampsRest:
    return GrampsRest(instance.url, OWNER_USER, OWNER_PW)


def test_a_person_write_is_certified_by_the_tree_not_by_the_report(
    rest: GrampsRest, mcp: McpContainer
) -> None:
    """The mutation target. Remove the PUT from `_write_person` and the report is unchanged —
    only the re-read below notices."""
    written = assert_guarded_write(
        rest,
        mcp,
        "gramps_set_first_name",
        {"gramps_id": SUBJECT, "first_name": "Reinhold"},
        expect_delta={},
        self_report="person",
        expect_person={SUBJECT: {FIRST_NAME: "Reinhold"}},
    )

    assert written.delta == {}


def test_a_new_person_resolves_under_the_id_the_tool_reports(
    rest: GrampsRest, mcp: McpContainer
) -> None:
    """`add_person` is one of the three bare-`str` tools, so its id arrives in
    `structuredContent` rather than in the text — and an id is only evidence once it resolves."""
    written = assert_guarded_write(
        rest,
        mcp,
        "gramps_add_person",
        {"first_name": "Wendelin", "surname": "Brehmer", "gender": 1},
        expect_delta={"people": 1},
        self_report="id",
        id_namespace="people",
    )

    assert rest.person(written.payload)["primary_name"]["first_name"] == "Wendelin"


def test_a_missing_confirmation_refuses_and_changes_nothing(
    rest: GrampsRest, mcp: McpContainer
) -> None:
    assert_refusal(
        rest,
        mcp,
        "gramps_delete_person",
        {"gramps_id": SUBJECT},
        contains="requires confirm=True",
    )


def test_a_path_that_escapes_the_backup_directory_refuses(
    rest: GrampsRest, mcp: McpContainer
) -> None:
    """The guard lives in `backup_store.py`, which is a product module like the other three —
    the vocabulary meta-test accepts this fragment for exactly that reason."""
    assert_refusal(
        rest,
        mcp,
        "gramps_import_file",
        {"filename": "../etc/passwd"},
        contains="Path escapes backup directory",
    )


def test_an_export_appears_under_the_name_this_test_chose(
    rest: GrampsRest, mcp: McpContainer, backup: BackupDir
) -> None:
    """D17: never "is there a file", always "did *this* file appear in this call". The default
    name is a 1-second timestamp, so two default exports in one second overwrite each other.

    `external` is the shape that says the evidence is not in the tree — which is precisely why
    the `assert_export` below is not optional decoration but the assertion this test rests on."""
    before = backup.listing()

    assert_guarded_write(
        rest,
        mcp,
        "gramps_export_tree",
        {"filename": "acceptance.gramps"},
        expect_delta={},
        self_report="external",
        timeout=300.0,
    )

    written = backup.assert_export(before, filename="acceptance.gramps")
    assert written.stat().st_size > 0
