# Generated by OrchestKit Claude Plugin
# Created: 2026-08-02

"""Blog CRUD and the backup round trip, against a live server. Needs Docker.

Sixteen cases selected in `phase-4/triage-product-risk.md` out of the matrix's 50. Five of the
matrix's ids (R1–R5) and two more (M8, W5) are already committed in `test_01_env_wiring.py`,
`test_08_protocol.py` and `test_80_regressions.py`; re-implementing them here is what the triage's
K16 exists to prevent.

The centre of gravity is `TestTheExportIsTheWayBack`. `gramps_delete_all_objects` tells the calling
model that an export "is the only way back", and until this module nothing had ever fed one of this
server's own exports through its own importer — the export is gzip, every import this suite has
ever performed was plain XML.
"""

from __future__ import annotations

import pytest
from fixtures import cast
from harness.assertions import (
    EVERYTHING,
    assert_guarded_write,
    assert_refusal,
    payload,
    payload_list,
)

pytestmark = pytest.mark.gramps

BODY_FIRST = "Der erste Rumpf, geschrieben von der Stufe-1-Matrix."
BODY_SECOND = "Der zweite Rumpf. Dieselbe Notiz, anderer Text."


def blog_tag_handle(rest) -> str:
    """Tags have no gramps_id — they are identified by handle (`movement.py:70`), so the Blog tag
    must be resolved from the tree rather than named."""
    return next(tag["handle"] for tag in rest.tags() if tag["name"] == "Blog")


class TestTheBlogChain:
    """Ordered: each case uses what the one before it created. `seeded_tree.state` carries the
    server-assigned ids, because nothing here may hardcode one."""

    @pytest.mark.chain
    def test_a_post_is_a_tagged_source_plus_a_body_note(self, seeded_tree) -> None:
        """`tags` is deliberately absent from the delta: the Blog tag already exists on all 23
        committed sources, so the correct movement is zero and a regression that mints a second
        Blog tag reds here rather than going unnoticed."""
        written = assert_guarded_write(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_create_blog_post",
            {"title": "Erster Eintrag", "body": BODY_FIRST, "author": "Harness"},
            expect_delta={"sources": 1, "notes": 1},
            self_report="id",
            id_namespace="sources",
        )
        seeded_tree.state["first"] = written.payload

        source = seeded_tree.rest.by_gramps_id("sources", written.payload)
        assert source["author"] == "Harness"
        assert source["tag_list"] == [blog_tag_handle(seeded_tree.rest)]
        assert len(source["note_list"]) == 1
        seeded_tree.state["first_note"] = source["note_list"][0]

    @pytest.mark.chain
    def test_an_omitted_author_is_stored_as_the_empty_string(self, seeded_tree) -> None:
        """`author or ""` (`gramps_blog.py:72`) is the only thing between an omitted author and a
        null byline. `_assert_fields_landed` resolves a missing key to `ABSENT`, never to `None`,
        so a dropped field reds instead of passing as the value we expected anyway."""
        written = assert_guarded_write(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_create_blog_post",
            {"title": "Zweiter Eintrag", "body": "Ohne Verfasser."},
            expect_delta={"sources": 1, "notes": 1},
            self_report="id",
            id_namespace="sources",
        )
        seeded_tree.state["second"] = written.payload

        assert seeded_tree.rest.by_gramps_id("sources", written.payload)["author"] == ""

    @pytest.mark.chain
    def test_the_listing_is_every_blog_source_and_only_the_four_projected_keys(
        self, seeded_tree
    ) -> None:
        """`list_blog_posts` hand-builds a URL-quoted rules query plus `keys=` plus `sort=-change`
        (`gramps_blog.py:97-107`). If the server's rules grammar, its projection or its sort key
        moves, this tool returns every source, none, or fat records — and the feature is silently
        broken for every caller."""
        rows = payload_list(seeded_tree.mcp.call("gramps_list_blog_posts", {}))

        expected = {source["gramps_id"] for source in cast.SOURCES} | {
            seeded_tree.state["first"],
            seeded_tree.state["second"],
        }
        assert {row["gramps_id"] for row in rows} == expected
        assert all(set(row) == {"gramps_id", "title", "author", "change"} for row in rows)
        changes = [row["change"] for row in rows]
        assert changes == sorted(changes, reverse=True), "the tool documents newest first"

    @pytest.mark.chain
    def test_a_pagesize_of_one_returns_one_row(self, seeded_tree) -> None:
        """The `page` default at `gramps_blog.py:95-96` exists because gramps-web-api ignores
        `pagesize` when `page < 1` and hands back everything — the shape that blows a model's
        context window."""
        rows = payload_list(seeded_tree.mcp.call("gramps_list_blog_posts", {"pagesize": 1}))

        assert len(rows) == 1

    @pytest.mark.chain
    def test_a_post_reads_back_with_a_rendered_body(self, seeded_tree) -> None:
        """`body_html` comes from `(note.get("formatted") or {}).get("html")` after asking for
        `?formats=html` (`gramps_blog.py:137-144`). If the server ignores or renames that
        parameter the tool degrades to `body_html=None` on every post, forever, with no error."""
        post = payload(
            seeded_tree.mcp.call("gramps_get_blog_post", {"gramps_id": seeded_tree.state["first"]})
        )
        note = seeded_tree.rest.get_json(f"/api/notes/{seeded_tree.state['first_note']}")

        assert post["body_text"] == note["text"]["string"]
        assert post["body_html"], "the rendered half is missing — formats=html did not take"
        assert post["body_html"] != post["body_text"]

    @pytest.mark.chain
    def test_updating_a_title_leaves_the_rest_of_the_source_standing(self, seeded_tree) -> None:
        """The sources instance of the projection pin (`triage-product-risk.md` §1):
        `update_blog_post` reads `/api/sources/?gramps_id=` and PUTs it back whole, and a partial
        body blanks every omitted field. Measured complete today — this notices if that changes.

        `self_report="unguarded"` makes `expect_record` mandatory (`gate.py:36,84-92`), which is
        the point: this tool's report is its own arguments plus a list of field names."""
        first = seeded_tree.state["first"]

        assert_guarded_write(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_update_blog_post",
            {"gramps_id": first, "title": "Erster Eintrag, überarbeitet"},
            expect_delta={},
            self_report="unguarded",
            expect_record={
                "sources": {
                    first: {
                        "title": "Erster Eintrag, überarbeitet",
                        "author": "Harness",
                        "tag_list.0": blog_tag_handle(seeded_tree.rest),
                        "note_list.0": seeded_tree.state["first_note"],
                    }
                }
            },
        )

    @pytest.mark.chain
    def test_updating_a_body_rewrites_the_same_note_instead_of_orphaning_it(
        self, seeded_tree
    ) -> None:
        """`expect_delta={}` is what catches create-new-and-leave-the-old-one: that regression
        moves `notes` by +1 and is invisible to any assertion that only reads the new text."""
        first = seeded_tree.state["first"]
        note_handle = seeded_tree.state["first_note"]

        assert_guarded_write(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_update_blog_post",
            {"gramps_id": first, "body": BODY_SECOND},
            expect_delta={},
            self_report="unguarded",
            expect_record={"sources": {first: {"note_list.0": note_handle}}},
        )

        assert seeded_tree.rest.by_gramps_id("sources", first)["note_list"] == [note_handle]
        assert (
            BODY_SECOND in seeded_tree.rest.get_json(f"/api/notes/{note_handle}")["text"]["string"]
        )

    @pytest.mark.chain
    def test_a_written_post_moves_to_the_front_of_the_listing(self, seeded_tree) -> None:
        """Non-vacuous only because the second post was created *after* the first, so the first
        was second until the two updates above rewrote its `change`. If this reds, the server
        stopped bumping `change` on a PUT and the tool's "newest first" promise is the lie."""
        rows = payload_list(seeded_tree.mcp.call("gramps_list_blog_posts", {}))

        assert rows[0]["gramps_id"] == seeded_tree.state["first"]


class TestExportingTheTree:
    def test_the_extension_reaches_both_the_exporter_and_the_filename(self, seeded_tree) -> None:
        """`export_tree` builds the exporter URL from `extension` (`gramps_client.py:377-379`) and
        `resolve_export_path` builds the filename from the same argument
        (`backup_store.py:16-20`). Hardcode `gramps` in either and a user gets a file named `.csv`
        holding gzipped Gramps XML — and nothing back when they restore it."""
        before = seeded_tree.backup.listing()

        reported = payload(seeded_tree.mcp.call("gramps_export_tree", {"extension": "csv"}))

        written = seeded_tree.backup.assert_export(
            before, filename=reported["path"].rsplit("/", 1)[-1]
        )
        assert written.name.endswith(".csv")
        assert written.read_bytes()[:2] != b"\x1f\x8b", "a CSV export must not be gzip"


class TestTheExportIsTheWayBack:
    """The claim `gramps_delete_all_objects` makes to the calling model, tested end to end.

    Ordered and expensive: export, wipe, restore. `BackupDir.reset()` would delete the export, so
    the class must not span a reseed — which is exactly why `seeded_tree` is class-scoped.
    """

    @pytest.mark.chain
    def test_an_export_reports_the_file_it_actually_wrote(self, seeded_tree) -> None:
        """`{"bytes": len(data)}` is computed from the downloaded buffer, not from the file
        (`server.py:285-286`). A short write through the bind mount — a uid that cannot write, a
        full disk — reports a full-size backup that is not there."""
        before = seeded_tree.backup.listing()
        seeded_tree.state["snapshot"] = seeded_tree.rest.snapshot()

        reported = payload(
            seeded_tree.mcp.call("gramps_export_tree", {"filename": "zurueck.gramps"})
        )

        written = seeded_tree.backup.assert_export(before, filename="zurueck.gramps")
        assert written.stat().st_size == reported["bytes"]
        assert reported["counts"] == seeded_tree.rest.object_counts()
        assert written.read_bytes()[:2] == b"\x1f\x8b", "the default export is gzip"

    @pytest.mark.chain
    def test_the_wipe_empties_the_tree(self, seeded_tree) -> None:
        total = seeded_tree.rest.total()

        assert_guarded_write(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_delete_all_objects",
            {"confirm": True, "expected_count": total},
            expect_delta={name: -value for name, value in cast.COUNTS.items() if value},
            self_report="counts",
            expect_removed={name: EVERYTHING for name, value in cast.COUNTS.items() if value},
            timeout=600.0,
        )

        assert seeded_tree.rest.total() == 0

    @pytest.mark.chain
    def test_importing_that_export_puts_the_tree_back(self, seeded_tree) -> None:
        """Nothing had ever fed one of this server's own exports back through its own importer.
        If the identity sets below differ, the backup is not a way back and the wipe tool's
        docstring is making a promise the product does not keep."""
        assert_guarded_write(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_import_file",
            {"filename": "zurueck.gramps"},
            expect_delta={name: value for name, value in cast.COUNTS.items() if value},
            self_report="counts",
            timeout=600.0,
        )

        restored = seeded_tree.rest.snapshot()
        assert restored["counts"] == cast.COUNTS
        assert restored["objects"] == seeded_tree.state["snapshot"]["objects"]


class TestTheGuardsAroundTheBackupDirectory:
    @pytest.mark.refusal
    def test_an_export_may_not_escape_the_directory(self, seeded_tree) -> None:
        """The second half is the one that matters: a guard that refuses *and writes anyway*
        reads exactly like a clean rejection to `is_error` and to the text."""
        before = seeded_tree.backup.listing()

        assert_refusal(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_export_tree",
            {"filename": "../entwischt.gramps"},
            contains="Path escapes backup directory",
        )

        assert seeded_tree.backup.listing() == before

    @pytest.mark.refusal
    def test_an_import_of_a_file_that_is_not_there_says_so(self, seeded_tree) -> None:
        """Non-vacuous only because `BackupDir.reset()` guarantees what the directory holds."""
        assert_refusal(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_import_file",
            {"filename": "gibtsnicht.gramps"},
            contains="Import file not found in backup directory",
        )

    @pytest.mark.refusal
    def test_an_empty_filename_is_refused_rather_than_defaulted(self, seeded_tree) -> None:
        """`Invalid filename` fires on an empty name or a NUL byte and on nothing else
        (`backup_store.py:7`) — a space is a perfectly good filename, so the matrix's `"a b"`
        case was wrong about the product and would have landed red.

        The empty string is the interesting one anyway: `resolve_export_path` defaults the name
        only when `filename is None` (`:17-19`), so `""` must refuse rather than quietly write a
        timestamped export the caller never asked for. The listing check is what proves it did
        not."""
        before = seeded_tree.backup.listing()

        assert_refusal(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_export_tree",
            {"filename": ""},
            contains="Invalid filename",
        )

        assert seeded_tree.backup.listing() == before

    @pytest.mark.refusal
    def test_the_wipe_refuses_a_count_that_does_not_match_the_tree(self, seeded_tree) -> None:
        """The count is read live and never written as a literal: the whole point of the guard is
        that it compares against the tree, so a test that hardcoded the total would pass on a
        tree the fixture no longer describes."""
        total = seeded_tree.rest.total()

        assert_refusal(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_delete_all_objects",
            {"confirm": True, "expected_count": total + 1},
            contains="does not match the live total",
        )
