# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""The leak lint itself, and the two exemptions it grants (plan T2.7). No Docker, no LLM.

The lint is the guard without which every Stage-2 use case is worthless: a prompt that names
the tool it expects comes back green whatever the docstring says. Its own rule is one line, so
what needs testing is the two places it deliberately does *not* fire — and that both of those
holes stay closed by something other than good intentions.
"""

from __future__ import annotations

from unittest.mock import MagicMock

import pytest
from stage2.catalog import UseCase, load_all
from stage2.leak_lint import DOMAIN_WORDS, FUNCTION_WORDS, leaks, name_tokens, stale, tokens

import server

TOOLS = ("gramps_add_person", "gramps_delete_person", "gramps_export_tree", "gramps_list_people")


@pytest.fixture(scope="module")
def registered() -> set[str]:
    return set(server.create_server(MagicMock(), enable_destructive=True)[1])


@pytest.fixture(scope="module")
def catalog() -> dict[str, UseCase]:
    return load_all()


def test_a_word_only_one_tool_has_in_its_name_is_a_leak() -> None:
    found = leaks("Please export the whole thing", TOOLS)

    assert [(leak.token, leak.tool) for leak in found] == [("export", "gramps_export_tree")]


def test_a_word_several_tools_share_says_nothing() -> None:
    """`person` is in five tool names — a prompt saying it has not narrowed anything down."""
    assert leaks("Please look at this person", TOOLS) == []


def test_the_domain_words_are_let_through_when_they_point_elsewhere() -> None:
    """A use case about deleting somebody may say "in my tree" — `export_tree` is not what it
    is testing, so the word costs the measurement nothing."""
    assert leaks("Get that junk entry out of my tree", TOOLS, ["gramps_delete_person"]) == []


def test_the_domain_exemption_stops_at_the_use_case_s_own_primary() -> None:
    """The hole that would matter: uc7 asking for a copy of "the tree" would hand
    `gramps_export_tree` over, and its green run would then say nothing about the docstring."""
    found = leaks("I'd like a copy of the whole tree", TOOLS, ["gramps_export_tree"])

    assert [leak.token for leak in found] == ["tree"]


def test_english_glue_inside_a_tool_name_is_not_signal() -> None:
    """`add_child_to_family` owns "to" and `remove_child_from_family` owns "from". Nobody
    writes a prompt without them and neither carries a gram of information."""
    assert FUNCTION_WORDS <= name_tokens("gramps_add_child_to_family") | name_tokens(
        "gramps_remove_child_from_family"
    )
    assert leaks("Move him to the other household", ["gramps_add_child_to_family"]) == []


def test_the_plural_fold_applies_to_both_sides() -> None:
    """A prompt saying "objects" must still meet `delete_all_objects`, or the rule is a
    spelling test."""
    found = leaks("Delete the objects", ["gramps_delete_all_objects", "gramps_add_person"])

    assert [leak.token for leak in found] == ["delete", "object"]
    assert tokens("Counts, counting, count") == ["count", "counting"]


def test_a_prompt_that_quotes_a_tool_name_outright_is_caught(registered: set[str]) -> None:
    """The crude case the whole lint exists for, against the live registry rather than a
    handful of names."""
    found = leaks("Please call gramps_confirm_person on her", registered)

    assert {leak.token for leak in found} == {"confirm"}


def test_every_domain_word_is_still_needed_by_a_prompt(
    catalog: dict[str, UseCase], registered: set[str]
) -> None:
    """Each exemption is a hole in the guard. One that no prompt needs any more gets deleted,
    not kept in case somebody wants it back.

    Passing every tool as `primary` is what switches the exemption off, so this asks the
    question the other way round: which words *would* be reported without it."""
    would_be_flagged = {
        leak.token
        for use_case in catalog.values()
        for leak in leaks(use_case.prompt, registered, registered)
    }
    unnecessary = sorted(DOMAIN_WORDS - would_be_flagged)

    assert unnecessary == [], f"{unnecessary} are exempted and no prompt needs the exemption"


def test_no_use_case_carries_a_waiver_for_a_word_it_no_longer_says(
    catalog: dict[str, UseCase], registered: set[str]
) -> None:
    """A rewritten prompt that leaves its waiver behind re-arms the leak silently: the next
    edit that puts the word back passes, because an exemption is already sitting there."""
    left_behind = {
        use_case.id: sorted(
            stale(
                leaks(use_case.prompt, registered, use_case.primary),
                {waiver.token for waiver in use_case.waivers},
            )
        )
        for use_case in catalog.values()
        if use_case.waivers
    }

    assert {identifier: stale for identifier, stale in left_behind.items() if stale} == {}


def test_the_waivers_that_exist_say_why(catalog: dict[str, UseCase]) -> None:
    """A waiver without an argument is how a leak becomes permanent. The count is small on
    purpose — one, today — so a growing list is visible in the diff."""
    waived = [(u.id, w.token, w.reason) for u in catalog.values() for w in u.waivers]

    assert waived, "no waiver at all would mean the rule never fired — check the lint"
    for identifier, token, reason in waived:
        assert len(reason.split()) >= 12, f"{identifier} waives {token!r} with a one-liner"
