# Generated by OrchestKit Claude Plugin
# Created: 2026-08-01

"""What the container does with a broken environment (plan T3.2, D11). Docker, no Gramps Web.

Every one of these is a deployment mistake, not a code change, and every one of them reaches
the user as something the MCP client shows — or fails to show. Three distinct shapes, and the
difference between them is the whole point:

* **the server never starts** (a required variable is missing) — the process exits and the
  handshake never happens, so nothing about the failure is visible over the protocol;
* **the server starts and the tool refuses** (`GRAMPS_BACKUP_DIR` unset) — the tool is still
  registered and answers with a reason the model can act on;
* **the server starts and the call fails at the far end** (unroutable host) — the failure is
  the network's, and it must arrive as a tool error rather than as a hang.

The fourth group is the destructive gate: `GRAMPS_ENABLE_DESTRUCTIVE` is compared to the exact
string `"1"`, so every other truthy-looking value must leave the tools unregistered. That is a
fail-*open* probe: the assertion that matters is the one where the tools are absent, and the
`"1"` case is its control — without it a gate that registered nothing at all would pass.
"""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager

import pytest
from harness import tool_contract
from harness.docker_util import ProbeError
from harness.mcp_container import ImageRef, McpContainer, container_name

UNROUTABLE = "http://gwe2e-nowhere:5000"
BASE = {
    "GRAMPS_BASE_URL": UNROUTABLE,
    "GRAMPS_USERNAME": "nobody",
    "GRAMPS_PASSWORD": "unused",
}
TOOLS_WITHOUT_DESTRUCTIVE = 27
TOOLS_WITH_DESTRUCTIVE = 31


@contextmanager
def container(
    image: ImageRef, runid: str, label: str, env: dict[str, str]
) -> Iterator[McpContainer]:
    running = McpContainer(
        container_name(runid, label), image.run_reference, env, runid=runid, network="none"
    )
    try:
        yield running
    finally:
        assert running.close() == [], "the container outlived its test"


def without(*keys: str) -> dict[str, str]:
    return {key: value for key, value in BASE.items() if key not in keys}


@pytest.mark.parametrize(
    "missing",
    ["GRAMPS_BASE_URL", "GRAMPS_USERNAME", "GRAMPS_PASSWORD"],
    ids=lambda name: name.removeprefix("GRAMPS_").lower(),
)
def test_a_missing_required_variable_kills_the_server_before_the_handshake(
    mcp_image: ImageRef, e2e_runid: str, missing: str
) -> None:
    """`main()` reads these with `os.environ[...]`, so the process dies on the first line.

    Asserted as a *named* death rather than a timeout: the harness learned to tell those apart
    precisely because this failure shape and a broken image produce the same silence, and a
    60-second "timed out" points at everything except the environment.
    """
    with container(mcp_image, e2e_runid, f"no-{missing[7:9].lower()}", without(missing)) as mcp:
        with pytest.raises(ProbeError, match="exited with code") as raised:
            mcp.start()

    assert missing in str(raised.value), "the server names the variable it could not find"


def test_without_a_backup_directory_the_file_tools_exist_and_say_why(
    mcp_image: ImageRef, e2e_runid: str
) -> None:
    """Registration does not depend on the mount, and it should not.

    A tool that vanishes when a variable is unset is a tool the model cannot ask about: it
    would report "this server cannot export", which is a different — and wrong — statement
    from "this server was not given a directory to export into".
    """
    with container(mcp_image, e2e_runid, "no-backup", BASE) as mcp:
        served = tool_contract.from_wire(tool_contract.read_pages(mcp.list_tools))
        export = mcp.call("gramps_export_tree", {})
        write = mcp.call("gramps_import_file", {"filename": "anything.gramps"})

    assert {"gramps_export_tree", "gramps_import_file"} <= set(served)
    assert export.is_error is True
    assert "GRAMPS_BACKUP_DIR is not configured" in export.text
    assert write.is_error is True
    assert "GRAMPS_BACKUP_DIR is not configured" in write.text


def test_an_unreachable_instance_answers_as_a_tool_error_not_as_a_hang(
    mcp_image: ImageRef, e2e_runid: str
) -> None:
    """The client is lazy, so this is the first moment the base URL is used at all.

    `--network none` makes the name unresolvable, which is the fast, deterministic version of
    "the instance is down". What must not happen is silence: a call that never returns is a
    client that never recovers.
    """
    with container(mcp_image, e2e_runid, "unroutable", BASE) as mcp:
        answer = mcp.call("gramps_get_object_counts", {}, timeout=90)

    assert answer.is_error is True
    assert "gwe2e-nowhere" in answer.text


@pytest.mark.parametrize("value", ["0", "true", "TRUE", "yes", "on", ""])
def test_only_the_exact_string_one_arms_the_destructive_tools(
    mcp_image: ImageRef, e2e_runid: str, value: str
) -> None:
    """D11's fail-open probe over the wire: pydantic coerces these, `os.environ` must not.

    `"true"`, `"yes"` and `"on"` are all `True` to pydantic 2.13.4 (measured), so a gate that
    ever moved to a coercing reader would arm a public deployment that asked for the opposite.
    """
    label = f"gate-{value or 'empty'}"
    with container(
        mcp_image, e2e_runid, label, {**BASE, "GRAMPS_ENABLE_DESTRUCTIVE": value}
    ) as mcp:
        served = tool_contract.from_wire(tool_contract.read_pages(mcp.list_tools))

    assert len(served) == TOOLS_WITHOUT_DESTRUCTIVE
    assert not [name for name in served if name.startswith(tool_contract.DESTRUCTIVE_PREFIX)]


def test_the_exact_string_one_does_arm_them(mcp_image: ImageRef, e2e_runid: str) -> None:
    """The control for the probe above: a gate that never registers anything is not a gate."""
    with container(
        mcp_image, e2e_runid, "gate-one", {**BASE, "GRAMPS_ENABLE_DESTRUCTIVE": "1"}
    ) as mcp:
        served = tool_contract.from_wire(tool_contract.read_pages(mcp.list_tools))

    assert len(served) == TOOLS_WITH_DESTRUCTIVE
