# Generated by OrchestKit Claude Plugin
# Created: 2026-08-01

"""The tool contract, read three ways and pinned once (plan T3.1). No Docker, no LLM, ~1 s.

Stage 2 hands a real model nothing but this contract and grades what it does with it. That
makes an unnoticed change to a name, a schema or a docstring indistinguishable from a model
that got worse — so the contract is a snapshot, and a change to it has to be a diff somebody
approved rather than a number that drifted.

Three readings, because they fail differently:

* the **registry** (this process, mock client) against the committed snapshot — catches any
  edit to `server.py` that changes what a client would see;
* the **source** (`ast`, never imported) against the registry — answers "is the text the model
  reads the text written in this repository", which is what makes a Stage-2 finding
  attributable to `server.py` rather than to the framework;
* the **README** against the registry — the one number the release ritual has always had to
  check by hand, and the one it has repeatedly checked too late.

The live half of this contract — that the *shipped image* serves the same list — cannot be
answered here and is `test_08_protocol.py`.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import pytest
from harness import tool_contract
from harness.tool_contract import DESTRUCTIVE_PREFIX

README = tool_contract.REPO_ROOT / "README.md"

TOOLS_WITHOUT_DESTRUCTIVE = 27
TOOLS_WITH_DESTRUCTIVE = 31


@pytest.fixture(scope="module")
def snapshot() -> dict[str, Any]:
    return tool_contract.load()


@pytest.fixture(scope="module")
def armed() -> dict[str, dict[str, Any]]:
    return tool_contract.from_registry(enable_destructive=True)


@pytest.fixture(scope="module")
def unarmed() -> dict[str, dict[str, Any]]:
    return tool_contract.from_registry(enable_destructive=False)


def test_the_registry_serves_exactly_what_the_snapshot_pins(
    armed: dict[str, dict[str, Any]], snapshot: dict[str, Any]
) -> None:
    """Names, descriptions, input schemas and output schemas — byte for byte.

    Regenerating the snapshot is a deliberate act (`python -m harness.tool_contract`), not a
    way to make this green.
    """
    assert armed == snapshot["tools"]


def test_the_snapshot_records_both_gates_from_one_reading(
    unarmed: dict[str, dict[str, Any]], snapshot: dict[str, Any]
) -> None:
    assert sorted(unarmed) == snapshot["gate_off"]


def test_the_gate_adds_the_destructive_tools_and_changes_nothing_else(
    armed: dict[str, dict[str, Any]], unarmed: dict[str, dict[str, Any]]
) -> None:
    """The gate is structural: without the flag the tools do not exist, and nothing else moves.

    Both halves matter. A gate that also altered a docstring would be a gate that changes what
    the model sees in the *default* deployment, which is the one deployment nobody re-reads.
    """
    added = set(armed) - set(unarmed)

    assert len(unarmed) == TOOLS_WITHOUT_DESTRUCTIVE
    assert len(armed) == TOOLS_WITH_DESTRUCTIVE
    assert added == {name for name in armed if name.startswith(DESTRUCTIVE_PREFIX)}
    assert {name: armed[name] for name in unarmed} == unarmed


def test_every_description_is_the_docstring_written_in_server_py(
    armed: dict[str, dict[str, Any]],
) -> None:
    """Attribution: what the model reads must be what this repository wrote.

    Both sides are dedented — `ast.get_docstring(clean=True)` on one, `_entry` on the other —
    so this is an exact comparison of the text and a deliberate blindness to its indentation.
    The reason that blindness is not laziness is measured and written down in `_entry`.
    """
    written = tool_contract.docstrings_from_source()

    assert set(written) == set(armed), "the source parser and the registry disagree on the tools"
    for name, tool in sorted(armed.items()):
        assert tool["description"] is not None, f"{name} has no description"
        assert written[name] is not None, f"{name} has no docstring in server.py"
        assert tool["description"] == written[name], name


def test_the_source_parser_finds_the_whole_tool_set() -> None:
    """The previous test is only worth its name if the parser can fail to find something.

    A parser that returned `{}` would make the set comparison red, but one that quietly
    matched *every* nested function would make it green while asserting nothing about the
    decorator. So: the count is pinned, and a non-tool function defined in the same factory
    must not appear.
    """
    written = tool_contract.docstrings_from_source()

    assert len(written) == TOOLS_WITH_DESTRUCTIVE
    assert all(name.startswith("gramps_") for name in written)
    assert "register" not in written


def test_no_tool_reaches_the_model_without_a_docstring(armed: dict[str, dict[str, Any]]) -> None:
    """A tool whose description is empty is not "undocumented", it is unusable.

    The model chooses from the description alone; an empty one is a tool that will never be
    picked and will never be reported as missing either.
    """
    empty = [name for name, tool in armed.items() if not (tool["description"] or "").strip()]

    assert empty == []


def test_every_tool_declares_an_object_input_schema(armed: dict[str, dict[str, Any]]) -> None:
    """The schema is the other half of what the model sees, and `None` is a legal value here.

    A tool whose `inputSchema` lost its `type` still lists fine and still fails at call time,
    which in a Stage-2 run reads as "the model got the arguments wrong".
    """
    for name, tool in sorted(armed.items()):
        schema = tool["inputSchema"]
        assert isinstance(schema, dict), name
        assert schema.get("type") == "object", name
        assert isinstance(schema.get("properties"), dict), name


def _paged(pages: list[dict[str, Any]]) -> Any:
    """A `list_tools` that hands out one page per cursor, the way a paginating server would."""
    return lambda cursor: pages[0 if cursor is None else int(cursor)]


def test_the_page_walker_follows_the_cursor_to_the_end() -> None:
    """The live server answers in one page today, which makes the live assertion tautological.

    So the walk is proven here instead, against a server that does paginate: two pages, two
    tools, and a reading that stopped at the first would silently lose the tail — which is
    exactly where the destructive tools sit in the registration order.
    """
    served = [
        {"tools": [{"name": "first", "description": "a", "inputSchema": {}}], "nextCursor": "1"},
        {"tools": [{"name": "second", "description": "b", "inputSchema": {}}]},
    ]

    walked = tool_contract.read_pages(_paged(served))

    assert len(walked) == 2
    assert sorted(tool_contract.from_wire(walked)) == ["first", "second"]


def test_a_cursor_that_never_ends_fails_instead_of_hanging() -> None:
    """A hang has no failing assertion to read, and CI would kill the job with no verdict."""
    endless = [{"tools": [{"name": "t", "description": "d", "inputSchema": {}}], "nextCursor": "0"}]

    with pytest.raises(RuntimeError, match="paginating without end"):
        tool_contract.read_pages(_paged(endless), max_pages=3)


def _readme_counts(text: str) -> tuple[int, int]:
    """The two numbers the `## Tools` intro claims. A rewritten sentence is a failure here.

    Not a skip and not a default: this test exists precisely because that sentence drifts, and
    a guard that quietly stops looking when the wording changes is the drift it was meant to
    catch.
    """
    plain = re.search(r"exposes (\d+) tools", text)
    destructive = re.search(r"plus (\d+) optional destructive", text)
    assert plain and destructive, (
        "README.md no longer states its tool counts in the expected wording — "
        "update this parser deliberately, do not delete the check"
    )
    return int(plain.group(1)), int(destructive.group(1))


def test_the_readme_states_the_tool_counts_the_server_actually_registers(
    armed: dict[str, dict[str, Any]], unarmed: dict[str, dict[str, Any]], readme: Path = README
) -> None:
    """The release ritual's step 3, as a test that runs on every push instead of once a wave."""
    stated_plain, stated_destructive = _readme_counts(readme.read_text(encoding="utf-8"))

    assert stated_plain == len(unarmed)
    assert stated_destructive == len(armed) - len(unarmed)


def test_the_readme_names_every_destructive_tool_it_gates(
    armed: dict[str, dict[str, Any]], unarmed: dict[str, dict[str, Any]], readme: Path = README
) -> None:
    """A count that matches while a name is missing is the same silence, one field over."""
    text = readme.read_text(encoding="utf-8")

    for name in sorted(set(armed) - set(unarmed)):
        assert name in text, f"{name} is gated but never named in README.md"
