# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""Grading, without a model and without an instance (T2.5).

Two captures in, outcomes out — that is the whole contract, and it is why these tests cost
nothing. What is checked here is not "does the grader run" but that each kind can **fail**: a
check that cannot go red is coverage on paper, which is the failure mode this suite keeps
finding in itself (B2-B4, and the `n_skills` key that would have passed on every contaminated
run).

The two standing checks get the same treatment. `guards` had been validated as data since T2.2
and read by nobody; an emptied `guards:` was invisible. It is a graded outcome now.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest
from fixtures import stage2_records as make
from harness.docker_util import ProbeError
from stage2 import checks_record, grading, validate
from stage2.assertion_kinds import KINDS
from stage2.catalog import Assertion, UseCase, load, load_all

MARRIED, BIRTH = make.MARRIED_NAME, make.BIRTH_NAME

BEFORE = make.state(
    people=(
        make.person("I0000", "Rosalind", "Steinbrecht", alternates=((("Wendelmark"), BIRTH),)),
        make.person(
            "I0001",
            "Bertram",
            "Aschenblum",
            gender=make.MALE,
            tags=("Unbestätigt",),
            families=("h-F0000",),
        ),
        make.person("I0002", "Elvide", "Grausteen", families=("h-F0000",)),
    ),
    families=(make.family("F0000", father="I0001", mother="I0002"),),
    sources=(make.source("S0000", "Der Grippewinter", notes=("N0000",)),),
    notes=(make.note("N0000", "Im Winter 1918 starben viele."),),
    tags=(make.tag("Unbestätigt"),),
)


def use_case(*assertions: Assertion, guards: Any = None, maxdrop: Any = 0) -> UseCase:
    return UseCase(
        id="uc0",
        slug="uc00-probe",
        tier=1,
        prompt="p",
        primary=("gramps_add_person",),
        decoys=(),
        secondary=(),
        subjects={
            "target": {"namespace": "people", "first_name": "Rosalind", "surname": "Steinbrecht"},
            "husband": {"namespace": "people", "first_name": "Bertram", "surname": "Aschenblum"},
            "household": {"namespace": "families", "members": ["husband", "wife"]},
            "wife": {"namespace": "people", "first_name": "Elvide", "surname": "Grausteen"},
            "article": {"namespace": "sources", "title": "Der Grippewinter"},
        },
        guards={"people": [], "families": [], "sources": []} if guards is None else guards,
        maxdrop=maxdrop,
        assertions=assertions,
        waivers=(),
        path=make.__file__,  # type: ignore[arg-type]
    )


def graded(assertion: Assertion, after: Any, **kwargs: Any) -> grading.Outcome:
    case = use_case(assertion, guards=kwargs.pop("guards", None), maxdrop=kwargs.pop("maxdrop", 0))
    evidence = grading.evidence_for(case, BEFORE, after, **kwargs)
    return grading.grade(case, evidence)[0]


def test_every_kind_the_catalog_allows_has_an_implementation() -> None:
    """The registry is a contract in both directions: T2.5 answers for every name in it."""
    assert set(grading.CHECKS) == set(KINDS)


def test_every_field_the_27_use_cases_name_is_one_the_grader_can_read() -> None:
    """`validate.py` checks kinds and required parameters; nobody checked the field *names*.

    A `fields: {sur_name: …}` would load, validate and grade — against a reader that does not
    exist. This is the last place the catalog and the grader could disagree in silence.
    """
    known = set(checks_record.PERSON_FIELDS) | set(checks_record.SOURCE_FIELDS)
    used = {
        str(field)
        for case in load_all().values()
        for assertion in case.assertions
        for field in (assertion.params.get("fields") or {})
    }

    assert used <= known, f"the catalog names {sorted(used - known)}, which nothing can read"


def test_counts_passes_when_nothing_moved() -> None:
    outcome = graded(Assertion("a", "counts", {"deltas": {}}), BEFORE)

    assert outcome.passed and outcome.grade == "A"


def test_counts_fails_and_says_both_sides() -> None:
    after = make.state(
        people=(*BEFORE.of("people"), make.person("I0003", "Neu", "Person")),
        families=BEFORE.of("families"),
        sources=BEFORE.of("sources"),
        notes=BEFORE.of("notes"),
        tags=BEFORE.of("tags"),
    )

    outcome = graded(Assertion("a", "counts", {"deltas": {}}), after)

    assert not outcome.passed
    assert "people" in outcome.detail


def test_created_reads_the_record_that_actually_appeared() -> None:
    after = _plus(make.person("I0003", "Wendelmark", "Sorge"))
    assertion = Assertion(
        "a", "created", {"namespace": "people", "count": 1, "fields": {"first_name": "Wendelmark"}}
    )

    assert graded(assertion, after).passed


def test_created_fails_when_the_new_record_carries_other_values() -> None:
    after = _plus(make.person("I0003", "Wendelmar", "Sorge"))
    assertion = Assertion(
        "a", "created", {"namespace": "people", "count": 1, "fields": {"first_name": "Wendelmark"}}
    )

    assert not graded(assertion, after).passed


def test_a_new_subject_comes_from_the_movement_not_from_a_report() -> None:
    after = _plus(make.person("I0003", "Wendelmark", "Sorge"))
    assertion = Assertion("a", "person", {"subject": "new:people", "fields": {"surname": "Sorge"}})

    assert graded(assertion, after).passed


def test_a_new_subject_with_nothing_new_fails_the_assertion() -> None:
    """A create that did not happen is a finding, not a crash — it must not abort the sweep."""
    outcome = graded(
        Assertion("a", "person", {"subject": "new:people", "fields": {"surname": "Sorge"}}), BEFORE
    )

    assert not outcome.passed
    assert "0 did" in outcome.detail


def test_removed_names_the_set_not_the_count() -> None:
    after = _without_family()
    assertion = Assertion("a", "removed", {"namespace": "families", "subjects": ["household"]})

    assert graded(assertion, after, maxdrop=1).passed


def test_removed_fails_when_the_wrong_record_went() -> None:
    after = make.state(
        people=BEFORE.of("people")[:2],
        families=BEFORE.of("families"),
        sources=BEFORE.of("sources"),
        notes=BEFORE.of("notes"),
        tags=BEFORE.of("tags"),
    )
    assertion = Assertion("a", "removed", {"namespace": "people", "subjects": ["husband"]})

    outcome = graded(assertion, after, maxdrop=1)

    assert not outcome.passed and "I0002" in outcome.detail


def test_person_reads_the_friendly_field_names() -> None:
    after = _replacing(make.person("I0001", "Bertram", "Aschenblum", gender=make.FEMALE))
    assertion = Assertion("a", "person", {"subject": "husband", "fields": {"gender": 0}})

    assert graded(assertion, after, guards={"people": ["husband"]}).passed


def test_a_field_nobody_can_read_is_a_failure_not_a_skip() -> None:
    assertion = Assertion("a", "person", {"subject": "husband", "fields": {"sur_name": "x"}})

    outcome = graded(assertion, BEFORE)

    assert not outcome.passed and "sur_name" in outcome.detail


def test_an_unreadable_field_fails_even_when_the_expectation_is_empty() -> None:
    """The sharp version: a `.get(field)` fallback would compare `None` to `None` and pass —
    a misspelt field name asserting nothing while looking like coverage."""
    assertion = Assertion("a", "person", {"subject": "husband", "fields": {"sur_name": None}})

    assert not graded(assertion, BEFORE).passed


def test_a_subject_the_call_removes_still_resolves() -> None:
    """Resolution runs against the *before* capture — uc15 selects a household by the child the
    call is about to take out of it, and an after-resolution would match nothing."""
    after = make.state(
        people=BEFORE.of("people")[:2],
        families=BEFORE.of("families"),
        sources=BEFORE.of("sources"),
        notes=BEFORE.of("notes"),
        tags=BEFORE.of("tags"),
    )
    assertion = Assertion("a", "removed", {"namespace": "people", "subjects": ["wife"]})

    assert graded(assertion, after, maxdrop=1).passed


def test_alternates_counts_and_matches_pairs() -> None:
    swapped = make.person(
        "I0000", "Rosalind", "Wendelmark", name_type=BIRTH, alternates=((("Steinbrecht"), MARRIED),)
    )
    assertion = Assertion(
        "a",
        "alternates",
        {
            "subject": "target",
            "count": 1,
            "contains": [{"surname": "Steinbrecht", "name_type": MARRIED}],
        },
    )

    assert graded(assertion, _replacing(swapped), guards={"people": ["target"]}).passed


def test_an_alternate_may_be_named_by_surname_alone() -> None:
    """uc4 omits `name_type` on purpose, and the first live run proved it right: the model's
    route left the old name as an **"Also Known As"**, a type the use case must not pin — that
    choice belongs to the product, and asserting it would be asserting the answer."""
    kept = make.person(
        "I0000", "Rosalind", "Steinbrecht", alternates=((("Wendelmark"), "Also Known As"),)
    )
    assertion = Assertion(
        "a", "alternates", {"subject": "target", "contains": [{"surname": "Wendelmark"}]}
    )

    assert graded(assertion, _replacing(kept), guards={"people": ["target"]}).passed


def test_a_misspelt_key_inside_contains_is_caught_before_any_money_is_spent(
    tmp_path: Path,
) -> None:
    """The lint is where this belongs. Catching it in the grader means the model run that was
    being graded has already been paid for."""
    path = tmp_path / "uc01-probe.yaml"
    path.write_text(
        "id: uc1\ntier: 1\nprompt: Please correct her record.\n"
        "primary: [gramps_add_alternate_name]\n"
        "subjects:\n  target: {namespace: people, first_name: Rosalind, surname: Steinbrecht}\n"
        "guards: {people: [target]}\nmaxdrop: 0\n"
        "assertions:\n  - id: uc1/alt\n    kind: alternates\n    subject: target\n"
        "    contains: [{sur_name: Wendelmark}]\n",
        encoding="utf-8",
    )
    case = load(path)

    found = validate.problems({case.id: case}, {"gramps_add_alternate_name"}, BEFORE.tree)

    assert any("sur_name" in problem for problem in found), found


def test_an_unknown_key_inside_contains_is_a_failure_not_a_crash() -> None:
    """It used to be a `KeyError` mid-sweep: the harness died with a traceback after the model
    run had already been paid for."""
    assertion = Assertion(
        "a", "alternates", {"subject": "target", "contains": [{"sur_name": "Wendelmark"}]}
    )

    outcome = graded(assertion, BEFORE)

    assert not outcome.passed and "sur_name" in outcome.detail


def test_alternates_catches_the_extra_name_a_wrong_route_leaves_behind() -> None:
    """uc13's whole point: set-the-surname-then-add-the-old-one grows a second alternate."""
    wrong = make.person(
        "I0000",
        "Rosalind",
        "Wendelmark",
        alternates=((("Wendelmark"), BIRTH), (("Steinbrecht"), MARRIED)),
    )
    assertion = Assertion("a", "alternates", {"subject": "target", "count": 1})

    assert not graded(assertion, _replacing(wrong), guards={"people": ["target"]}).passed


def test_family_reads_slots_and_children_as_subjects() -> None:
    after = _replacing(make.family("F0000", father="I0001", mother="I0002", children=("I0000",)))
    assertion = Assertion(
        "a", "family", {"subject": "household", "father": "husband", "children": ["target"]}
    )

    assert graded(assertion, after, guards={"families": ["household"]}).passed


def test_family_fails_when_somebody_else_sits_in_the_slot() -> None:
    after = _replacing(make.family("F0000", father="I0000", mother="I0002"))
    assertion = Assertion("a", "family", {"subject": "household", "father": "husband"})

    assert not graded(assertion, after, guards={"families": ["household"]}).passed


def test_tag_separates_the_marker_from_the_tag_object() -> None:
    stripped = make.person("I0001", "Bertram", "Aschenblum", gender=make.MALE)
    assertion = Assertion(
        "a",
        "tag",
        {"subject": "husband", "tag": "Unbestätigt", "present": False, "tag_survives": True},
    )

    assert graded(assertion, _replacing(stripped), guards={"people": ["husband"]}).passed


def test_tag_fails_when_the_marker_is_still_on_the_person() -> None:
    assertion = Assertion(
        "a", "tag", {"subject": "husband", "tag": "Unbestätigt", "present": False}
    )

    assert not graded(assertion, BEFORE).passed


def test_note_body_demands_a_byte_preserving_edit() -> None:
    after = _replacing(make.note("N0000", "Im Winter 1919 starben viele."))
    assertion = Assertion(
        "a", "note_body", {"subject": "article", "replaces": {"from": "1918", "to": "1919"}}
    )

    assert graded(assertion, after).passed


def test_note_body_fails_when_the_model_rewrote_the_article() -> None:
    after = _replacing(make.note("N0000", "Der Winter 1919 forderte viele Opfer."))
    assertion = Assertion(
        "a", "note_body", {"subject": "article", "replaces": {"from": "1918", "to": "1919"}}
    )

    assert not graded(assertion, after).passed


def test_source_reads_the_title_a_prompt_asked_for() -> None:
    after = _replacing(make.source("S0000", "Grippewinter 1918", notes=("N0000",)))
    assertion = Assertion(
        "a", "source", {"subject": "article", "fields": {"title": "Grippewinter 1918"}}
    )

    assert graded(assertion, after, guards={"sources": ["article"]}).passed


def test_tree_unchanged_catches_a_read_tool_that_wrote() -> None:
    after = _replacing(make.person("I0001", "Bertrand", "Aschenblum", gender=make.MALE))

    outcome = graded(Assertion("a", "tree_unchanged", {}), after)

    assert not outcome.passed and "people/I0001" in outcome.detail


def test_tree_unchanged_passes_on_a_tree_nobody_touched() -> None:
    assert graded(Assertion("a", "tree_unchanged", {}), BEFORE).passed


def test_tree_empty_is_only_true_when_every_namespace_is_zero() -> None:
    assert graded(Assertion("a", "tree_empty", {}), make.state(), maxdrop="everything").passed
    assert not graded(Assertion("a", "tree_empty", {}), BEFORE).passed


def test_names_added_matches_on_names_because_an_import_renumbers() -> None:
    after = _plus(make.person("I0003", "Sigrun", "Aschenblum"))
    assertion = Assertion(
        "a", "names_added", {"pairs": [{"first_name": "Sigrun", "surname": "Aschenblum"}]}
    )

    assert graded(assertion, after).passed


def test_backup_file_counts_what_appeared_during_the_call() -> None:
    assertion = Assertion("a", "backup_file", {"count": 1, "extension": ".gramps", "min_bytes": 10})
    entry = grading.BackupEntry(name="tree.gramps", size=1159, text="")

    assert graded(assertion, BEFORE, backup=(entry,)).passed
    assert not graded(assertion, BEFORE, backup=()).passed


def test_the_tool_log_is_class_b_and_never_gates() -> None:
    assertion = Assertion("a", "tool_log", {"used_any": ["gramps_list_people"]})

    outcome = graded(assertion, BEFORE, calls=("gramps_get_person",))

    assert not outcome.passed and outcome.grade == "B"
    assert grading.failures([outcome]) == []


def test_guards_fire_when_somebody_outside_the_use_case_was_rewritten() -> None:
    """The check that had no consumer until now: an emptied `guards:` used to be invisible."""
    case = use_case(Assertion("a", "counts", {"deltas": {}}), guards={"people": ["target"]})
    after = _replacing(make.person("I0001", "Bertrand", "Aschenblum", gender=make.MALE))

    outcomes = grading.grade(case, grading.evidence_for(case, BEFORE, after))
    guards = next(outcome for outcome in outcomes if outcome.kind == "guards")

    assert not guards.passed and "I0001" in guards.detail


def test_guards_allow_the_declared_subject_to_change() -> None:
    case = use_case(Assertion("a", "counts", {"deltas": {}}), guards={"people": ["husband"]})
    after = _replacing(make.person("I0001", "Bertrand", "Aschenblum", gender=make.MALE))

    outcomes = grading.grade(case, grading.evidence_for(case, BEFORE, after))

    assert all(outcome.passed for outcome in outcomes)


def test_a_family_change_does_not_red_its_spouses() -> None:
    """`family_list` is deliberately outside the person signature — uc16 deletes a household and
    both spouses' membership moves with it, which is the call working, not a stray write."""
    case = use_case(Assertion("a", "counts", {"deltas": {"families": -1}}), maxdrop=1)
    after = _without_family()

    outcomes = grading.grade(case, grading.evidence_for(case, BEFORE, after))

    assert all(outcome.passed for outcome in outcomes), [o.detail for o in outcomes if not o.passed]


def test_maxdrop_is_per_namespace_and_says_which() -> None:
    case = use_case(Assertion("a", "counts", {"deltas": {"people": -2}}), maxdrop=1)
    after = make.state(
        people=BEFORE.of("people")[:1],
        families=BEFORE.of("families"),
        sources=BEFORE.of("sources"),
        notes=BEFORE.of("notes"),
        tags=BEFORE.of("tags"),
    )

    outcomes = grading.grade(case, grading.evidence_for(case, BEFORE, after))
    maxdrop = next(outcome for outcome in outcomes if outcome.kind == "maxdrop")

    assert not maxdrop.passed and "people" in maxdrop.detail


def test_everything_is_the_wipe_and_not_a_wildcard_elsewhere() -> None:
    case = use_case(Assertion("a", "tree_empty", {}), guards="everything", maxdrop="everything")

    outcomes = grading.grade(case, grading.evidence_for(case, BEFORE, make.state()))

    assert all(outcome.passed for outcome in outcomes)


def test_a_subject_that_no_longer_resolves_stops_the_run() -> None:
    """A fixture that moved is a harness fault, not a product finding — it must not be graded."""
    case = use_case(Assertion("a", "counts", {"deltas": {}}))

    with pytest.raises(ProbeError, match="target"):
        grading.evidence_for(case, make.state(), make.state())


def _plus(record: dict[str, Any]) -> Any:
    return make.state(
        people=(*BEFORE.of("people"), record),
        families=BEFORE.of("families"),
        sources=BEFORE.of("sources"),
        notes=BEFORE.of("notes"),
        tags=BEFORE.of("tags"),
    )


def _replacing(record: dict[str, Any]) -> Any:
    namespaces = {}
    for namespace in ("people", "families", "sources", "notes", "tags"):
        namespaces[namespace] = tuple(
            record if existing["handle"] == record["handle"] else existing
            for existing in BEFORE.of(namespace)
        )
    return make.state(**namespaces)


def _without_family() -> Any:
    """The household gone — and both spouses' `family_list` gone with it, as the server does."""
    return make.state(
        people=tuple(
            {**person, "family_list": []} if person["family_list"] else person
            for person in BEFORE.of("people")
        ),
        families=(),
        sources=BEFORE.of("sources"),
        notes=BEFORE.of("notes"),
        tags=BEFORE.of("tags"),
    )
