# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""A write has to name what the tree must say afterwards — whatever it reports (B5, B6). No Docker.

D16's re-read hung on the *report shape*: `person` and `bulk` had to name a person, and the five
tools that report nothing at all were held to nothing at all. `unguarded` returned from
`assert_self_report` before its first check, so removing the family PUT from
`add_child_to_family` left the whole suite green.

The mechanism was never missing — `expect_person` worked for any shape. The obligation was. And
the obligation could not simply be extended, because it only ever reached `people`: a family, a
note or a source has no `expect_person` to name. So the expectation is now
`{namespace: {gramps_id: {path: value}}}` over `by_gramps_id`, `expect_person` is the sugar for
the common case, and the one tool whose effect is genuinely not in the tree says so out loud.

The same re-read is what lets `assert_refusal` mean what its docstring says: counts and identity
cannot see a field written in place before the raise, and that is the worst refusal there is.
"""

from __future__ import annotations

from typing import Any

import pytest
from harness.assertions import assert_guarded_write, assert_refusal
from harness.docker_util import ProbeError
from stubs.fake_tree import FakeRest, FakeTree
from stubs.fake_write_shapes import BLOG_POST, BODY_NOTE, FakeWriteMcp

CHILD = "I0002"
FAMILY = "F0000"
CHILD_REF = "child_ref_list.0.ref"
BODY = "text.string"
TITLE = "title"


@pytest.fixture
def tree() -> FakeTree:
    return FakeTree()


@pytest.fixture
def rest(tree: FakeTree) -> FakeRest:
    return FakeRest(tree)


@pytest.fixture
def mcp(tree: FakeTree) -> FakeWriteMcp:
    return FakeWriteMcp(tree)


def add_child(rest: FakeRest, mcp: FakeWriteMcp, **kwargs: Any) -> Any:
    return assert_guarded_write(
        rest,
        mcp,
        "gramps_add_child_to_family",
        {"family_id": FAMILY, "child_id": CHILD},
        expect_delta={},
        self_report="unguarded",
        **kwargs,
    )


FAMILY_GAINED_THE_CHILD = {"families": {FAMILY: {CHILD_REF: f"h-{CHILD}"}}}


# -- B5: the obligation follows the write, not the report shape ------------------------


def test_an_unguarded_write_without_a_record_expectation_is_refused(
    rest: FakeRest, mcp: FakeWriteMcp
) -> None:
    """A usage error, like the D16 gate it generalises. This shape reports `{family_id,
    child_id}` — the arguments, echoed — so without a re-read nothing is checked at all."""
    with pytest.raises(ProbeError, match="expect_record"):
        add_child(rest, mcp)


def test_an_unguarded_write_is_certified_by_the_record_it_names(
    rest: FakeRest, mcp: FakeWriteMcp
) -> None:
    """The re-read reaches a namespace that is not `people`, which is what `expect_person`
    structurally could not do."""
    add_child(rest, mcp, expect_record=FAMILY_GAINED_THE_CHILD)

    assert rest.tree.namespaces["families"][FAMILY]["child_ref_list"] == [{"ref": f"h-{CHILD}"}]


def test_an_unguarded_write_that_never_reached_the_tree_is_caught(
    rest: FakeRest, mcp: FakeWriteMcp
) -> None:
    """D16's mutation, on the family side: the PUT is gone and the report cannot tell."""
    mcp.skip_family_put = True

    with pytest.raises(AssertionError, match=CHILD_REF):
        add_child(rest, mcp, expect_record=FAMILY_GAINED_THE_CHILD)


def test_the_report_of_that_same_write_is_unchanged(mcp: FakeWriteMcp) -> None:
    """Why the obligation had to move. The report is the arguments echoed back, so it is
    identical whether or not the write happened."""
    mcp.skip_family_put = True

    honest = FakeWriteMcp(FakeTree()).call(
        "gramps_add_child_to_family", {"family_id": FAMILY, "child_id": CHILD}
    )
    silent = mcp.call("gramps_add_child_to_family", {"family_id": FAMILY, "child_id": CHILD})

    assert silent.text == honest.text
    assert mcp.tree.namespaces["families"][FAMILY]["child_ref_list"] == [], "premise: nothing wrote"


def test_an_unguarded_tool_may_claim_a_delta_the_oracle_corroborates(
    rest: FakeRest, mcp: FakeWriteMcp
) -> None:
    """`update_blog_post(body=…)` on a post with no note creates one, and the old gate refused
    any delta for this shape — so the tool had no legal call form at all. The delta never came
    from the tool's report in the first place; it comes from the REST snapshots around it."""
    written = assert_guarded_write(
        rest,
        mcp,
        "gramps_update_blog_post",
        {"gramps_id": BLOG_POST, "body": "Hallo"},
        expect_delta={"notes": 1},
        self_report="unguarded",
        expect_record={"notes": {BODY_NOTE: {BODY: "Hallo"}}},
    )

    assert written.added == {"notes": [BODY_NOTE]}


def test_a_tool_whose_effect_is_outside_the_tree_declares_that(
    rest: FakeRest, mcp: FakeWriteMcp
) -> None:
    """The over-strictness guard, and the escape hatch's whole purpose: `export_tree` writes a
    file. Demanding a tree re-read of it would be a false red, and leaving it as `unguarded`
    would let every genuinely unchecked call hide behind the same word. The test still owes the
    file assertion — `BackupDir.assert_export` — which is why the name says so."""
    written = assert_guarded_write(
        rest,
        mcp,
        "gramps_export_tree",
        {"filename": "acceptance.gramps"},
        expect_delta={},
        self_report="external",
    )

    assert written.payload["bytes"] > 0


def test_a_hollow_expectation_is_refused_in_every_namespace(
    rest: FakeRest, mcp: FakeWriteMcp
) -> None:
    """B2's rule had to travel with the parameter, not stay behind with `expect_person`.
    `{"F0000": {}}` opens the gate and then compares nothing, exactly as `{"I0001": {}}` did —
    and a namespace-wide expectation is the natural place to write one by accident."""
    with pytest.raises(ProbeError, match="names no field"):
        add_child(rest, mcp, expect_record={"families": {FAMILY: {}}})


def test_a_shape_this_module_does_not_know_is_refused(rest: FakeRest, mcp: FakeWriteMcp) -> None:
    """`SelfReport` is a `Literal`, which is a hint to a type checker and nothing at runtime.
    A misspelt shape matched no branch of the cross-check and was therefore *silent* — the same
    defect as B2-B4, one typo away, and it survived a mutation probe of everything else."""
    with pytest.raises(ProbeError, match="persn"):
        assert_guarded_write(
            rest,
            mcp,
            "gramps_set_first_name",
            {"gramps_id": "I0001", "first_name": "Reinhold"},
            expect_delta={},
            self_report="persn",  # type: ignore[arg-type]
            expect_person={"I0001": {"primary_name.first_name": "Reinhold"}},
        )


def test_naming_a_person_twice_over_is_refused(rest: FakeRest, mcp: FakeWriteMcp) -> None:
    """`expect_person` is sugar for `expect_record["people"]`. Given both, the helper would have
    to guess which wins, and a silently dropped expectation checks nothing."""
    with pytest.raises(ProbeError, match="expect_person"):
        assert_guarded_write(
            rest,
            mcp,
            "gramps_set_first_name",
            {"gramps_id": "I0001", "first_name": "Reinhold"},
            expect_delta={},
            self_report="person",
            expect_person={"I0001": {"primary_name.first_name": "Reinhold"}},
            expect_record={"people": {"I0001": {"gender": 1}}},
        )


# -- B6: a refusal that already wrote is the worst one ---------------------------------


def test_a_refusal_that_wrote_in_place_before_raising_is_caught(
    rest: FakeRest, mcp: FakeWriteMcp
) -> None:
    """No count moves and no object changes identity, so counts and fingerprint both agree the
    tree stood still. Only re-reading the named leaf disagrees."""
    mcp.write_then_refuse = True

    with pytest.raises(AssertionError, match=TITLE):
        assert_refusal(
            rest,
            mcp,
            "gramps_delete_blog_post",
            {"gramps_id": BLOG_POST, "title": "Überschrieben"},
            contains="delete_blog_post requires confirm=True",
            expect_record={"sources": {BLOG_POST: {TITLE: "Blog"}}},
        )


def test_a_clean_refusal_passes_that_same_re_read(rest: FakeRest, mcp: FakeWriteMcp) -> None:
    """The over-strictness guard: the shipped order validates first, so the honest refusal has
    to stay green under exactly the expectation that catches the leak."""
    assert_refusal(
        rest,
        mcp,
        "gramps_delete_blog_post",
        {"gramps_id": BLOG_POST, "title": "Überschrieben"},
        contains="delete_blog_post requires confirm=True",
        expect_record={"sources": {BLOG_POST: {TITLE: "Blog"}}},
    )
