# Generated by OrchestKit Claude Plugin
# Created: 2026-08-02

"""The people/names tools against a live server — the cases a mock cannot decide. Needs Docker.

Selected in `.claude/worknotes/e2e-suite/phase-4/triage-product-risk.md` (13 of the matrix's 48).
The criterion was not coverage but *decidability*: a case belongs here only if the answer lives in
the server's behaviour rather than in our Python, because `tests/test_gramps_client.py` mocks the
API away and can only ever confirm the body the product built.

Every subject is chosen **by shape** off `cast`, never by id literal — `test_00_id_literals.py`
enforces that, and it enforces it because C4 renumbered the tree under a literal written the day
before.
"""

from __future__ import annotations

import pytest
from fixtures import cast
from harness.assertions import assert_guarded_write, assert_refusal, payload_list

pytestmark = pytest.mark.gramps

# Every list-shaped field a person carries, as measured off a live record. The pin below asserts
# all of them at once, so a field added upstream shows up as a new key rather than as silence.
REFERENCE_LISTS = (
    "family_list",
    "parent_family_list",
    "event_ref_list",
    "note_list",
    "birth_ref_index",
    "tag_list",
    "person_ref_list",
    "citation_list",
    "attribute_list",
    "media_list",
    "urls",
    "lds_ord_list",
    "address_list",
)


def _parents_and_children() -> tuple[set[str], set[str]]:
    spouses = {slot for f in cast.FAMILIES for slot in (f["father"], f["mother"]) if slot}
    children = {child for f in cast.FAMILIES for child in f["children"]}
    return spouses, children


def rooted_person() -> str:
    """Somebody who is both a spouse and a child, so both reverse lists are non-empty.

    A freshly created person has neither, which is what makes the pin below vacuous on one — the
    reason the matrix's own subject choice was wrong.
    """
    spouses, children = _parents_and_children()
    return sorted(spouses & children)[0]


def loose_person() -> str:
    spouses, children = _parents_and_children()
    return sorted({p["gramps_id"] for p in cast.PEOPLE} - spouses - children)[0]


def person_with_an_alternate_name() -> dict:
    return next(p for p in cast.PEOPLE if p.get("alternate_names"))


def largest_surname_group() -> tuple[str, list[str]]:
    counts: dict[str, list[str]] = {}
    for person in cast.PEOPLE:
        counts.setdefault(person["surname"], []).append(person["gramps_id"])
    surname = max(counts, key=lambda key: len(counts[key]))
    return surname, sorted(counts[surname])


def refs_of(rest, gramps_id: str) -> dict:
    person = rest.person(gramps_id)
    return {key: person.get(key, "<<ABSENT>>") for key in REFERENCE_LISTS}


class TestAFieldWriteLeavesTheRestOfTheRecordStanding:
    """A regression pin, and it is labelled one deliberately.

    Every field write is a read-modify-write: the product reads a person from the *collection*
    projection `/api/people/?gramps_id=` (`gramps_client.py:620`) and PUTs that same dict back as
    the whole person (`:681`). The server does not merge — `observed.json::u5_put_semantics`
    measured that a partial body answers 200 and blanks every omitted field. So if the collection
    projection were ever narrower than the object, every single-field edit would silently destroy
    the difference, `object_counts` would not move, and no mocked test could see it: on the update
    path the body comes from the server, and a mock returns whatever the test author put in it.

    It is not true today. `mutation-probes/probe_projection_width.py` measured both projections
    byte-identical in all three namespaces the product treats this way. That is exactly why this
    is a pin: it costs one call and it is the only thing in the suite that would notice the day
    the API narrows a projection. Do not read it as a discovery.
    """

    def test_setting_a_surname_touches_the_surname_and_nothing_else(self, seeded_tree) -> None:
        subject = rooted_person()
        before = refs_of(seeded_tree.rest, subject)
        assert before["family_list"] and before["parent_family_list"], (
            f"{subject} was chosen to have both reverse lists — without them this pin is vacuous"
        )

        assert_guarded_write(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_set_surname",
            {"gramps_id": subject, "surname": "Umgehängt"},
            expect_delta={},
            self_report="person",
            expect_person={subject: {"primary_name.surname_list.0.surname": "Umgehängt"}},
        )

        assert refs_of(seeded_tree.rest, subject) == before

    def test_the_name_type_survives_the_round_trip_as_the_server_returns_it(
        self, seeded_tree
    ) -> None:
        """The product writes a bare string (`gramps_client.py:269`); `cast.NAME_TYPES` records
        what comes back. If the server ever normalises a NameType differently, every assertion in
        this suite naming `Married Name` moves at once, and this is where it surfaces first."""
        subject = loose_person()
        wanted = cast.NAME_TYPES["primary"]

        assert_guarded_write(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_set_surname",
            {"gramps_id": subject, "surname": "Grünwalder", "name_type": wanted},
            expect_delta={},
            self_report="person",
            expect_person={
                subject: {
                    "primary_name.surname_list.0.surname": "Grünwalder",
                    "primary_name.type": wanted,
                }
            },
        )

        assert seeded_tree.rest.person(subject)["primary_name"]["type"] == wanted

    def test_swapping_the_primary_name_exchanges_whole_name_records(self, seeded_tree) -> None:
        """`swap_primary_name` is the one write tool no committed test has ever driven live."""
        subject = person_with_an_alternate_name()
        gramps_id = subject["gramps_id"]
        alternate = subject["alternate_names"][0]

        assert_guarded_write(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_swap_primary_name",
            {"gramps_id": gramps_id, "alt_index": 0},
            expect_delta={},
            self_report="person",
            expect_person={
                gramps_id: {
                    "primary_name.surname_list.0.surname": alternate["surname"],
                    "alternate_names.0.surname_list.0.surname": subject["surname"],
                }
            },
        )

        person = seeded_tree.rest.person(gramps_id)
        assert person["primary_name"]["type"] == cast.NAME_TYPES["alternate"]
        assert person["alternate_names"][0]["type"] == cast.NAME_TYPES["primary"]

    def test_a_bulk_write_applies_every_item_under_one_count_guard(self, seeded_tree) -> None:
        """`_bulk_write` is best-effort by design and *reports* its guard instead of raising
        (`gramps_client.py:714-743`). A per-item write that silently no-ops moves no count, so the
        report is not evidence — `expect_person` has to name every id, and `gate.py` refuses the
        call if it does not."""
        subjects = sorted(p["gramps_id"] for p in cast.PEOPLE if p["gender"] == 2)[:3]
        items = [{"gramps_id": gramps_id, "gender": 1} for gramps_id in subjects]

        written = assert_guarded_write(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_set_gender_bulk",
            {"items": items},
            expect_delta={},
            self_report="bulk",
            expect_person={gramps_id: {"gender": 1} for gramps_id in subjects},
        )

        assert written.payload["count_guard_ok"] is True
        assert written.payload["errors"] == []

    def test_adding_a_person_with_a_birth_year_and_a_note_makes_all_three_objects(
        self, seeded_tree
    ) -> None:
        """The only live exercise of `_create_note` and `_create_birth_event`. Each is read back
        out of a transaction envelope (`_create_object`, `:673-678`), a shape the mocked suite
        scripts rather than tests. `tags` is absent from the delta on purpose: `Unbestätigt`
        already exists, so the correct movement is zero and a duplicate-tag regression reds."""
        written = assert_guarded_write(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_add_person",
            {
                "first_name": "Notburga",
                "surname": "Immergrün",
                "gender": 0,
                "birth_year": 1887,
                "note": "Angelegt von der Stufe-1-Matrix.",
            },
            expect_delta={"people": 1, "events": 1, "notes": 1},
            self_report="id",
            id_namespace="people",
        )

        created = seeded_tree.rest.person(written.payload)
        assert created["birth_ref_index"] == 0
        assert len(created["note_list"]) == 1
        assert len(created["tag_list"]) == 1


class TestTheReadToolsAgainstTheServersOwnProjections:
    def test_a_search_hits_a_name_only_an_alternate_carries(self, seeded_tree) -> None:
        """`search_person` asks for `?keys=…,alternate_names` (`:836-838`) and matches against
        every alternate name too (`:239-251`). Drop that key from the projection and maiden-name
        search silently returns nothing — the one thing this tool does that no other tool can."""
        subject = person_with_an_alternate_name()
        query = subject["alternate_names"][0]["surname"]

        rows = payload_list(seeded_tree.mcp.call("gramps_search_person", {"query": query}))

        assert [row["gramps_id"] for row in rows] == [subject["gramps_id"]]

    def test_a_surname_search_returns_exactly_the_people_who_carry_it(self, seeded_tree) -> None:
        """Deterministic only because `test_00_fixture_xml.py` asserts no fixture name is a
        substring of another — without that invariant every count here is luck."""
        surname, expected = largest_surname_group()

        rows = payload_list(seeded_tree.mcp.call("gramps_search_person", {"query": surname}))

        assert sorted(row["gramps_id"] for row in rows) == expected

    def test_the_limit_is_applied_by_the_server_and_clamped_below_zero(self, seeded_tree) -> None:
        surname, expected = largest_surname_group()
        assert len(expected) > 5, "the group has to exceed the limit or the cap proves nothing"

        call = seeded_tree.mcp.call
        capped = payload_list(call("gramps_search_person", {"query": surname, "limit": 5}))
        none_at_all = payload_list(call("gramps_search_person", {"query": surname, "limit": 0}))
        negative = payload_list(call("gramps_search_person", {"query": surname, "limit": -1}))

        assert len(capped) == 5
        assert none_at_all == []
        assert negative == [], "a negative limit clamps to zero (`gramps_client.py:858-860`)"

    def test_two_pages_of_people_are_disjoint_and_both_real(self, seeded_tree) -> None:
        """`page=None -> 1` (`:653-656`) exists because gramps-web-api ignores `pagesize` when
        `page < 1`. Non-vacuous only because the tree holds more people than two pages."""
        assert cast.COUNTS["people"] > 10

        call = seeded_tree.mcp.call
        first = payload_list(call("gramps_list_people", {"keys": ["gramps_id"], "pagesize": 5}))
        second = payload_list(
            call("gramps_list_people", {"keys": ["gramps_id"], "page": 2, "pagesize": 5})
        )

        page_one = {row["gramps_id"] for row in first}
        page_two = {row["gramps_id"] for row in second}
        everybody = {person["gramps_id"] for person in seeded_tree.rest.people()}
        assert len(page_one) == len(page_two) == 5
        assert not page_one & page_two
        assert (page_one | page_two) <= everybody


class TestTheRefusalsWhoseWordingThisRepoAuthored:
    """Only the four whose message is a repo-authored fragment. The rest of the matrix's negative
    cases assert a bare gramps id, a tuple repr or pydantic prose, which `test_00_vocabulary.py`
    rejects — rightly: `contains="<tool name>"` is satisfied by *any* failure of that tool."""

    @pytest.mark.refusal
    def test_a_person_needs_a_name(self, seeded_tree) -> None:
        assert_refusal(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_add_person",
            {"first_name": "   ", "surname": "", "gender": 2},
            contains="add_person requires a non-empty first_name or surname",
        )

    @pytest.mark.refusal
    def test_a_between_birth_year_needs_its_upper_bound(self, seeded_tree) -> None:
        assert_refusal(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_add_person",
            {
                "first_name": "Ohne",
                "surname": "Obergrenze",
                "gender": 1,
                "birth_year": 1850,
                "birth_quality": "between",
            },
            contains="birth_year_to is required when birth_quality='between'",
        )

    @pytest.mark.refusal
    def test_an_unknown_birth_quality_is_named_back(self, seeded_tree) -> None:
        """The fragment stops before `{quality!r}` — the repr is the server's, not ours."""
        assert_refusal(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_add_person",
            {
                "first_name": "Unklares",
                "surname": "Datum",
                "gender": 1,
                "birth_year": 1850,
                "birth_quality": "ungefähr",
            },
            contains="Unknown birth_quality: ",
        )

    @pytest.mark.refusal
    def test_swapping_a_name_that_is_not_there_refuses_and_keeps_the_one_that_is(
        self, seeded_tree
    ) -> None:
        """`expect_record` is what makes this more than `is_error`: a refusal that already wrote
        reads exactly like a clean rejection to the text (checkpoint B6)."""
        subject = person_with_an_alternate_name()
        gramps_id = subject["gramps_id"]

        assert_refusal(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_swap_primary_name",
            {"gramps_id": gramps_id, "alt_index": 5},
            contains="no alternate name at index ",
            expect_record={
                "people": {gramps_id: {"primary_name.surname_list.0.surname": subject["surname"]}}
            },
        )
