# Generated by OrchestKit Claude Plugin
# Created: 2026-08-01

"""The files a use case needs are on disk before it is allowed to cost anything (T2.6, D17).

The first full sweep paid three times for uc19 and learned nothing about the product. The
model did everything right — it called `gramps_import_file` with the name the prompt gave it —
and the server answered `Import file not found in backup directory`. The file was never there:
the sweep staged the tree fixture into the mount and nothing else, while
`fixtures/backup-inputs.json` had declared *two* inputs since D17.

That is the enumeration defect this suite already knows by name. `mcp_config.py` derives its
mount list from the repo root precisely because the Dockerfile's hand-kept `COPY` list has
shipped a broken image twice by falling behind the tree; the backup inputs were hand-kept
anyway, and fell behind the same way.

Two tests, because the staging and the catalog can drift apart in both directions: one pins
that everything *declared* lands, the other that everything a prompt *names* is declared.
"""

from __future__ import annotations

import re

from harness.backup_dir import load_manifest
from stage2 import __main__ as cli
from stage2.catalog import load_all

# A prompt may only name a file the run put there. Outputs are asserted by `backup_file`,
# which reads what appeared during the call and never needs the name in advance — so a
# filename in a prompt is an input, always.
NAMED_FILE = re.compile(r"[\w.-]+\.gramps\b")


def test_every_declared_input_lands_in_the_mounted_directory(tmp_path) -> None:
    """The whole manifest, not the one file the reset happens to need."""
    backup = cli.stage_backup(tmp_path)

    assert {entry.name for entry in backup.iterdir()} == set(load_manifest())


def test_the_file_uc19_asks_for_is_one_of_them(tmp_path) -> None:
    """The instance that cost $0.39 and proved nothing, pinned by name.

    Naming it here is not redundant with the manifest check: a manifest that lost the entry
    would satisfy "everything declared landed" and still leave uc19 unable to pass.
    """
    backup = cli.stage_backup(tmp_path)

    assert (backup / "cousins-branch.gramps").is_file()


def test_a_prompt_may_not_name_a_file_nobody_stages() -> None:
    """The other direction: a new use case that says "import foo.gramps" fails here, for free.

    Without this the next such use case behaves exactly like uc19 did — the model calls the
    right tool with the right argument, the server cannot find the file, and the suite reports
    it as a product finding after paying for three runs of it.
    """
    declared = set(load_manifest())
    named = {
        (case.id, filename)
        for case in load_all().values()
        for filename in NAMED_FILE.findall(case.prompt)
    }

    assert {(case, name) for case, name in named if name not in declared} == set()
