# Generated by OrchestKit Claude Plugin
# Created: 2026-08-01

"""Which CI leg each test belongs to, declared and linted (plan T3.4). No Docker.

The required leg runs `-m "e2e and not gramps"`: everything that needs at most Docker, no
services, no secrets, and therefore no reason ever to be advisory. Whether a module belongs
there is a property of what it *does*, but CI can only read what it *says* — so the modules
that bring up an instance say so with a marker, and this file is what keeps the saying honest.

Two directions, both of them failures:

* a module that brings up an instance and forgets the marker drags a whole Gramps Web bring-up
  into the job that is supposed to need no services — and it will pass there, slowly, until the
  day the runner has no network and the failure looks like the product's;
* a module that carries the marker without needing one is quietly excluded from the required
  leg, which is the more dangerous direction: a test nobody runs is indistinguishable from a
  test that passes.

`test_00_*` is exempt by the convention the rest of the suite already rests on — those modules
are Docker-free, and one of them refers to `GrampsInstance` precisely because it patches the
bring-up away.

The list of spellings below is the part that rots. It grew once already: T4.0 added a second way
to acquire an instance — asking for `seeded_tree` — and the check went red on the first module
that used it, correctly, for the wrong stated reason. Anything that hands a module a live
instance belongs in that tuple on the same commit it is written.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

E2E_ROOT = Path(__file__).parent
MARKER = re.compile(r"^pytestmark = pytest\.mark\.gramps$", re.MULTILINE)

# The ways a module can end up with a live instance. There was one until T4.0 — construct a
# `GrampsInstance` yourself — and the check read that name directly. `seeded_tree` is the second:
# a matrix asks for the substrate and never names the class that brings it up, so a detector
# looking only for `GrampsInstance` calls a module services-free that starts Gramps Web, Redis,
# two volumes and a container. Both spellings are listed rather than one generalised guess,
# because a rule that infers "probably needs services" from something vaguer is a rule that
# starts excusing modules nobody meant to excuse.
NEEDS_INSTANCE = ("GrampsInstance", "seeded_tree")

# This module names both things it looks for, so it matches itself. Excluded rather than
# worked around: a check that has to be careful about its own text is one nobody will edit
# safely later.
MODULES = sorted(path for path in E2E_ROOT.glob("test_*.py") if path.name != Path(__file__).name)


def declares_instance(source: str) -> bool:
    return MARKER.search(source) is not None


def test_the_suite_has_modules_to_classify() -> None:
    """A glob that matched nothing would make every check below vacuously true."""
    assert len(MODULES) > 20


@pytest.mark.parametrize("module", MODULES, ids=lambda path: path.name)
def test_a_module_declares_the_instance_it_brings_up(module: Path) -> None:
    source = module.read_text(encoding="utf-8")
    needs_instance = any(spelling in source for spelling in NEEDS_INSTANCE)
    declares = declares_instance(source)

    if module.name.startswith("test_00_"):
        assert not declares, f"{module.name} is a Docker-free module and cannot need an instance"
        return
    assert needs_instance == declares, (
        f"{module.name}: uses an instance = {needs_instance}, declares one = {declares}"
    )


def test_both_legs_are_non_empty() -> None:
    """Neither half may collapse: an empty required leg would be a green job that ran nothing."""
    marked = [path.name for path in MODULES if declares_instance(path.read_text(encoding="utf-8"))]

    assert marked, "no module declares an instance — the marker has stopped being applied"
    assert len(marked) < len(MODULES), "every module needs an instance; the required leg is empty"
