# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""K of N, and what may become a public issue (T2.6, D24). No Docker, no model.

Every rule here exists because the repo is public. A model is not a deterministic function, so
one red run is a coin; three reds of the *same* assertion is a finding. The arithmetic is worth
testing on its own because it decides how much of the user's window a sweep spends: a green use
case must cost one run, not five.
"""

from __future__ import annotations

import pytest
from stage2 import gates
from stage2.gates import Attempt

PASS = Attempt("OK", ())
FAIL = Attempt("OK", ("uc1/counts",), 0.1)
UNSURE = Attempt("INCONCLUSIVE", (), 0.05)


def sequence(*attempts: Attempt) -> gates.Verdict:
    """Escalate over a canned sequence, and refuse to run past its end."""
    return gates.escalate("uc1", lambda number: attempts[number - 1])


def test_a_passing_use_case_costs_one_run() -> None:
    """The early stop that pays for the whole sweep. Repetition confirms a failure; it does not
    go looking for one, so a green first run ends the use case — otherwise 27 healthy use cases
    would cost four runs each."""
    verdict = sequence(PASS)

    assert len(verdict.attempts) == 1
    assert not verdict.reportable and not verdict.watch


def test_a_use_case_that_always_fails_stops_at_k() -> None:
    verdict = sequence(FAIL, FAIL, FAIL, FAIL, FAIL)

    assert len(verdict.attempts) == gates.K_FAILURES
    assert verdict.reportable
    assert verdict.recurring == ("uc1/counts",)


def test_two_failures_are_a_watch_line_and_never_a_draft() -> None:
    verdict = sequence(FAIL, FAIL, PASS, PASS, PASS)

    assert verdict.failures == 2
    assert verdict.watch and not verdict.reportable


def test_the_run_stops_as_soon_as_three_failures_are_out_of_reach() -> None:
    verdict = gates.escalate("uc1", lambda number: FAIL if number == 1 else PASS)

    assert len(verdict.attempts) == 4, "one failure cannot become three after the fourth run"
    assert not verdict.watch


def test_three_failures_of_different_assertions_are_three_coins() -> None:
    """Per assertion, not per run — otherwise a public issue would carry a claim that no single
    run supports."""
    verdict = gates.escalate("uc1", lambda number: Attempt("OK", (f"uc1/assertion-{number}",), 0.1))

    assert verdict.failures == gates.K_FAILURES
    assert verdict.recurring == ()
    assert not verdict.reportable


def test_a_repeat_offender_among_the_noise_is_still_a_finding() -> None:
    verdict = gates.escalate(
        "uc1", lambda number: Attempt("OK", ("uc1/counts", f"uc1/flake-{number}"), 0.1)
    )

    assert verdict.recurring == ("uc1/counts",)
    assert verdict.reportable


def test_an_inconclusive_run_votes_for_nothing() -> None:
    """Counting it as a pass buries a real defect; as a failure it files an issue for a timeout."""
    verdict = sequence(UNSURE, UNSURE, PASS)

    assert verdict.inconclusive == 2
    assert verdict.failures == 0 and verdict.passes == 1
    assert not verdict.reportable and not verdict.watch


def test_an_inconclusive_run_is_retried_because_it_said_nothing() -> None:
    """A timeout is not a pass. The use case is retried until something conclusive happens —
    and the attempts it burned still count against N."""
    verdict = sequence(UNSURE, UNSURE, UNSURE, FAIL, FAIL)

    assert len(verdict.attempts) == 4, "the fourth failure can no longer become three"
    assert verdict.failures == 1 and not verdict.reportable


def test_the_cost_of_every_attempt_is_kept() -> None:
    verdict = sequence(FAIL, UNSURE, PASS, PASS)

    assert verdict.cost_usd == pytest.approx(0.15)


@pytest.mark.parametrize(
    ("failures", "passes", "attempts", "expected"),
    [
        (0, 0, 0, True),  # nothing has happened yet
        (0, 1, 1, False),  # it works — do not go hunting
        (0, 0, 2, True),  # two inconclusive runs are still no answer
        (1, 0, 1, True),  # a failure worth confirming
        (1, 0, 4, False),  # one failure can no longer become three
        (2, 0, 4, True),  # two in four: the fifth can still settle it
        (3, 0, 3, False),  # established
        (2, 2, 5, False),  # out of attempts
    ],
)
def test_the_stopping_rule_itself(
    failures: int, passes: int, attempts: int, expected: bool
) -> None:
    assert gates.keep_going(failures, passes, attempts) is expected


def test_a_finding_carries_a_key_that_can_be_grepped_for() -> None:
    key = gates.dedup_key("uc9", "uc9/she-is-recorded-female")

    assert gates.MARKER in key and "uc9/she-is-recorded-female" in key


def test_an_open_issue_for_the_same_pair_is_found_locally() -> None:
    """Locally, over `gh issue list` — `gh search` lags minutes and would file a second issue
    for a finding this very sweep just reported."""
    key = gates.dedup_key("uc9", "uc9/she-is-recorded-female")
    issues = [
        {"number": 20, "title": "unrelated", "body": "nothing"},
        {"number": 21, "title": "Stage 2: something", "body": f"{key}\n\nmore text"},
    ]

    assert gates.already_filed(key, issues) == 21


def test_a_different_assertion_of_the_same_use_case_is_a_different_finding() -> None:
    filed = gates.dedup_key("uc9", "uc9/counts")
    new = gates.dedup_key("uc9", "uc9/she-is-recorded-female")
    issues = [{"number": 21, "title": "t", "body": filed}]

    assert gates.already_filed(new, issues) is None
