# Generated by OrchestKit Claude Plugin
# Created: 2026-08-01

"""The prompt a model actually gets, and what a sweep keeps when it stops (T2.6).

Two defects, both found by the first full sweep and both of the same family the catalog kept
producing — something declared as data that nothing consumes:

* **the placeholder was never filled.** `validate.py` checked that `{target}` named a declared
  subject, its docstring said the value was "filled at run time", and no code anywhere filled
  it. uc26 went to a real model with a literal `{target}`; the model asked what that was
  supposed to mean and called no tool. From outside that is indistinguishable from every gramps
  tool being undiscoverable, so the selfcheck aborted the sweep — correctly, and expensively;
* **the abort threw away the evidence.** `SpendExceeded` stopped the loop and kept what it had.
  `HarnessAborted` escaped it, escaped `main()`, and `summary.md` was never written: 26 finished
  use cases and the money they cost, gone because the 27th proved nothing.

The guard against the first is deliberately placed *before* the spawn. A prompt with a
placeholder still in it is not an expensive failure here; it is a free one.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest
from fixtures import cast
from fixtures import stage2_records as make
from stage2 import report, runner, subjects, sweep, transcript
from stage2.catalog import Assertion, UseCase, load_all

FIXTURE = Path(__file__).parent / "fixtures" / "stage2" / "clean-run.jsonl"
TREE = make.state(people=(make.person("I0000", "Rosalind", "Steinbrecht"),))
HER = {"namespace": "people", "first_name": "Rosalind", "surname": "Steinbrecht"}


def use_case(prompt: str, *, subjects_: dict[str, Any], identifier: str = "uc1") -> UseCase:
    return UseCase(
        id=identifier,
        slug=f"{identifier}-probe",
        tier=1,
        prompt=prompt,
        primary=("gramps_get_person",),
        decoys=(),
        secondary=(),
        subjects=subjects_,
        guards={"people": [], "families": [], "sources": []},
        maxdrop=0,
        assertions=(Assertion(f"{identifier}/counts", "counts", {"deltas": {}}),),
        waivers=(),
        path=Path(f"{identifier}.yaml"),
    )


class RecordingRunner:
    """Hands out canned runs and keeps the prompt it was asked to run."""

    def __init__(self, *verdicts: str) -> None:
        self.verdicts = list(verdicts) or [runner.OK]
        self.prompts: list[str] = []

    def run(self, case: UseCase) -> runner.Run:
        verdict = self.verdicts[min(len(self.prompts), len(self.verdicts) - 1)]
        self.prompts.append(case.prompt)
        return runner.Run(
            case.id,
            verdict,
            "the server was not reachable",
            Path("/tmp"),
            (),
            transcript.load(FIXTURE),
        )


def build(driver: Any) -> sweep.Sweep:
    return sweep.Sweep(driver=driver, reset=lambda: None, capture=lambda: TREE)


def test_the_prompt_a_model_gets_has_its_placeholder_filled_in() -> None:
    """The whole point of uc26: it asks for a record *by* id, and an id is the one thing a use
    case may not write down — so it has to arrive from the tree the run starts on."""
    driver = RecordingRunner(runner.OK)

    build(driver).attempt(
        use_case("Everything on file for {target}, please.", subjects_={"target": HER})
    )

    assert driver.prompts == ["Everything on file for I0000, please."]


def test_an_unfilled_placeholder_never_reaches_a_paid_run() -> None:
    """Free here, $0.02 and a dead sweep in production. The guard is before the spawn on
    purpose: the run that taught us this had already been paid for when it was noticed."""
    driver = RecordingRunner(runner.OK)

    with pytest.raises(sweep.HarnessAborted, match="placeholder"):
        build(driver).attempt(
            use_case("Everything on file for {stranger}.", subjects_={"target": HER})
        )

    assert driver.prompts == [], "the model must not be asked a question nobody can answer"


def test_uc26_the_use_case_that_cost_a_sweep_fills_against_the_committed_cast() -> None:
    """The regression, named. Not a synthetic prompt — the real uc26 against the real fixture."""
    case = load_all()["uc26"]
    tree = subjects.from_cast(cast)

    filled = subjects.fill(case.prompt, subjects.resolve_all(dict(case.subjects), tree))

    assert subjects.unfilled(filled) == []
    assert "{" not in filled
    assert filled != case.prompt, "uc26 is the one prompt that has to carry an id"


def test_every_prompt_in_the_catalog_survives_being_filled() -> None:
    """The other 26 carry no placeholder, and this is what keeps that true rather than assumed:
    a subject renamed in `subjects:` and not in the prompt is caught here, for nothing."""
    tree = subjects.from_cast(cast)

    unfilled = {
        case.id: subjects.unfilled(
            subjects.fill(case.prompt, subjects.resolve_all(dict(case.subjects), tree))
        )
        for case in load_all().values()
    }

    assert {case: left for case, left in unfilled.items() if left} == {}


def test_an_abort_keeps_the_use_cases_that_already_finished() -> None:
    """26 runs and the money they cost used to go in the bin because the 27th proved nothing."""
    driven = build(RecordingRunner(runner.OK, runner.HARNESS_BROKEN))
    cases = [
        use_case("Everything on file for {target}.", subjects_={"target": HER}, identifier="uc1"),
        use_case("Everything on file for {target}.", subjects_={"target": HER}, identifier="uc2"),
    ]

    verdicts = driven.run(cases)

    assert [verdict.use_case for verdict in verdicts] == ["uc1"]
    assert "uc2" in driven.aborted and not driven.stopped


def test_the_abort_still_reads_as_a_harness_fault_and_not_as_a_finding() -> None:
    driven = build(RecordingRunner(runner.HARNESS_BROKEN))

    verdicts = driven.run([use_case("Anything at all.", subjects_={})])

    assert verdicts == [] and driven.aborted


def test_a_subject_that_no_longer_fits_the_tree_keeps_the_evidence_too() -> None:
    """The same hole as D2, one path over.

    `HarnessAborted` was taught to keep what the sweep already had. Subject resolution runs
    before that — in `_addressed` and in `evidence_for` — and raises a bare `ProbeError` when
    the fixture and the catalog have drifted apart. That one still escaped the loop, escaped
    `main()`, and wrote no report: a drifted fixture is exactly the fault most likely to hit
    every use case, so it is the one that would discard the most paid runs.
    """
    driven = build(RecordingRunner(runner.OK))
    gone = {"namespace": "people", "first_name": "Wendelin", "surname": "Vergangen"}
    cases = [
        use_case("Everything on file for {target}.", subjects_={"target": HER}, identifier="uc1"),
        use_case("Everything on file for {target}.", subjects_={"target": gone}, identifier="uc2"),
    ]

    verdicts = driven.run(cases)

    assert [verdict.use_case for verdict in verdicts] == ["uc1"]
    assert "uc2" in driven.aborted, "the report has to name the use case that stopped it"
    assert not driven.stopped, "a drifted subject is a fault, not a budget"


def test_the_report_says_at_the_top_that_the_sweep_was_aborted() -> None:
    """Skimmed, a partial table is indistinguishable from a whole one."""
    written = report.summary([], [], spent=2.31, aborted="uc26: the server was not reachable")

    assert "aborted" in written.lower()
    assert written.index("aborted") < written.index("How to read this")
    assert "not run" in written


def test_a_spent_budget_reads_as_a_stop_and_not_as_an_abort() -> None:
    """The two are not the same event: one is the user's own cap doing its job."""
    written = report.summary([], [], spent=9.0, stopped="$9.00 spent of the $9.00 allowed")

    assert "budget" in written.lower() and "aborted" not in written.lower()
