# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""The entry point that spends money, checked where it costs nothing (T2.6, T2.8).

`main()` needs Docker, an instance and a subscription. Everything that decides *how much* of
those it will use — which use cases, how often, with what cap — is parsing and selection, and
that is testable here. The cheap paths are the ones D24 made mandatory, so they are the ones
pinned: a mistyped `--tier` must not quietly become a full sweep.
"""

from __future__ import annotations

import pytest
from stage2 import __main__ as cli
from stage2.catalog import load_all

TIER_1 = 8


def test_the_tier_flag_selects_the_smoke_tier() -> None:
    chosen = cli.select(cli.parse(["--tier", "1"]))

    assert len(chosen) == TIER_1
    assert {case.tier for case in chosen} == {1}


def test_no_flags_means_every_use_case() -> None:
    assert len(cli.select(cli.parse([]))) == len(load_all())


def test_only_names_use_cases_and_keeps_them_in_order() -> None:
    chosen = cli.select(cli.parse(["--only", "uc19", "uc7"]))

    assert [case.id for case in chosen] == ["uc7", "uc19"]


def test_a_use_case_that_does_not_exist_is_refused_before_anything_starts() -> None:
    with pytest.raises(Exception, match="uc99"):
        cli.select(cli.parse(["--only", "uc99"]))


def test_two_ways_of_choosing_at_once_is_an_error_not_a_silent_winner() -> None:
    with pytest.raises(SystemExit):
        cli.parse(["--tier", "1", "--only", "uc9"])


def test_a_tier_nobody_defined_is_refused() -> None:
    with pytest.raises(SystemExit):
        cli.parse(["--tier", "4"])


def test_zero_repeats_is_refused() -> None:
    """`--repeats 0` would report "nothing failed" after running nothing at all."""
    with pytest.raises(SystemExit):
        cli.parse(["--repeats", "0"])


def test_the_spend_cap_is_read_as_a_number() -> None:
    assert cli.parse(["--max-spend-usd", "3.00"]).max_spend_usd == pytest.approx(3.0)


def test_the_cap_is_absent_unless_asked_for() -> None:
    """Absent means "no cap", which is why the flag is in the module docstring's first example."""
    assert cli.parse([]).max_spend_usd is None
