# Generated by OrchestKit Claude Plugin
# Created: 2026-08-02

r"""No test spells an id the cast could hand it (README, `fixtures/cast.py`). No Docker.

`cast.py` is regenerated with the tree, and the tree renumbers. T4.5 grew it by eighteen
people and five families and every id past the insertion point moved — which is the whole
danger: a test that spells an id itself does not fail afterwards, it silently changes subject.
It still passes, against somebody else.

The rule, scoped by measurement rather than by ambition:

> a module carrying `pytestmark = pytest.mark.gramps` may contain a string literal shaped like
> a gramps id only inside a statement that also names `cast`.

Both halves of the scope are deliberate.

* **Only the marked modules.** They are the ones talking to a live tree grown from the
  committed fixture, so they are the ones an id can go stale in. `test_00_stage2_*` builds
  stub trees full of `"I0000"` and those ids *are* the fixture of that test — a blanket ban
  would ban writing them at all.
* **Statement, not physical line.** A line rule is satisfied by the word `cast` in a comment
  beside the literal, and "it's from the cast" is exactly the reasoning that puts a stale id
  in a test. The statement the literal sits in has to actually consult the module. It also
  costs nothing on a call `ruff format` wrapped across three lines, which a line rule reds.

`[A-Z]\d{4}` rather than the `[IFSN]` this was scoped with: the committed tree also carries 65
event ids, and a later one may carry citations, places or media. A prefix list is a thing that
falls behind, and the direction it falls in is silence. Over-eagerness costs a rename; silence
costs a test that stopped testing what it says.

The lint was not green on arrival. Its first run reported `UC14_HOUSEHOLD = "F0021"` in
`test_05_fixture.py` — written the day before by the commit that regrew the fixture, and the
only place in the suite where "the household uc14 is about" was pinned to a number instead of
to the person the use case declares. That is the class of bug this file is here for, found by
it on its first pass.
"""

from __future__ import annotations

import ast
import re
from collections.abc import Iterable, Iterator
from dataclasses import dataclass
from pathlib import Path

import pytest
from harness.vocabulary import module_markers

E2E_ROOT = Path(__file__).parent

# The marker that means "this module runs against a live tree" — the scope of the rule.
INSTANCE_MARKER = "gramps"
# The name a compliant literal has to sit next to. `from fixtures import cast` is how all
# eight marked modules spell it; an `import fixtures.cast as c` would read as a violation,
# correctly — the point is that the reader of the line can see where the id came from.
CAST = "cast"
GRAMPS_ID = re.compile(r"[A-Z]\d{4}")


@dataclass(frozen=True)
class Literal:
    """One id-shaped string in a module that runs against the live tree."""

    origin: str
    lineno: int
    value: str
    resolved: bool
    """True if the statement it sits in also names `cast` — i.e. it is being compared to a
    generated value rather than used to find one."""


def scan_literals(tree: ast.Module, origin: str) -> list[Literal]:
    """Every id-shaped literal in one parsed module, each attributed to its own statement."""
    found: list[Literal] = []
    for statement in (node for node in ast.walk(tree) if isinstance(node, ast.stmt)):
        own = list(_own_nodes(statement))
        resolved = any(isinstance(node, ast.Name) and node.id == CAST for node in own)
        found.extend(
            Literal(origin=origin, lineno=node.lineno, value=node.value, resolved=resolved)
            for node in own
            if isinstance(node, ast.Constant)
            and isinstance(node.value, str)
            and GRAMPS_ID.search(node.value)
        )
    return found


def scan_tree(root: Path) -> dict[str, list[Literal]]:
    """Every module the rule applies to, and what it carries. Keyed by module, so a scan that
    stops seeing the marked modules at all is visible as an empty dict rather than as green."""
    scanned: dict[str, list[Literal]] = {}
    for path in sorted(root.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        tree = ast.parse(path.read_text(encoding="utf-8"))
        if INSTANCE_MARKER not in module_markers(tree):
            continue
        origin = str(path.relative_to(root))
        scanned[origin] = scan_literals(tree, origin)
    return scanned


def unresolved(literals: Iterable[Literal]) -> list[Literal]:
    """The ids nobody read out of the cast — the ones a regrow moves without a red."""
    return [literal for literal in literals if not literal.resolved]


def _own_nodes(node: ast.AST) -> Iterator[ast.AST]:
    """`node` and everything under it that is not inside a *nested* statement.

    This is what makes the attribution one-to-one: every literal belongs to exactly one
    statement, the nearest one enclosing it. Without the cut, an `if` whose body happens to
    mention `cast` would excuse an id in its condition.
    """
    yield node
    for child in ast.iter_child_nodes(node):
        if isinstance(child, ast.stmt):
            continue
        yield from _own_nodes(child)


# -- the rule, over the real tree --------------------------------------------------------


@pytest.fixture(scope="module")
def scanned() -> dict[str, list[Literal]]:
    return scan_tree(E2E_ROOT)


def test_no_marked_module_spells_an_id_the_cast_could_hand_it(
    scanned: dict[str, list[Literal]],
) -> None:
    strays = [literal for literals in scanned.values() for literal in unresolved(literals)]

    assert not strays, "id literal that does not come from the cast: " + "; ".join(
        f"{literal.origin}:{literal.lineno} {literal.value[:40]!r}" for literal in strays
    )


def test_the_scan_sees_the_modules_it_lints(scanned: dict[str, list[Literal]]) -> None:
    """The check above is green on an empty scan, which is how a guard like this dies: the
    marker gets spelled differently, nothing matches, and the silence reads as compliance."""
    assert len(scanned) >= 5, f"only {len(scanned)} modules carry the {INSTANCE_MARKER} marker"
    assert "test_05_fixture.py" in scanned

    resolved = [literal for literals in scanned.values() for literal in literals]
    assert resolved, "no id literal found anywhere — the detector has stopped detecting"


# -- the guard's own falsification --------------------------------------------------------


def parse(sample: str) -> list[Literal]:
    return scan_literals(ast.parse(sample), "sample.py")


BARE_LITERAL = """
household = families["F0021"]
"""

FROM_THE_CAST = """
assert cast.PEOPLE[0]["gramps_id"] == "I0000", "ids start at I0000, not I0001"
"""

WRAPPED_ACROSS_LINES = """
assert families[cast.GRAPH["single_parent_family"]]["gramps_id"] == (
    "F0025"
)
"""

TALKED_OUT_OF_IT = """
household = families["F0021"]  # from the cast, honestly
"""

IN_PROSE = """
def test_it():
    \"\"\"F0021 is uc14's household.\"\"\"
"""

NO_ID_IN_IT = """
mother = people["Talvegaard"]
year = "1912"
"""


def test_a_bare_id_is_reported() -> None:
    assert [literal.value for literal in unresolved(parse(BARE_LITERAL))] == ["F0021"]


def test_an_id_compared_against_the_cast_is_not() -> None:
    """Both literals on that line, the id and the message that quotes two more, belong to a
    statement that reads the generated file. That is the shape the rule exists to allow."""
    assert unresolved(parse(FROM_THE_CAST)) == []
    assert len(parse(FROM_THE_CAST)) == 2


def test_a_statement_wrapped_across_lines_is_not() -> None:
    """The reason the scope is the statement: `ruff format` decides where the line ends."""
    assert unresolved(parse(WRAPPED_ACROSS_LINES)) == []


def test_a_comment_cannot_talk_the_lint_out_of_it() -> None:
    """The other reason. A comment is where "it's from the cast" gets asserted rather than
    done, and it is invisible to the parser — which is the property being relied on here."""
    assert [literal.value for literal in unresolved(parse(TALKED_OUT_OF_IT))] == ["F0021"]


def test_an_id_in_prose_is_reported_too() -> None:
    """A docstring naming an id rots exactly like a line of code naming one, and reads as
    documentation while it does — so it is not exempt. Say "uc14's household" instead."""
    assert len(unresolved(parse(IN_PROSE))) == 1


def test_a_string_that_is_not_an_id_is_left_alone() -> None:
    assert parse(NO_ID_IN_IT) == []


MARKED = "pytestmark = pytest.mark.gramps\n"
MARKED_IN_A_LIST = "pytestmark = [pytest.mark.gramps, pytest.mark.refusal]\n"
UNMARKED = "import pytest\n"


@pytest.mark.parametrize(
    ("source", "in_scope"),
    [(MARKED, True), (MARKED_IN_A_LIST, True), (UNMARKED, False)],
    ids=["plain", "list", "none"],
)
def test_the_scope_is_read_from_the_marker_not_the_spelling(source: str, in_scope: bool) -> None:
    """A matrix module may well end up carrying two module-level markers, and a regex over the
    source line would then quietly drop it out of scope — the silent direction again."""
    assert (INSTANCE_MARKER in module_markers(ast.parse(source))) is in_scope
