# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""The runner, without a subscription, a model or Docker (T2.4).

The spawn is injected for the same reason `_sleep` is injected in the product's polling loops:
the tests that keep the expensive stage honest must be free to run. What is exercised here is
everything around the model — the evidence directory, the guarded invocation, and the three
verdicts a run can carry.

The verdicts are kept apart on purpose. A killed run and a contaminated run and a run the model
simply failed are three different things, and only one of them is about this product.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from harness.mcp_container import ImageRef
from stage2 import driver, runner, transcript
from stage2.catalog import UseCase

FIXTURE = Path(__file__).parent / "fixtures" / "stage2" / "clean-run.jsonl"
IMAGE = ImageRef(reference="gramps-remote-mcp:e2e-abcd1234", image_id="sha256:feed", leg="w")

USE_CASE = UseCase(
    id="uc1",
    slug="uc01-add-person-gender-enum",
    tier=1,
    prompt="Please add my grandmother Wendelmark Sorge.",
    primary=("gramps_add_person",),
    decoys=(),
    secondary=(),
    subjects={},
    guards={},
    maxdrop=0,
    assertions=(),
    waivers=(),
    path=Path("uc01.yaml"),
)


def recording(cwd: Path) -> str:
    """The recorded clean run, re-stamped with the cwd this runner actually uses."""
    events = transcript.read_events(FIXTURE)
    events[0]["cwd"] = str(cwd)
    return "".join(json.dumps(event) + "\n" for event in events)


def fake_spawn(body, code: int = 0, stderr: str = ""):
    """A spawn that writes what it is told and records how it was called."""
    calls: list[dict] = []

    def spawn(argv, *, cwd, env, stdout, timeout):
        calls.append({"argv": argv, "cwd": cwd, "env": env, "timeout": timeout})
        stdout.write_text(body(cwd) if callable(body) else body, encoding="utf-8")
        return code, stderr

    spawn.calls = calls  # type: ignore[attr-defined]
    return spawn


def make(tmp_path: Path, spawn) -> runner.Runner:
    return runner.Runner(
        image=IMAGE,
        network="gwe2e-abcd1234-net",
        gramps_env={"GRAMPS_BASE_URL": "http://gwe2e-abcd1234-web:5000"},
        backup_dir=tmp_path / "backup",
        run_root=tmp_path / "run",
        runid="abcd1234",
        spawn=spawn,
        environ={"HOME": "/home/nobody"},
    )


def test_preparing_writes_the_config_and_an_empty_working_directory(tmp_path: Path) -> None:
    driven = make(tmp_path, fake_spawn(""))
    config = driven.prepare()

    assert json.loads(config.read_text(encoding="utf-8"))["mcpServers"]["gramps"]
    assert driven.cwd.is_dir()
    assert list(driven.cwd.iterdir()) == []


def test_preparing_refuses_a_working_directory_with_anything_in_it(tmp_path: Path) -> None:
    driven = make(tmp_path, fake_spawn(""))
    driven.cwd.mkdir(parents=True)
    (driven.cwd / "CLAUDE.md").write_text("steer me", encoding="utf-8")

    with pytest.raises(Exception, match="CLAUDE.md"):
        driven.prepare()


def test_a_clean_run_is_gradeable_and_carries_its_cost(tmp_path: Path) -> None:
    driven = make(tmp_path, fake_spawn(recording))
    driven.prepare()

    result = driven.run(USE_CASE)

    assert result.verdict == runner.OK
    assert result.gradeable
    assert result.cost_usd == pytest.approx(0.0791895)
    assert result.transcript is not None
    assert [call.name for call in result.transcript.gramps_calls] == ["gramps_add_person"]


def test_the_evidence_lands_on_disk(tmp_path: Path) -> None:
    """Decision (d): a non-deterministic failure nobody can read afterwards is worth nothing."""
    driven = make(tmp_path, fake_spawn(recording, stderr="a warning"))
    driven.prepare()

    result = driven.run(USE_CASE)

    assert (result.run_dir / "run.jsonl").exists()
    assert (result.run_dir / "run.err").read_text(encoding="utf-8") == "a warning"
    assert json.loads((result.run_dir / "argv.json").read_text(encoding="utf-8"))[0] == "claude"


def test_each_use_case_gets_its_own_directory_and_one_shared_config(tmp_path: Path) -> None:
    driven = make(tmp_path, fake_spawn(recording))
    driven.prepare()
    other = UseCase(**{**USE_CASE.__dict__, "id": "uc2", "slug": "uc02-add-family"})

    first, second = driven.run(USE_CASE), driven.run(other)

    assert first.run_dir != second.run_dir
    assert first.argv[first.argv.index("--mcp-config") + 1] == str(driven.config_path)


def test_the_process_is_spawned_in_the_empty_directory_with_the_guarded_argv(
    tmp_path: Path,
) -> None:
    spawn = fake_spawn(recording)
    driven = make(tmp_path, spawn)
    driven.prepare()

    driven.run(USE_CASE)

    (call,) = spawn.calls
    assert call["cwd"] == driven.cwd
    assert call["argv"][-1] == USE_CASE.prompt
    assert "--strict-mcp-config" in call["argv"]
    assert driver.SIMPLE_MODE_ENV not in call["env"]


def test_a_contaminated_run_is_broken_not_failed(tmp_path: Path) -> None:
    def contaminated(cwd: Path) -> str:
        events = transcript.read_events(FIXTURE)
        events[0] |= {"cwd": str(cwd), "plugins": ["ork"]}
        return "".join(json.dumps(event) + "\n" for event in events)

    driven = make(tmp_path, fake_spawn(contaminated))
    driven.prepare()

    result = driven.run(USE_CASE)

    assert result.verdict == runner.HARNESS_BROKEN
    assert "plugins" in (result.reason or "")
    assert not result.gradeable


def test_a_killed_run_is_inconclusive_rather_than_an_exception(tmp_path: Path) -> None:
    """The wall-clock cap is the only reliable one; what it leaves behind is half a log."""
    partial = "\n".join(FIXTURE.read_text(encoding="utf-8").splitlines()[:3]) + "\n"
    driven = make(tmp_path, fake_spawn(partial, code=124, stderr="timed out after 300s"))
    driven.prepare()

    result = driven.run(USE_CASE)

    assert result.verdict == runner.INCONCLUSIVE
    assert "timed out" in (result.reason or "")
    assert result.cost_usd == 0.0


def test_an_empty_log_is_inconclusive_and_says_what_the_process_said(tmp_path: Path) -> None:
    driven = make(tmp_path, fake_spawn("", code=1, stderr="error: unknown option '--nope'"))
    driven.prepare()

    result = driven.run(USE_CASE)

    assert result.verdict == runner.INCONCLUSIVE
    assert "--nope" in (result.reason or "")


def test_a_model_that_flailed_is_inconclusive_and_keeps_its_transcript(tmp_path: Path) -> None:
    def flailed(cwd: Path) -> str:
        events = transcript.read_events(FIXTURE)
        events[0]["cwd"] = str(cwd)
        events[-1]["num_turns"] = 30
        return "".join(json.dumps(event) + "\n" for event in events)

    driven = make(tmp_path, fake_spawn(flailed))
    driven.prepare()

    result = driven.run(USE_CASE)

    assert result.verdict == runner.INCONCLUSIVE
    assert result.transcript is not None, "the evidence survives an inconclusive run"
    assert result.cost_usd > 0, "and so does what it cost"
