# Generated by OrchestKit Claude Plugin
# Created: 2026-07-30

"""Every error-text fragment this suite asserts must be one **this repo** wrote. No Docker.

Wire text comes from two places. Some of it we authored (`"requires confirm=True"`,
`"Path escapes backup directory"`); the rest belongs to FastMCP and pydantic, which
`requirements.txt` pins as a *range*. A suite that asserts framework wording turns one
`pip install -U` into a mass-red that says nothing about this server.

Prose in a README cannot enforce that, so this does: it parses every `assert_refusal(...)`
call in the e2e tree and requires its `contains=` literal to appear verbatim in a product
module. The set of product modules is **derived from the repo root**, not listed here — a
hardcoded list would drift exactly the way the Dockerfile's COPY list has drifted twice.
"""

from __future__ import annotations

import ast
from pathlib import Path

import pytest
from harness.vocabulary import (
    NOT_A_LITERAL,
    product_sources,
    scan_source,
    scan_tree,
    unauthored,
)

E2E_ROOT = Path(__file__).parent
REPO_ROOT = E2E_ROOT.parents[1]


@pytest.fixture(scope="module")
def sources() -> dict[str, str]:
    return product_sources(REPO_ROOT)


# -- the meta-test itself ------------------------------------------------------------


def test_every_asserted_fragment_is_authored_in_this_repo(sources: dict[str, str]) -> None:
    strays = unauthored(scan_tree(E2E_ROOT), sources)

    assert not strays, "not authored in any product module: " + "; ".join(
        f"{fragment.origin}:{fragment.lineno} {fragment.value!r}" for fragment in strays
    )


def test_the_scan_actually_finds_the_suites_fragments() -> None:
    """Without this the meta-test above is green on an empty scan — which is precisely how a
    guard like this dies: someone renames the helper and nothing ever reports it again."""
    found = scan_tree(E2E_ROOT)

    assert len(found) >= 3, f"only {len(found)} contains= literals found in {E2E_ROOT}"
    assert any(fragment.value == "requires confirm=True" for fragment in found)


def test_the_product_module_set_is_derived_and_covers_what_ships(sources: dict[str, str]) -> None:
    """Four modules ship (the Dockerfile COPY list). `backup_store.py` is one of them and
    authors the path-traversal refusal, so a three-module rule would reject a legitimate
    assertion — which is how a guard gets switched off."""
    assert {"server.py", "gramps_client.py", "gramps_blog.py", "backup_store.py"} <= set(sources)


# -- the guard's own falsification ---------------------------------------------------


def parse(sample: str) -> list:
    return scan_source(ast.parse(sample), "sample.py")


def test_a_framework_fragment_is_reported(sources: dict[str, str]) -> None:
    """pydantic's wording, not ours: it moves with the pin and grades the wrong project."""
    found = parse('assert_refusal(rest, mcp, "t", {}, contains="Input should be a valid integer")')

    assert [fragment.value for fragment in unauthored(found, sources)] == [
        "Input should be a valid integer"
    ]


def test_an_authored_fragment_is_accepted(sources: dict[str, str]) -> None:
    found = parse('assert_refusal(rest, mcp, "t", {}, contains="does not match the live total")')

    assert unauthored(found, sources) == []


def test_a_qualified_call_is_still_scanned(sources: dict[str, str]) -> None:
    """`assertions.assert_refusal(...)` is the same call and must not slip past the parser."""
    found = parse('assertions.assert_refusal(rest, mcp, "t", {}, contains="not our wording")')

    assert len(unauthored(found, sources)) == 1


def test_a_computed_fragment_is_a_violation(sources: dict[str, str]) -> None:
    """An f-string or a variable would let any wording through while still looking compliant,
    so a non-literal is reported rather than skipped."""
    found = parse('assert_refusal(rest, mcp, "t", {}, contains=f"person {gid} not found")')

    assert [fragment.value for fragment in found] == [NOT_A_LITERAL]
    assert len(unauthored(found, sources)) == 1


def test_a_call_without_contains_is_ignored(sources: dict[str, str]) -> None:
    """`assert_guarded_write` asserts no text at all, and must not be dragged in."""
    assert parse('assert_guarded_write(rest, mcp, "t", {}, expect_delta={})') == []
