# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""Every registered tool has a Stage-2 slot, and no slot names a tool that is gone (T2.1).

This is the cheapest test in the suite and it guards the most expensive silence. Stage 2 costs
real money and ~24 minutes per pass; a tool that ships without a use case is not *reported* as
uncovered, it simply never appears — and "the new tools are missing" has been this repo's
failure mode twice already. So the map is checked against the **live registry**, not against a
number in a README.

No Docker and no LLM: it imports `server.create_server` with a mock client, which is the same
call the release ritual uses to count tools.
"""

from __future__ import annotations

from unittest.mock import MagicMock

import pytest
from stage2.coverage import A_TWIN, COVERAGE, A, B, gating

import server


@pytest.fixture(scope="module")
def registered() -> dict[str, object]:
    """Every tool the server registers with the destructive flag on — the full 31."""
    return server.create_server(MagicMock(), enable_destructive=True)[1]


def test_every_registered_tool_has_a_use_case(registered: dict[str, object]) -> None:
    """The one that matters: a 32nd tool must not be able to ship into silence."""
    uncovered = sorted(set(registered) - set(COVERAGE))

    assert uncovered == [], (
        f"{uncovered} are registered but have no Stage-2 slot — give each one a use case where "
        "it is primary, or a Slot with grade B and a written reason why no assertion can pin it"
    )


def test_the_map_names_no_tool_that_is_not_registered(registered: dict[str, object]) -> None:
    """The other direction, which a renamed tool trips: a slot pointing at nothing would keep
    the count right while the tool it claims to cover no longer exists."""
    phantom = sorted(set(COVERAGE) - set(registered))

    assert phantom == [], f"{phantom} have a Stage-2 slot but are not registered"


def test_a_slot_that_cannot_gate_says_why(registered: dict[str, object]) -> None:
    """`B` is a concession, not a default. Each one has to carry the argument for itself, so
    that promoting a tool to gate-eligible later is a deliberate act against a written reason."""
    silent = sorted(
        tool for tool, slot in COVERAGE.items() if not gating(slot.grade) and not slot.reason
    )

    assert silent == [], f"{silent} may never gate the run and give no reason for it"


def test_a_twin_slot_says_which_twin(registered: dict[str, object]) -> None:
    """`A_TWIN` gates the outcome but not the identity, which is exactly the sort of caveat that
    gets lost. It is only usable if the record says what the tool cannot be told apart from."""
    unexplained = sorted(
        tool for tool, slot in COVERAGE.items() if slot.grade == A_TWIN and not slot.reason
    )

    assert unexplained == [], f"{unexplained} claim a behavioural twin without naming the reason"


def test_every_slot_names_a_use_case(registered: dict[str, object]) -> None:
    numberless = sorted(
        tool
        for tool, slot in COVERAGE.items()
        if not (slot.primary.startswith("uc") and slot.primary[2:].isdigit())
    )

    assert numberless == [], f"{numberless} have no `ucN` primary"


def test_the_grade_distribution_is_the_one_the_table_gives(registered: dict[str, object]) -> None:
    """Pinned on purpose, because the source design contradicts itself here.

    Its summary sentence says "22 of 31 have a gate-eligible primary … the 9 that don't are the
    six substitutable reads and the three behavioural twins". Its own itemised table gives 20 A
    + 4 A_TWIN + 7 B — 24 gate-eligible, 7 not, and the twins are four, not three. The table is
    what is encoded, because its rows carry per-tool reasons while the sentence carries only a
    count. This test is where that decision is visible instead of buried.
    """
    grades = [slot.grade for slot in COVERAGE.values()]

    assert (grades.count(A), grades.count(A_TWIN), grades.count(B)) == (20, 4, 7)
    assert sum(gating(grade) for grade in grades) == 24


def test_no_tool_is_a_decoy_in_its_own_primary(registered: dict[str, object]) -> None:
    """A decoy is a tool a use case asserts was *not* the effective route. Naming one in the
    very case it is primary for would make the use case assert both halves of a contradiction."""
    contradictory = sorted(tool for tool, slot in COVERAGE.items() if slot.primary in slot.decoy_in)

    assert contradictory == [], f"{contradictory} are primary and decoy in the same use case"
