# Generated by OrchestKit Claude Plugin
# Created: 2026-07-30

"""The assertion helpers, against a fake tree that can be told to lie (plan D16). No Docker.

The helper's whole job is to be un-foolable, so it is tested by fooling it. Every failing
case here corresponds to a switch on `stubs.fake_tree.FakeMcp`, and the important one is
`skip_put`: a server that reports a successful write and performs none. That is not a
hypothetical — `_guarded_write` builds its `before`/`after` from the **local dict**
(`gramps_client.py:699-704`), so deleting `self._put_person(...)` leaves seven write tools
reporting success while changing nothing, and the obvious `before != after` check certifies it.
"""

from __future__ import annotations

from typing import Any

import pytest
from harness.assertions import assert_guarded_write, assert_refusal, payload, resolve_path
from harness.docker_util import ProbeError
from stubs.fake_tree import FakeMcp, FakeRest, FakeTree

FIRST_NAME = "primary_name.first_name"
SURNAME = "primary_name.surname_list.0.surname"


@pytest.fixture
def tree() -> FakeTree:
    return FakeTree()


@pytest.fixture
def rest(tree: FakeTree) -> FakeRest:
    return FakeRest(tree)


@pytest.fixture
def mcp(tree: FakeTree) -> FakeMcp:
    return FakeMcp(tree)


def rename(rest: FakeRest, mcp: FakeMcp, **kwargs: Any) -> Any:
    """The canonical guarded write: one person, one renamed field, nothing else may move."""
    return assert_guarded_write(
        rest,
        mcp,
        "gramps_set_first_name",
        {"gramps_id": "I0001", "first_name": "Reinhold"},
        expect_delta={},
        self_report="person",
        expect_person={"I0001": {FIRST_NAME: "Reinhold"}},
        **kwargs,
    )


# -- reading the wire ----------------------------------------------------------------


def test_a_bare_str_tool_is_read_from_structured_content(mcp: FakeMcp) -> None:
    """Measured, and the reverse of what the plan assumed: only the three `-> str` tools
    carry `structuredContent`, as `{"result": …}`."""
    assert payload(mcp.call("gramps_add_person", {"first_name": "Neu", "surname": "Brehmer"})) == (
        "I0003"
    )


def test_a_dict_tool_is_read_from_the_text_part(mcp: FakeMcp) -> None:
    """`dict`-returning tools carry no `structuredContent` at all, so the JSON in the text
    part is the only report there is."""
    result = mcp.call("gramps_set_first_name", {"gramps_id": "I0001", "first_name": "Reinhold"})

    assert payload(result)["gramps_id"] == "I0001"


def test_a_list_tool_is_read_as_one_element_per_content_part(mcp: FakeMcp) -> None:
    """A `list` tool emits one text part per element — joining them and parsing once would
    raise, so the helper has to parse per part."""
    people = payload(mcp.call("gramps_list_people", {}))

    assert [person["gramps_id"] for person in people] == ["I0000", "I0001", "I0002"]


def test_a_field_path_walks_lists_by_index() -> None:
    record = {"primary_name": {"surname_list": [{"surname": "Brehmer"}]}}

    assert resolve_path(record, SURNAME) == "Brehmer"


# -- the guarded write ---------------------------------------------------------------


def test_a_real_write_passes_and_reports_the_delta(rest: FakeRest, mcp: FakeMcp) -> None:
    written = rename(rest, mcp)

    assert written.delta == {}
    assert rest.tree.person("I0001")["primary_name"]["first_name"] == "Reinhold"


def test_a_write_that_never_reaches_the_tree_is_caught(rest: FakeRest, mcp: FakeMcp) -> None:
    """D16 in one test. The report is untouched — only the re-read over REST disagrees."""
    mcp.skip_put = True

    with pytest.raises(AssertionError, match=FIRST_NAME):
        rename(rest, mcp)


def test_the_discarded_check_would_have_passed_that_same_write(mcp: FakeMcp) -> None:
    """Why `before != after` is gone rather than merely supplemented.

    Under the exact mutation above, the tool's report is *identical* to the honest one: it
    snapshots the local dict it mutated, so before and after still differ. Anything reading
    the report alone — including the obvious guard — calls this a successful write.
    """
    mcp.skip_put = True

    reported = payload(
        mcp.call("gramps_set_first_name", {"gramps_id": "I0001", "first_name": "Reinhold"})
    )

    assert reported["before"] != reported["after"]
    assert rest_untouched(mcp), "the tree changed after all — the premise no longer holds"


def rest_untouched(mcp: FakeMcp) -> bool:
    return mcp.tree.person("I0001")["primary_name"]["first_name"] == "Cordt"


def test_a_fabricated_before_is_caught(rest: FakeRest, mcp: FakeMcp) -> None:
    """The tool wrote, but claims the field already held the new value — which would let a
    no-op tool pass for a write on the next run."""
    mcp.lie_before = True

    with pytest.raises(AssertionError, match="before"):
        rename(rest, mcp)


def test_a_report_that_does_not_match_the_write_is_caught(rest: FakeRest, mcp: FakeMcp) -> None:
    """The write landed, so the re-read is satisfied — the tool simply tells a different
    story about it. Worth catching separately: a use case that chains off the reported value
    (`after` -> the next call's argument) would carry the wrong one forward while the tree
    looks perfect."""
    mcp.lie_after = True

    with pytest.raises(AssertionError, match="reported after"):
        rename(rest, mcp)


def test_a_report_about_a_different_person_is_caught(rest: FakeRest, mcp: FakeMcp) -> None:
    mcp.wrong_id = True

    with pytest.raises(AssertionError, match="I9999"):
        rename(rest, mcp)


def test_a_person_write_without_an_expectation_is_refused(rest: FakeRest, mcp: FakeMcp) -> None:
    """Not an assertion failure — a usage error. `expect_person` is what makes the helper
    falsifiable, so a caller who omits it must not get a green test out of it."""
    with pytest.raises(ProbeError, match="expect_person"):
        assert_guarded_write(
            rest,
            mcp,
            "gramps_set_first_name",
            {"gramps_id": "I0001", "first_name": "Reinhold"},
            expect_delta={},
            self_report="person",
        )


def test_an_unexpected_movement_of_the_tree_is_caught(rest: FakeRest, mcp: FakeMcp) -> None:
    """The independent oracle, not the tool's own count guard: the tool here reports nothing
    about counts at all."""
    with pytest.raises(AssertionError, match="people"):
        assert_guarded_write(
            rest,
            mcp,
            "gramps_add_person",
            {"first_name": "Neu", "surname": "Brehmer"},
            expect_delta={},
            self_report="id",
            id_namespace="people",
        )


def test_a_failed_call_is_never_a_guarded_write(rest: FakeRest, mcp: FakeMcp) -> None:
    with pytest.raises(AssertionError, match="Unknown tool"):
        assert_guarded_write(
            rest, mcp, "gramps_no_such_tool", {}, expect_delta={}, self_report="unguarded"
        )


# -- the other self-report shapes ----------------------------------------------------


def test_a_new_id_must_resolve_in_the_tree(rest: FakeRest, mcp: FakeMcp) -> None:
    written = assert_guarded_write(
        rest,
        mcp,
        "gramps_add_person",
        {"first_name": "Neu", "surname": "Brehmer"},
        expect_delta={"people": 1},
        self_report="id",
        id_namespace="people",
    )

    assert written.payload == "I0003"


def test_an_id_that_does_not_resolve_is_caught(rest: FakeRest, mcp: FakeMcp) -> None:
    """A well-shaped id is not evidence, and neither is a correct count delta — the person
    really was created here, just not under the id the tool handed back. Only the lookup
    catches that, and every later step of a use case would key off the wrong id."""
    mcp.phantom_id = True

    with pytest.raises(AssertionError, match="I9999"):
        assert_guarded_write(
            rest,
            mcp,
            "gramps_add_person",
            {"first_name": "Neu", "surname": "Brehmer"},
            expect_delta={"people": 1},
            self_report="id",
            id_namespace="people",
        )


def test_a_delete_reports_one_fewer_and_the_tree_agrees(rest: FakeRest, mcp: FakeMcp) -> None:
    """`expect_removed` is what makes "one fewer" mean *this* one — see `test_00_movement.py`
    for the delete that satisfies the count and takes the wrong person."""
    written = assert_guarded_write(
        rest,
        mcp,
        "gramps_delete_person",
        {"gramps_id": "I0002", "confirm": True},
        expect_delta={"people": -1},
        expect_removed={"people": ["I0002"]},
        self_report="delete",
    )

    assert written.payload["deleted"] is True


def test_a_bulk_write_checks_every_person_it_claims(rest: FakeRest, mcp: FakeMcp) -> None:
    assert_guarded_write(
        rest,
        mcp,
        "gramps_set_gender_bulk",
        {"items": [{"gramps_id": "I0000", "gender": 2}, {"gramps_id": "I0001", "gender": 2}]},
        expect_delta={},
        self_report="bulk",
        expect_person={"I0000": {"gender": 2}, "I0001": {"gender": 2}},
    )


def test_a_delete_that_miscounts_itself_is_caught(rest: FakeRest, mcp: FakeMcp) -> None:
    """The person really is gone, so the independent delta is right — the tool's own
    arithmetic is what is wrong, and that arithmetic is the product's guard."""
    mcp.lie_delete_counts = True

    with pytest.raises(AssertionError, match="not a delete of exactly one"):
        assert_guarded_write(
            rest,
            mcp,
            "gramps_delete_person",
            {"gramps_id": "I0002", "confirm": True},
            expect_delta={"people": -1},
            expect_removed={"people": ["I0002"]},
            self_report="delete",
        )


def test_a_bulk_write_whose_own_guard_failed_is_caught(rest: FakeRest, mcp: FakeMcp) -> None:
    """`count_guard_ok` is *reported*, not raised (`gramps_client.py:737-743`) — a batch that
    tripped its own guard still comes back as a successful tool call."""
    mcp.break_bulk_guard = True

    with pytest.raises(AssertionError, match="count_guard_ok"):
        assert_guarded_write(
            rest,
            mcp,
            "gramps_set_gender_bulk",
            {"items": [{"gramps_id": "I0000", "gender": 2}]},
            expect_delta={},
            self_report="bulk",
            expect_person={"I0000": {"gender": 2}},
        )


def test_an_identity_swap_that_leaves_every_count_alone_is_caught(
    rest: FakeRest, mcp: FakeMcp
) -> None:
    """One object destroyed and one created nets to zero in every count. `expect_delta={}` is
    the most common expectation in the suite, so this is the shape a counts-only guard would
    wave through most often."""
    with pytest.raises(AssertionError, match="identity"):
        assert_guarded_write(
            rest,
            mcp,
            "gramps_replace_person",
            {"gramps_id": "I0002"},
            expect_delta={},
            self_report="unguarded",
        )


def test_a_bulk_write_that_never_reaches_the_tree_is_caught(rest: FakeRest, mcp: FakeMcp) -> None:
    mcp.skip_put = True

    with pytest.raises(AssertionError, match="gender"):
        assert_guarded_write(
            rest,
            mcp,
            "gramps_set_gender_bulk",
            {"items": [{"gramps_id": "I0000", "gender": 2}]},
            expect_delta={},
            self_report="bulk",
            expect_person={"I0000": {"gender": 2}},
        )


def test_a_counts_reporting_tool_is_checked_against_the_oracle(
    rest: FakeRest, mcp: FakeMcp
) -> None:
    assert_guarded_write(
        rest,
        mcp,
        "gramps_import_file",
        {"filename": "synthetic-tree.gramps"},
        expect_delta={"people": 1},
        self_report="counts",
    )


def test_a_counts_report_that_hides_the_growth_is_caught(rest: FakeRest, mcp: FakeMcp) -> None:
    """`before == after` in the report reads as "the import added nothing" — which is a
    documented, *successful* outcome of `gramps_import_file`, so nothing else would object."""
    mcp.lie_counts = True

    with pytest.raises(AssertionError, match="reported before"):
        assert_guarded_write(
            rest,
            mcp,
            "gramps_import_file",
            {"filename": "synthetic-tree.gramps"},
            expect_delta={"people": 1},
            self_report="counts",
        )


def test_an_unguarded_tool_may_not_claim_a_delta(rest: FakeRest, mcp: FakeMcp) -> None:
    """`add_child_to_family` takes no count snapshot and returns no before/after
    (`gramps_client.py:979-998`), so the helper has nothing to cross-check — and says so
    rather than pretending it checked."""
    with pytest.raises(ProbeError, match="unguarded"):
        assert_guarded_write(
            rest,
            mcp,
            "gramps_add_child_to_family",
            {"family_id": "F0000", "child_id": "I0002"},
            expect_delta={"people": 1},
            self_report="unguarded",
        )


def test_an_unguarded_tool_still_gets_the_independent_delta(rest: FakeRest, mcp: FakeMcp) -> None:
    written = assert_guarded_write(
        rest,
        mcp,
        "gramps_add_child_to_family",
        {"family_id": "F0000", "child_id": "I0002"},
        expect_delta={},
        self_report="unguarded",
    )

    assert written.payload == {"family_id": "F0000", "child_id": "I0002"}


# -- refusals ------------------------------------------------------------------------


def test_a_refusal_is_an_error_carrying_the_authored_fragment(rest: FakeRest, mcp: FakeMcp) -> None:
    refused = assert_refusal(
        rest,
        mcp,
        "gramps_delete_person",
        {"gramps_id": "I0002"},
        contains="requires confirm=True",
    )

    assert refused.is_error


def test_a_refusal_with_the_wrong_text_is_caught(rest: FakeRest, mcp: FakeMcp) -> None:
    with pytest.raises(AssertionError, match="not in"):
        assert_refusal(
            rest, mcp, "gramps_delete_person", {"gramps_id": "I0002"}, contains="grade must be >= 1"
        )


def test_a_call_that_succeeds_is_not_a_refusal(rest: FakeRest, mcp: FakeMcp) -> None:
    with pytest.raises(AssertionError, match="did not refuse"):
        assert_refusal(
            rest,
            mcp,
            "gramps_delete_person",
            {"gramps_id": "I0002", "confirm": True},
            contains="requires confirm=True",
        )


def test_a_refusal_that_moved_the_tree_is_caught(rest: FakeRest, mcp: FakeMcp) -> None:
    """A refusal that changed something is the worst outcome of the three, and the only one
    a text assertion alone would call green."""
    mcp.leaky_refusal = True

    with pytest.raises(AssertionError, match="people"):
        assert_refusal(
            rest,
            mcp,
            "gramps_import_file",
            {"filename": "../escape.gramps"},
            contains="Path escapes backup directory",
        )
