# Generated by OrchestKit Claude Plugin
# Created: 2026-08-01

"""The two live regressions worth a nightly (plan T3.3). Docker + Gramps Web.

**The 429 that broke the wipe on a cold client** is the reason this file cannot be a pass/fail
check. Gramps Web limits the token endpoints to 1/second, and `delete_all_objects` used to mint
two tokens without a pause: the lazy login inside `object_counts()`, then a mandatory fresh
one. Shipped as `v0.5.1` under the `conditional-fresh` design.

Reverting only the mint guard leaves the retry in place — so the wipe still *succeeds*, with
three token POSTs and a 429 in the middle. A test that asserted "the wipe worked" would be
green on that revert. Only the count sees it, which makes `TokenAudit` load-bearing and its
positive control session-fatal: without proof that the parser can find a request it should
find, every count is `0 == 0` and stays green with the fix deleted.

**`IMPORT_MIN_SETTLE`** is the other direction: an import that adds nothing must be reported as
a success with `added=0` once the counts have held steady, never as a timeout. The constant is
what separates "this file changed nothing" from "the import has not started yet", and it is
only observable against a live server.
"""

from __future__ import annotations

import json
import time
from collections.abc import Iterator

import pytest
from harness.backup_dir import BackupDir
from harness.docker_util import inspect_container
from harness.gramps_instance import OWNER_PW, OWNER_USER, ROLE_OWNER, GrampsInstance
from harness.mcp_container import ImageRef, McpContainer, container_name
from harness.rest import GrampsRest
from harness.runid import new_runid
from harness.token_audit import TokenAudit

from gramps_client import IMPORT_MIN_SETTLE

EMPTY_IMPORT = "adds-nothing.gramps"

# The shortest settle window that still separates "this import added nothing" from "this
# import has not begun". Well under the shipped 30 s, because this is a floor and not a
# restatement of the tuning decision.
MEANINGFUL_SETTLE_S = 10

# A *valid* Gramps XML database with nothing in it. Measured 2026-08-01: a zero-byte file is
# refused by the server with `400 BAD REQUEST`, which is a different regression from the one
# this test is about — "the import failed" rather than "the import changed nothing".
EMPTY_DATABASE = b"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE database PUBLIC "-//Gramps//DTD Gramps XML 1.7.2//EN"
"http://gramps-project.org/xml/1.7.2/grampsxml.dtd">
<database xmlns="http://gramps-project.org/xml/1.7.2/">
  <header>
    <created date="2000-01-01" version="6.0.8"/>
    <researcher>
    </researcher>
  </header>
</database>
"""


def container_ip(name: str) -> str:
    """The address the access log will attribute this container's requests to."""
    found = inspect_container(name, "{{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}}")
    addresses = [part for part in found.split() if part]

    assert len(addresses) == 1, f"{name} is on {len(addresses)} networks: {addresses}"
    return addresses[0]


@pytest.fixture(scope="module")
def instance() -> Iterator[GrampsInstance]:
    started = GrampsInstance(new_runid())
    started.start()
    assert started.add_user(OWNER_USER, OWNER_PW, ROLE_OWNER)["rc"] == 0
    try:
        yield started
    finally:
        started.teardown()


@pytest.fixture(scope="module")
def backup(tmp_path_factory: pytest.TempPathFactory) -> BackupDir:
    staged = BackupDir(tmp_path_factory.mktemp("regressions") / "backup")
    staged.reset()
    (staged.path / EMPTY_IMPORT).write_bytes(EMPTY_DATABASE)
    return staged


def spawn(
    instance: GrampsInstance, image: ImageRef, label: str, backup: BackupDir | None = None
) -> McpContainer:
    env = {
        "GRAMPS_BASE_URL": instance.internal_url,
        "GRAMPS_USERNAME": OWNER_USER,
        "GRAMPS_PASSWORD": OWNER_PW,
        "GRAMPS_ENABLE_DESTRUCTIVE": "1",
    }
    if backup is not None:
        env["GRAMPS_BACKUP_DIR"] = "/data"
    return McpContainer(
        container_name(instance.runid, label),
        image.run_reference,
        env,
        network=instance.network,
        mounts=((str(backup.path), "/data"),) if backup is not None else (),
        runid=instance.runid,
    )


@pytest.fixture(scope="module")
def seeded(instance: GrampsInstance, mcp_image: ImageRef) -> None:
    """Two people, added by a container that is then thrown away.

    The wipe has to run against a client that has never minted a token, and a container that
    seeded the tree is by definition warm. Seeding over REST from the host would keep it cold
    too, but the oracle cannot create people — and a second container is closer to the real
    situation anyway: a fresh client process against a tree that already exists.
    """
    seeder = spawn(instance, mcp_image, "seeder")
    try:
        for index in range(2):
            added = seeder.call(
                "gramps_add_person",
                {"first_name": f"Kalt{index}", "surname": "Start", "gender": index},
            )
            assert not added.is_error, added.text
    finally:
        assert seeder.close() == [], "the seeding container outlived its fixture"


def test_a_cold_client_wipes_the_tree_with_exactly_one_token(
    instance: GrampsInstance, mcp_image: ImageRef, seeded: None
) -> None:
    """The `v0.5.1` regression, asserted as a count rather than as an outcome.

    Three assertions, and the middle one is the test: the wipe worked, it cost exactly one
    token POST, and that POST was not a 429. Drop the middle one and reverting the mint guard
    is invisible; drop the last and a 200-after-429 retry reads as a clean run.
    """
    audit = TokenAudit(instance.token_post_log)
    rest = GrampsRest(instance.url, OWNER_USER, OWNER_PW)
    control = audit.positive_control(lambda: rest.token(force=True))

    assert control["passed"], f"the access log cannot see a known-good mint: {control}"

    cold = spawn(instance, mcp_image, "cold")
    try:
        cold.start()
        client_ip = container_ip(cold.name)
        mark = audit.mark()
        wiped = cold.call(
            "gramps_delete_all_objects",
            {"confirm": True, "expected_count": rest.total()},
            timeout=600,
        )
    finally:
        assert cold.close() == [], "the MCP container outlived its test"

    minted = [post for post in audit.since(mark) if post.ip == client_ip]

    assert not wiped.is_error, wiped.text
    assert rest.total() == 0
    assert [post.status for post in minted] == [200], f"cold-client token POSTs: {minted}"


def test_an_import_that_adds_nothing_settles_into_a_success(
    instance: GrampsInstance, mcp_image: ImageRef, backup: BackupDir
) -> None:
    """A file that moves no count is a success with `added=0`, and it takes `IMPORT_MIN_SETTLE`.

    The elapsed time is asserted deliberately. Without the settle window the same call would
    have to answer immediately, and "no counts moved yet" is indistinguishable from "the import
    has not started" — the shape that would report a real import as an empty one.
    """
    mcp = spawn(instance, mcp_image, "settle", backup)
    started = time.monotonic()
    try:
        imported = mcp.call("gramps_import_file", {"filename": EMPTY_IMPORT}, timeout=300)
    finally:
        assert mcp.close() == [], "the MCP container outlived its test"
    elapsed = time.monotonic() - started

    report = json.loads(imported.text)

    assert not imported.is_error, imported.text
    # `added` is a delta per namespace, not a total — every one of them has to be untouched,
    # because a sum could hide a namespace that grew against one that shrank.
    assert set(report["added"].values()) == {0}, report["added"]
    assert report["before"] == report["after"]
    assert elapsed >= IMPORT_MIN_SETTLE, f"settled after {elapsed:.1f}s, below the window"
    # Asserted against the constant *and* about it. Compared only against itself, this test
    # would pass a window of zero — the exact revert that makes "nothing was added" and "the
    # import has not started" the same answer.
    assert IMPORT_MIN_SETTLE >= MEANINGFUL_SETTLE_S, (
        f"a {IMPORT_MIN_SETTLE}s window cannot tell an empty import from an unstarted one"
    )
