# Generated by OrchestKit Claude Plugin
# Created: 2026-08-02

"""The family graph against a live server: parent slots, reverse references, traversal. Docker.

Fourteen cases of the matrix's 43, selected in `phase-4/triage-product-risk.md`. Six of them are
only writable because T4.5 grew the fixture — a remarriage, a child with two parent families, a
fourth generation and a father-slot single parent — and `cast.GRAPH` carries the **measured**
order of `family_list` / `parent_family_list`, which is a server decision this module asserts
rather than chooses.

The through-line is the reverse reference. Every write tool here PUTs only the *Family* object,
and every read tool walks the *person*-side `family_list` / `parent_family_list`
(`gramps_client.py:1187,1208,1243,1254`). Three docstrings promise the API maintains the link
between them. Nothing had checked it: a mock returns whatever it was told, and both halves would
agree with each other while disagreeing with the server.
"""

from __future__ import annotations

import pytest
from fixtures import cast
from harness.assertions import assert_guarded_write, assert_refusal, payload

pytestmark = pytest.mark.gramps


def _in_a_family() -> set[str]:
    return {
        gramps_id
        for family in cast.FAMILIES
        for gramps_id in (family["father"], family["mother"], *family["children"])
        if gramps_id
    }


def loose(gender: int) -> list[str]:
    """Unattached people of one sex, so a new family is the only one they are in."""
    attached = _in_a_family()
    return sorted(
        person["gramps_id"]
        for person in cast.PEOPLE
        if person["gender"] == gender and person["gramps_id"] not in attached
    )


def family_with(children: int, both_slots: bool = True) -> dict:
    return next(
        family
        for family in cast.FAMILIES
        if len(family["children"]) == children
        and (bool(family["father"]) and bool(family["mother"])) == both_slots
    )


def handle_of(rest, gramps_id: str) -> str:
    return str(rest.person(gramps_id)["handle"])


def parents_of(gramps_id: str) -> list[str]:
    return [
        slot
        for family in cast.FAMILIES
        if gramps_id in family["children"]
        for slot in (family["father"], family["mother"])
        if slot
    ]


def children_of(gramps_id: str) -> list[str]:
    return [
        child
        for family in cast.FAMILIES
        if gramps_id in (family["father"], family["mother"])
        for child in family["children"]
    ]


def ancestors_to(gramps_id: str, grade: int) -> list[str]:
    """What `get_ancestors` must return, derived from `cast.FAMILIES` — including repeats.

    The product does **not** de-duplicate (`gramps_client.py:1203-1214`), so a person reachable by
    two routes appears twice; flattening to a set here would hide exactly that.
    """
    if grade < 1:
        return []
    found = []
    for parent in parents_of(gramps_id):
        found.append(parent)
        found.extend(ancestors_to(parent, grade - 1))
    return sorted(found)


def flatten(node: dict, key: str) -> list[str]:
    return sorted(
        [child["gramps_id"] for child in node[key]]
        + [deeper for child in node[key] for deeper in flatten(child, key)]
    )


class TestTheParentSlotsAreSlotsNotSexes:
    """`add_family` assigns father/mother by *argument order*, reordering only for the one
    ♂-second case (`gramps_client.py:227-236`). If the server ever normalised slots by sex, the
    documented rule would become a lie the calling model acts on — and `server.py:135-141` sells
    that rule to it explicitly. Marked `# DO NOT RELAX` in the design for that reason.
    """

    def _family_of(self, seeded_tree, written) -> dict:
        return seeded_tree.rest.by_gramps_id("families", written.payload)

    def _add(self, seeded_tree, spouse_a: str, spouse_b: str | None = None):
        arguments = {"spouse_a_id": spouse_a}
        if spouse_b is not None:
            arguments["spouse_b_id"] = spouse_b
        return assert_guarded_write(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_add_family",
            arguments,
            expect_delta={"families": 1},
            self_report="id",
            id_namespace="families",
        )

    def test_two_women_keep_the_order_they_were_given(self, seeded_tree) -> None:
        first, second = loose(0)[:2]

        family = self._family_of(seeded_tree, self._add(seeded_tree, first, second))

        assert family["father_handle"] == handle_of(seeded_tree.rest, first)
        assert family["mother_handle"] == handle_of(seeded_tree.rest, second)

    def test_a_man_named_second_after_an_unknown_lands_in_the_mother_slot(
        self, seeded_tree
    ) -> None:
        """The reordering branch fires on ♂ *second* only when the first is female
        (`:232-235`); an Unknown first leaves the man where he was put."""
        unknown = loose(2)[0]
        man = loose(1)[0]

        family = self._family_of(seeded_tree, self._add(seeded_tree, unknown, man))

        assert family["father_handle"] == handle_of(seeded_tree.rest, unknown)
        assert family["mother_handle"] == handle_of(seeded_tree.rest, man)

    def test_a_lone_woman_gets_the_mother_slot_and_an_empty_father(self, seeded_tree) -> None:
        alone = loose(0)[2]

        family = self._family_of(seeded_tree, self._add(seeded_tree, alone))

        assert not family["father_handle"]
        assert family["mother_handle"] == handle_of(seeded_tree.rest, alone)

    def test_the_same_person_may_occupy_both_slots(self, seeded_tree) -> None:
        """A behaviour pin, not an endorsement: `add_family` has no both-slots check
        (`:955-974`) while `set_family_parent` does (`:1018-1022`). The asymmetry is real and
        this is where it is written down."""
        twice = loose(1)[1]

        family = self._family_of(seeded_tree, self._add(seeded_tree, twice, twice))

        assert (
            family["father_handle"] == family["mother_handle"] == handle_of(seeded_tree.rest, twice)
        )


class TestTheWriteToolsAndTheirReverseReferences:
    def test_adding_a_child_keeps_both_parents_and_every_sibling(self, seeded_tree) -> None:
        """The families instance of the projection pin (`triage-product-risk.md` §1): `get_family`
        reads the collection projection (`:667-671`) and `_put_family` writes it back whole, and a
        partial body blanks every omitted field. Measured complete today; this notices otherwise.

        `self_report="unguarded"` makes `expect_record` mandatory (`gate.py:36,84-92`) — this
        tool's report is an echo of its own arguments, which `self_report.py:66` refuses to treat
        as evidence."""
        family = family_with(children=3)
        newcomer = loose(1)[2]
        before = seeded_tree.rest.by_gramps_id("families", family["gramps_id"])
        siblings = [ref["ref"] for ref in before["child_ref_list"]]

        assert_guarded_write(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_add_child_to_family",
            {"family_id": family["gramps_id"], "child_id": newcomer},
            expect_delta={},
            self_report="unguarded",
            expect_record={
                "families": {
                    family["gramps_id"]: {
                        "father_handle": before["father_handle"],
                        "mother_handle": before["mother_handle"],
                        "child_ref_list.3.ref": handle_of(seeded_tree.rest, newcomer),
                    }
                }
            },
        )

        after = seeded_tree.rest.by_gramps_id("families", family["gramps_id"])
        assert [ref["ref"] for ref in after["child_ref_list"]][:3] == siblings
        assert after["child_ref_list"][-1]["frel"] == cast.GRAPH["childref_rel"]

    def test_filling_an_empty_parent_slot_reaches_the_person_side_too(self, seeded_tree) -> None:
        """`gramps_client.py:1008-1009` promises "the API maintains the person's reverse
        family_list reference". The tool PUTs only the Family. If the promise were false the new
        father would sit in the slot while `get_relations` on him showed no family at all — write
        tools and read tools disagreeing, with nothing in the product to notice."""
        family = next(f for f in cast.FAMILIES if not f["father"] and f["mother"])
        newcomer = loose(1)[3]

        assert_guarded_write(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_set_family_parent",
            {
                "family_id": family["gramps_id"],
                "gramps_id": newcomer,
                "role": "father",
            },
            expect_delta={},
            self_report="unguarded",
            expect_record={
                "families": {
                    family["gramps_id"]: {
                        "father_handle": handle_of(seeded_tree.rest, newcomer),
                        "mother_handle": handle_of(seeded_tree.rest, family["mother"]),
                    }
                }
            },
        )

        relations = payload(seeded_tree.mcp.call("gramps_get_relations", {"gramps_id": newcomer}))
        assert [entry["family_gramps_id"] for entry in relations["families"]] == [
            family["gramps_id"]
        ]

    def test_removing_a_child_scrubs_the_reverse_reference_and_spares_the_siblings(
        self, seeded_tree
    ) -> None:
        """`:1037-1038` promises the child's `parent_family_list` is maintained. If it is not, the
        removal looks done from the family side and never happened from the read side —
        `get_ancestors` on the removed child still names the old parents."""
        family = family_with(children=3)
        leaving, *staying = family["children"]

        assert_guarded_write(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_remove_child_from_family",
            {"family_id": family["gramps_id"], "child_id": leaving},
            expect_delta={},
            self_report="unguarded",
            expect_record={
                "families": {
                    family["gramps_id"]: {
                        "child_ref_list.0.ref": handle_of(seeded_tree.rest, staying[0]),
                        "child_ref_list.1.ref": handle_of(seeded_tree.rest, staying[1]),
                    }
                }
            },
        )

        assert seeded_tree.rest.person(leaving)["parent_family_list"] == []
        assert (
            payload(seeded_tree.mcp.call("gramps_get_ancestors", {"gramps_id": leaving}))["parents"]
            == []
        )

    def test_deleting_a_childless_family_scrubs_it_off_both_parents(self, seeded_tree) -> None:
        """`:1130-1131` promises the parents' `family_list` is maintained. A surviving dangling
        handle makes `get_relations` on an ex-parent walk `_get_family_by_handle` (`:1155-1156`,
        no error handling anywhere in the traversal) into a raw 404 — a user-visible crash from a
        delete that reported success."""
        family = family_with(children=0)

        assert_guarded_write(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_delete_family",
            {"family_id": family["gramps_id"], "confirm": True},
            expect_delta={"families": -1},
            expect_removed={"families": [family["gramps_id"]]},
            self_report="delete",
        )

        for parent in (family["father"], family["mother"]):
            assert seeded_tree.rest.person(parent)["family_list"] == []
            assert (
                payload(seeded_tree.mcp.call("gramps_get_relations", {"gramps_id": parent}))[
                    "families"
                ]
                == []
            )


class TestReadingTheGraph:
    def test_a_child_of_two_families_reports_every_parent_in_the_measured_order(
        self, seeded_tree
    ) -> None:
        """`parent_family_order` in `cast.GRAPH` was read back off the instance at fixture-build
        time, never chosen — it decides this payload's order and is the server's decision."""
        adopted = cast.GRAPH["adopted_child"]

        tree = payload(
            seeded_tree.mcp.call("gramps_get_ancestors", {"gramps_id": adopted["gramps_id"]})
        )

        assert sorted(node["gramps_id"] for node in tree["parents"]) == ancestors_to(
            adopted["gramps_id"], 1
        )
        assert len(tree["parents"]) == 3, "two families, one of them single-parent"

    def test_a_remarriage_merges_the_children_of_both_marriages(self, seeded_tree) -> None:
        """`_build_descendant_node` walks **every** entry of `family_list` (`:1187`). A server
        that stopped maintaining the second entry would silently drop the half-siblings, and the
        count would still look plausible."""
        remarried = cast.GRAPH["remarried"]

        tree = payload(
            seeded_tree.mcp.call("gramps_get_descendants", {"gramps_id": remarried["gramps_id"]})
        )

        expected = sorted(
            child
            for family in cast.FAMILIES
            if family["gramps_id"] in remarried["family_order"]
            for child in family["children"]
        )
        assert sorted(node["gramps_id"] for node in tree["children"]) == expected
        assert len(remarried["family_order"]) == 2, "the fixture's remarriage is the premise"

    def test_ascending_the_whole_lineage_repeats_whoever_two_routes_reach(
        self, seeded_tree
    ) -> None:
        """Pins the absence of de-duplication (`:1203-1214`) rather than papering over it.

        The grade is 3, not 2, and that is a fact about the fixture rather than a preference:
        the deepest person's parent has three parents of their own but they are all distinct, so
        a duplicate first appears one level further up, where two of those three turn out to be
        siblings and hand back the same couple twice. `ancestors_to` reproduces the repeat
        deliberately — collapsing either side to a set is what would make this vacuous."""
        deepest = cast.GRAPH["deepest"]

        tree = payload(
            seeded_tree.mcp.call("gramps_get_ancestors", {"gramps_id": deepest, "grade": 3})
        )

        reached = flatten(tree, "parents")
        assert reached == ancestors_to(deepest, 3)
        assert len(reached) > len(set(reached)), (
            "nobody was reached twice, so this fixture no longer pins the missing de-duplication"
        )

    def test_descending_far_enough_reaches_the_fourth_generation(self, seeded_tree) -> None:
        """The only consumer of the generation T4.5 grew, and the case the matrix had to block
        until it existed: with three generations, grade 2 already saturates and a broken ceiling
        is invisible. Four generations means the deepest person sits **three** steps below the
        root, so grade 2 must not reach them and grade 3 must."""
        assert cast.GRAPH["generations"] == 4
        root = next(
            person["gramps_id"]
            for person in cast.PEOPLE
            if person["surname"] == cast.GRAPH["lineage_surname"]
            and not parents_of(person["gramps_id"])
            and children_of(person["gramps_id"])
        )

        shallow = payload(
            seeded_tree.mcp.call("gramps_get_descendants", {"gramps_id": root, "grade": 2})
        )
        deep = payload(
            seeded_tree.mcp.call("gramps_get_descendants", {"gramps_id": root, "grade": 3})
        )

        assert cast.GRAPH["deepest"] not in flatten(shallow, "children")
        assert cast.GRAPH["deepest"] in flatten(deep, "children")


class TestTheRefusalsWhoseWordingThisRepoAuthored:
    @pytest.mark.refusal
    @pytest.mark.parametrize("tool", ["gramps_get_ancestors", "gramps_get_descendants"])
    def test_a_grade_below_one_is_refused_by_both_traversals(self, seeded_tree, tool) -> None:
        """Two call sites, two identical raises (`:1196`, `:1218`) — a fix applied to one is the
        regression this catches. The `"two"` sub-case the matrix wanted is pydantic prose, which
        `test_00_vocabulary.py` rejects, so it is not here."""
        assert_refusal(
            seeded_tree.rest,
            seeded_tree.mcp,
            tool,
            {"gramps_id": cast.GRAPH["deepest"], "grade": 0},
            contains="grade must be >= 1",
        )

    @pytest.mark.refusal
    def test_a_role_that_is_neither_slot_is_refused_and_changes_nothing(self, seeded_tree) -> None:
        family = next(f for f in cast.FAMILIES if not f["father"] and f["mother"])

        assert_refusal(
            seeded_tree.rest,
            seeded_tree.mcp,
            "gramps_set_family_parent",
            {
                "family_id": family["gramps_id"],
                "gramps_id": loose(1)[0],
                "role": "Father",
            },
            contains="role must be 'father' or 'mother', got ",
            expect_record={
                "families": {
                    family["gramps_id"]: {
                        "mother_handle": handle_of(seeded_tree.rest, family["mother"])
                    }
                }
            },
        )
