# Generated by OrchestKit Claude Plugin
# Created: 2026-07-30

"""The backup directory is reset to a known set before every run (plan D17). No Docker.

The directory is a bind mount, so it survives the container, the test and the run. Two
consequences the suite has to defend against:

* **A leftover export makes "the model exported a file" pass when it never ran.** So a test
  never asks "is there a file?", it asks "did *this* file appear in this call", against a
  listing taken before it.
* **`resolve_export_path` defaults to a 1-second-resolution timestamp**
  (`backup_store.py:16-20`), so two default exports inside one second silently overwrite each
  other. Every export assertion therefore names its file.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from harness.backup_dir import MANIFEST_FILE, BackupDir, digest_of, load_manifest
from harness.docker_util import ProbeError

FIXTURES = Path(__file__).parent / "fixtures"


@pytest.fixture
def sources(tmp_path: Path) -> Path:
    source_dir = tmp_path / "src"
    source_dir.mkdir()
    (source_dir / "tree.gramps").write_bytes(b"<?xml version='1.0'?><database/>")
    return source_dir


@pytest.fixture
def manifest(sources: Path) -> dict[str, str]:
    return {"tree.gramps": digest_of((sources / "tree.gramps").read_bytes())}


@pytest.fixture
def backup(tmp_path: Path, sources: Path, manifest: dict[str, str]) -> BackupDir:
    return BackupDir(tmp_path / "backup", source_dir=sources, manifest=manifest)


# -- the reset -----------------------------------------------------------------------


def test_the_reset_leaves_exactly_the_declared_inputs(backup: BackupDir) -> None:
    backup.path.mkdir(parents=True)
    (backup.path / "gramps-export-20260730-120000.gramps").write_bytes(b"left over")

    backup.reset()

    assert set(backup.listing()) == {"tree.gramps"}


def test_the_reset_makes_the_directory_writable_by_the_container(backup: BackupDir) -> None:
    """The MCP container runs as a different uid than the test process, and an export lands
    on the host through the mount — 0777 is the whole reason `test_05` chmods by hand today."""
    backup.reset()

    assert backup.path.stat().st_mode & 0o777 == 0o777


def test_a_missing_input_stops_the_run(backup: BackupDir, sources: Path) -> None:
    (sources / "tree.gramps").unlink()

    with pytest.raises(ProbeError, match="tree.gramps"):
        backup.reset()


def test_an_input_that_drifted_from_the_manifest_stops_the_run(
    backup: BackupDir, sources: Path
) -> None:
    """A silently different input is the worst case: every count assertion downstream is
    calibrated against the committed one."""
    (sources / "tree.gramps").write_bytes(b"<?xml version='1.0'?><database><person/></database>")

    with pytest.raises(ProbeError, match="digest"):
        backup.reset()


# -- asserting an export -------------------------------------------------------------


def test_an_export_is_the_file_that_appeared_in_this_call(backup: BackupDir) -> None:
    backup.reset()
    before = backup.listing()
    (backup.path / "wave.gramps").write_bytes(b"exported bytes")

    written = backup.assert_export(before, filename="wave.gramps")

    assert written.read_bytes() == b"exported bytes"


def test_an_export_that_never_happened_is_caught(backup: BackupDir) -> None:
    """The leftover-export false green, in one test: the file is there the whole time."""
    backup.reset()
    (backup.path / "wave.gramps").write_bytes(b"from an earlier run")
    before = backup.listing()

    with pytest.raises(AssertionError, match="wave.gramps"):
        backup.assert_export(before, filename="wave.gramps")


def test_an_export_under_a_different_name_is_caught(backup: BackupDir) -> None:
    backup.reset()
    before = backup.listing()
    (backup.path / "gramps-export-20260730-120000.gramps").write_bytes(b"timestamped")

    with pytest.raises(AssertionError, match="gramps-export"):
        backup.assert_export(before, filename="wave.gramps")


def test_an_empty_export_is_caught(backup: BackupDir) -> None:
    """A zero-byte file is what a failed export leaves behind, and it satisfies "a file with
    that name exists"."""
    backup.reset()
    before = backup.listing()
    (backup.path / "wave.gramps").write_bytes(b"")

    with pytest.raises(AssertionError, match="empty"):
        backup.assert_export(before, filename="wave.gramps")


# -- the committed manifest ----------------------------------------------------------


def test_the_committed_manifest_matches_the_fixture_on_disk() -> None:
    """`build_fixture.py` can regenerate the tree; if it does and this is not regenerated with
    it, every run resets the backup directory to a file the suite no longer expects."""
    committed = load_manifest()

    assert committed, f"{MANIFEST_FILE} lists no inputs"
    for name, expected in committed.items():
        assert digest_of((FIXTURES / name).read_bytes()) == expected, (
            f"{name} no longer matches {MANIFEST_FILE.name} — regenerate it"
        )


def test_the_manifest_is_committed_as_readable_json() -> None:
    assert isinstance(json.loads(MANIFEST_FILE.read_text(encoding="utf-8")), dict)
