# Generated by OrchestKit Claude Plugin
# Created: 2026-07-30

"""Builds the canonical fixture with the server's own tools (plan D2, T1.6, T2.2).

Run rarely — the output is committed and `test_05_fixture.py` is what guards it::

    .venv/bin/python tests/e2e/fixtures/build_fixture.py
    ruff format tests/e2e/fixtures/cast.py   # the pre-commit hook does this anyway

Why the tree is grown through `gramps_add_person` and friends rather than hand-written XML:
the fixture then contains exactly what this server produces, including the side effects a
hand-written file would miss — `add_person` creates the `Unbestätigt` tag on first use and a
blog post creates the `Blog` tag, and a test that seeds neither reads a count delta of +1 on
tags as a failure.

**Every person here is invented.** The repo is public and the real `.gramps` backups are a
real family tree; nothing from them may end up in a fixture.

One build produces **two** files. The uc19 import input is grown first, exported, and the tree
is then wiped with the product's own wipe so the canonical growth still starts at `I0000`. The
run ends by importing that input back into the finished tree, so the per-namespace delta uc19
asserts is a measurement rather than an expectation.

Two fields are normalised after the export, because they are the only ones that move between
runs: `<created date=…>` and the per-object `change=` mtimes. Measured: two exports of an
unchanged tree are byte-identical after ungzipping, so the UUID that makes a `.gramps` file
unreproducible lives in the gzip wrapper, not in the XML. Normalising the remaining two means
a regenerated fixture diffs only where the *tree* changed.
"""

from __future__ import annotations

import gzip
import re
import shutil
import sys
import tempfile
from pathlib import Path

FIXTURE_DIR = Path(__file__).resolve().parent
E2E_ROOT = FIXTURE_DIR.parent
sys.path.insert(0, str(E2E_ROOT))

from harness import gramps_instance as gi  # noqa: E402
from harness.mcp_container import McpContainer, container_name, image_from_env  # noqa: E402
from harness.rest import GrampsRest  # noqa: E402
from harness.runid import new_runid  # noqa: E402

from fixtures import stage2_subjects as s2  # noqa: E402
from fixtures.builder import Builder  # noqa: E402
from fixtures.emit import render_cast, write_manifest  # noqa: E402

TREE_FILE = FIXTURE_DIR / "synthetic-tree.gramps"
COUSINS_FILE = FIXTURE_DIR / s2.COUSINS_FILE
CAST_FILE = FIXTURE_DIR / "cast.py"
MANIFEST_FILE = FIXTURE_DIR / "backup-inputs.json"

FIXED_DATE = "2000-01-01"
MOUNT = "/data"


def normalise(xml: bytes) -> bytes:
    """Blank the two fields that move between runs, so a rebuild diffs only real changes."""
    text = xml.decode("utf-8")
    text = re.sub(r'<created date="[^"]*"', f'<created date="{FIXED_DATE}"', text)
    text = re.sub(r'change="\d+"', 'change="0"', text)
    return text.encode("utf-8")


def export(rest: GrampsRest, target: Path) -> Path:
    """The whole tree, as the plain XML a committed fixture has to be."""
    exported = rest.request("GET", "/api/exporters/gramps/file").content
    target.write_bytes(normalise(gzip.decompress(exported)))
    return target


def measure_name_types(rest: GrampsRest, gramps_id: str) -> dict[str, object]:
    """What the API hands back for a name type — the design's open `[U]` #1."""
    person = rest.person(gramps_id)
    alternates = person.get("alternate_names") or []
    return {
        "gramps_id": gramps_id,
        "primary": person["primary_name"].get("type"),
        "alternate": alternates[0].get("type") if alternates else None,
    }


def measure_cousins_import(
    builder: Builder, rest: GrampsRest, before: dict[str, int]
) -> dict[str, object]:
    """Import the uc19 input into the finished tree and record what actually moved."""
    builder.import_file(s2.COUSINS_FILE)
    after = rest.object_counts()
    landed = [
        person["gramps_id"]
        for person in rest.people()
        if (person["primary_name"]["surname_list"] or [{}])[0].get("surname") == s2.COUSINS_SURNAME
    ]
    return {
        "filename": s2.COUSINS_FILE,
        "surname": s2.COUSINS_SURNAME,
        "first_names": list(s2.COUSINS),
        "delta": {
            name: after[name] - before[name]
            for name in sorted(after)
            if after[name] != before[name]
        },
        "landed": sorted(landed),
    }


def stage(path: Path, backup: Path) -> None:
    """Put a built file where the MCP container can import it from."""
    shutil.copy(path, backup / path.name)
    (backup / path.name).chmod(0o666)


def build(rest: GrampsRest, mcp: McpContainer, backup: Path) -> None:
    """Grow both files, then measure the two things the design left open."""
    builder = Builder(mcp)
    builder.grow()
    s2.grow(builder)
    if builder.people[0]["gramps_id"] != "I0000":
        raise SystemExit(f"the canonical cast does not start at I0000: {builder.people[0]}")

    counts = rest.object_counts()
    export(rest, TREE_FILE)
    stage(TREE_FILE, backup)
    print(f"grown: {counts}")

    remarried = next(person for person in builder.people if person.get("name_type"))
    name_types = measure_name_types(rest, str(remarried["gramps_id"]))

    # The uc19 input is grown *after* the canonical tree, in the same instance, because the id
    # counter does not reset on a wipe: growing the three cousins first pushed the canonical
    # cast to start at I0003 (measured). So the cousins take the high ids instead, they collide
    # with nothing on import, and uc19 asserts on names either way.
    builder.wipe(rest)
    cousins = Builder(mcp)
    s2.grow_cousins(cousins)
    export(rest, COUSINS_FILE)
    stage(COUSINS_FILE, backup)
    cousins.wipe(rest)
    print(f"grew the uc19 input: {COUSINS_FILE.name} ({COUSINS_FILE.stat().st_size} B)")

    # Import the committed fixture back through the product's own path before measuring, so
    # the delta uc19 asserts is taken against the state a Stage-2 reset actually produces.
    builder.import_file(TREE_FILE.name)
    reimported = rest.object_counts()
    if reimported != counts:
        raise SystemExit(f"the fixture does not import back as built: {reimported} != {counts}")
    cousins_fact = measure_cousins_import(builder, rest, counts)
    print(f"name types: {name_types}\ncousins import: {cousins_fact}")

    CAST_FILE.write_text(
        render_cast(
            builder.people, builder.families, builder.sources, counts, cousins_fact, name_types
        )
    )
    write_manifest([TREE_FILE, COUSINS_FILE], MANIFEST_FILE)
    print(f"wrote {TREE_FILE.name} ({TREE_FILE.stat().st_size} B), {CAST_FILE.name}, "
          f"{MANIFEST_FILE.name}")  # fmt: skip


def main() -> int:
    runid = new_runid()
    instance = gi.GrampsInstance(runid)
    instance.start()
    if instance.add_user(gi.OWNER_USER, gi.OWNER_PW, gi.ROLE_OWNER)["rc"] != 0:
        raise SystemExit("could not create the owner user")
    rest = GrampsRest(instance.url, gi.OWNER_USER, gi.OWNER_PW)
    backup = Path(tempfile.mkdtemp(prefix="gwe2e-fixture-"))
    backup.chmod(0o777)  # the container runs as a different uid than this process
    mcp = McpContainer(
        container_name(runid, "fixture"),
        image_from_env(runid, {}).run_reference,
        {
            "GRAMPS_BASE_URL": instance.internal_url,
            "GRAMPS_USERNAME": gi.OWNER_USER,
            "GRAMPS_PASSWORD": gi.OWNER_PW,
            "GRAMPS_BACKUP_DIR": MOUNT,
            "GRAMPS_ENABLE_DESTRUCTIVE": "1",  # the build wipes between the two trees
        },
        network=instance.network,
        mounts=((str(backup), MOUNT),),
        runid=runid,
    )
    try:
        build(rest, mcp, backup)
    finally:
        leftovers = mcp.close()
        instance.teardown()
        shutil.rmtree(backup, ignore_errors=True)
        print(f"leftovers: mcp={leftovers} instance={instance.leftovers}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
