# Generated by OrchestKit Claude Plugin
# Created: 2026-07-30

"""Builds the canonical fixture with the server's own tools (plan D2, T1.6).

Run rarely — the output is committed and `test_05_fixture.py` is what guards it::

    .venv/bin/python tests/e2e/fixtures/build_fixture.py
    ruff format tests/e2e/fixtures/cast.py   # the pre-commit hook does this anyway

Why the tree is grown through `gramps_add_person` and friends rather than hand-written XML:
the fixture then contains exactly what this server produces, including the side effects a
hand-written file would miss — `add_person` creates the `Unbestätigt` tag on first use and a
blog post creates the `Blog` tag, and a test that seeds neither reads a count delta of +1 on
tags as a failure.

**Every person here is invented.** The repo is public and the real `.gramps` backups are a
real family tree; nothing from them may end up in a fixture.

Two fields are normalised after the export, because they are the only ones that move between
runs: `<created date=…>` and the per-object `change=` mtimes. Measured: two exports of an
unchanged tree are byte-identical after ungzipping, so the UUID that makes a `.gramps` file
unreproducible lives in the gzip wrapper, not in the XML. Normalising the remaining two means
a regenerated fixture diffs only where the *tree* changed.
"""

from __future__ import annotations

import gzip
import re
import sys
from pathlib import Path

FIXTURE_DIR = Path(__file__).resolve().parent
E2E_ROOT = FIXTURE_DIR.parent
sys.path.insert(0, str(E2E_ROOT))

from harness import gramps_instance as gi  # noqa: E402
from harness.mcp_container import McpContainer, container_name, image_from_env  # noqa: E402
from harness.rest import GrampsRest  # noqa: E402
from harness.runid import new_runid  # noqa: E402

TREE_FILE = FIXTURE_DIR / "synthetic-tree.gramps"
CAST_FILE = FIXTURE_DIR / "cast.py"

FIXED_DATE = "2000-01-01"
MALE, FEMALE = 1, 0

# Three founding couples; their descendants marry in and the line runs three deep. 21 families
# is not decoration: `count_families` is `len(unpaginated list)` against a default pagesize of
# 20, so at 20 or fewer the pagination assumption is untestable.
FOUNDER_SURNAMES = ("Aschenblum", "Bernwald", "Corvinstett")
INLAW_SURNAMES = ("Duvenrath", "Erlenkamp", "Fjordheim", "Grausteen", "Halmberg", "Ivarsgard")
MEN = ("Anselm", "Bertram", "Corwin", "Detlev", "Eberhard", "Folkmar", "Gunthar")
WOMEN = ("Adalind", "Brunhild", "Cordula", "Dagmar", "Elvide", "Frauke", "Gisela")

CHILDREN_PER_FOUNDER = 3
FOUNDER_BIRTH_YEAR = 1880
GENERATION_SPAN = 28


class Builder:
    """Grows the tree and remembers every id the server handed back."""

    def __init__(self, mcp: McpContainer) -> None:
        self.mcp = mcp
        self.people: list[dict[str, object]] = []
        self.families: list[dict[str, object]] = []
        self.sources: list[dict[str, str]] = []

    def call(self, tool: str, arguments: dict[str, object]) -> str:
        result = self.mcp.call(tool, arguments, timeout=300)
        if result.is_error:
            raise SystemExit(f"{tool} failed: {result.text}")
        return result.text.strip()

    def person(self, first_name: str, surname: str, gender: int, birth_year: int) -> str:
        gramps_id = self.call(
            "gramps_add_person",
            {
                "first_name": first_name,
                "surname": surname,
                "gender": gender,
                "birth_year": birth_year,
            },
        )
        self.people.append(
            {
                "gramps_id": gramps_id,
                "first_name": first_name,
                "surname": surname,
                "gender": gender,
                "birth_year": birth_year,
            }
        )
        return gramps_id

    def family(self, spouse_a: str, spouse_b: str, children: tuple[str, ...] = ()) -> str:
        gramps_id = self.call(
            "gramps_add_family", {"spouse_a_id": spouse_a, "spouse_b_id": spouse_b}
        )
        for child in children:
            self.call("gramps_add_child_to_family", {"family_id": gramps_id, "child_id": child})
        self.families.append(
            {
                "gramps_id": gramps_id,
                "spouse_a": spouse_a,
                "spouse_b": spouse_b,
                "children": list(children),
            }
        )
        return gramps_id

    def source(self, index: int) -> str:
        title = f"Chronicle entry {index:02d}"
        gramps_id = self.call(
            "gramps_create_blog_post",
            {"title": title, "body": f"Invented note {index:02d} for the E2E fixture."},
        )
        self.sources.append({"gramps_id": gramps_id, "title": title})
        return gramps_id

    def grow(self) -> None:
        """Three generations: 3 founding couples, their children, and theirs. 42 / 21 / 21."""
        second: list[tuple[str, str]] = []
        for index, surname in enumerate(FOUNDER_SURNAMES):
            year = FOUNDER_BIRTH_YEAR + index
            father = self.person(MEN[index], surname, MALE, year)
            mother = self.person(WOMEN[index], INLAW_SURNAMES[index], FEMALE, year + 2)
            children = tuple(
                self.person(
                    MEN[child + 1] if child % 2 else WOMEN[child + 1],
                    surname,
                    MALE if child % 2 else FEMALE,
                    year + GENERATION_SPAN + child,
                )
                for child in range(CHILDREN_PER_FOUNDER)
            )
            self.family(father, mother, children)
            second += [(child, surname) for child in children]

        third: list[tuple[str, str]] = []
        for index, (child, surname) in enumerate(second):
            inlaw = self.person(
                WOMEN[index % len(WOMEN)],
                INLAW_SURNAMES[index % len(INLAW_SURNAMES)],
                FEMALE,
                FOUNDER_BIRTH_YEAR + GENERATION_SPAN + index,
            )
            grandchild = self.person(
                MEN[index % len(MEN)],
                surname,
                MALE,
                FOUNDER_BIRTH_YEAR + 2 * GENERATION_SPAN + index,
            )
            self.family(child, inlaw, (grandchild,))
            third.append((grandchild, surname))

        for index, (grandchild, _surname) in enumerate(third):
            inlaw = self.person(
                WOMEN[(index + 3) % len(WOMEN)],
                INLAW_SURNAMES[(index + 2) % len(INLAW_SURNAMES)],
                FEMALE,
                FOUNDER_BIRTH_YEAR + 2 * GENERATION_SPAN + index,
            )
            self.family(grandchild, inlaw)

        for index in range(len(self.families)):
            self.source(index)


def normalise(xml: bytes) -> bytes:
    """Blank the two fields that move between runs, so a rebuild diffs only real changes."""
    text = xml.decode("utf-8")
    text = re.sub(r'<created date="[^"]*"', f'<created date="{FIXED_DATE}"', text)
    text = re.sub(r'change="\d+"', 'change="0"', text)
    return text.encode("utf-8")


def render_cast(builder: Builder, counts: dict[str, int]) -> str:
    """Emit `cast.py`: every id lives here so no test body has to carry a literal."""
    return (
        '"""Every id in `synthetic-tree.gramps` — generated by `build_fixture.py`, do not edit.\n'
        "\n"
        "No test may hardcode a Gramps id: they are assigned by the server in creation order,\n"
        "and the probe already caught one design that assumed they start at I0001 (they start\n"
        'at I0000). Import from here instead."""\n\n'
        "from __future__ import annotations\n\n"
        f"PEOPLE = {builder.people!r}\n\n"
        f"FAMILIES = {builder.families!r}\n\n"
        f"SOURCES = {builder.sources!r}\n\n"
        "# Every namespace, as observed on the instance this tree was grown on. The whole dict\n"
        "# is asserted after the import: a dropped `<family>` element is *not* visible in the\n"
        "# family count (people carry `<parentin>`, so the importer rebuilds it) — it shows up\n"
        "# as one extra note, because Gramps records the repair. Measured, not assumed.\n"
        f"COUNTS = {dict(sorted(counts.items()))!r}\n"
    )


def main() -> int:
    runid = new_runid()
    instance = gi.GrampsInstance(runid)
    instance.start()
    if instance.add_user(gi.OWNER_USER, gi.OWNER_PW, gi.ROLE_OWNER)["rc"] != 0:
        raise SystemExit("could not create the owner user")
    rest = GrampsRest(instance.url, gi.OWNER_USER, gi.OWNER_PW)
    mcp = McpContainer(
        container_name(runid, "fixture"),
        image_from_env(runid, {}).run_reference,
        {
            "GRAMPS_BASE_URL": instance.internal_url,
            "GRAMPS_USERNAME": gi.OWNER_USER,
            "GRAMPS_PASSWORD": gi.OWNER_PW,
        },
        network=instance.network,
        runid=runid,
    )
    try:
        builder = Builder(mcp)
        builder.grow()
        counts = rest.snapshot()["counts"]
        print(f"grown: {counts}")

        exported = rest.request("GET", "/api/exporters/gramps/file").content
        TREE_FILE.write_bytes(normalise(gzip.decompress(exported)))
        CAST_FILE.write_text(render_cast(builder, counts))
        print(f"wrote {TREE_FILE.name} ({TREE_FILE.stat().st_size} B) and {CAST_FILE.name}")
    finally:
        leftovers = mcp.close()
        instance.teardown()
        print(f"leftovers: mcp={leftovers} instance={instance.leftovers}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
