# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""Grows a tree with the server's own tools and remembers every id it handed back (plan D2).

Split out of `build_fixture.py` when the Stage-2 subjects arrived — growing a tree and
orchestrating an instance around it are two jobs, and this repo's 300-line limit is a useful
forcing function for saying so.

Nothing here invents an id. Ids are assigned by the server in creation order — the bootstrap
probe caught one design that assumed they start at `I0001`, they start at `I0000` — so every id
in `cast.py` is one this server handed back during a real call.
"""

from __future__ import annotations

from typing import Any

from harness.mcp_container import McpContainer
from harness.rest import GrampsRest

FEMALE, MALE, UNKNOWN = 0, 1, 2

FOUNDER_SURNAMES = ("Aschenblum", "Bernwald", "Corvinstett")
INLAW_SURNAMES = ("Duvenrath", "Erlenkamp", "Fjordheim", "Grausteen", "Halmberg", "Ivarsgard")
MEN = ("Anselm", "Bertram", "Corwin", "Detlev", "Eberhard", "Folkmar", "Gunthar")
WOMEN = ("Adalind", "Brunhild", "Cordula", "Dagmar", "Elvide", "Frauke", "Gisela")

CHILDREN_PER_FOUNDER = 3
FOUNDER_BIRTH_YEAR = 1880
GENERATION_SPAN = 28


class Builder:
    """Grows the tree and remembers every id the server handed back."""

    def __init__(self, mcp: McpContainer) -> None:
        self.mcp = mcp
        self.people: list[dict[str, Any]] = []
        self.families: list[dict[str, Any]] = []
        self.sources: list[dict[str, Any]] = []

    def call(self, tool: str, arguments: dict[str, Any]) -> str:
        result = self.mcp.call(tool, arguments, timeout=300)
        if result.is_error:
            raise SystemExit(f"{tool} failed: {result.text}")
        return result.text.strip()

    def person(
        self,
        first_name: str,
        surname: str,
        gender: int,
        birth_year: int | None = None,
        **recorded: Any,
    ) -> str:
        """One person. `birth_year=None` deliberately creates no birth event."""
        arguments: dict[str, Any] = {
            "first_name": first_name,
            "surname": surname,
            "gender": gender,
        }
        if birth_year is not None:
            arguments["birth_year"] = birth_year
        gramps_id = self.call("gramps_add_person", arguments)
        self.people.append(
            {
                "gramps_id": gramps_id,
                "first_name": first_name,
                "surname": surname,
                "gender": gender,
                "birth_year": birth_year,
                **recorded,
            }
        )
        return gramps_id

    def family(
        self, spouse_a: str, spouse_b: str | None = None, children: tuple[str, ...] = ()
    ) -> str:
        """One family. A single spouse leaves the other parent slot empty on purpose."""
        arguments: dict[str, Any] = {"spouse_a_id": spouse_a}
        if spouse_b is not None:
            arguments["spouse_b_id"] = spouse_b
        gramps_id = self.call("gramps_add_family", arguments)
        for child in children:
            self.call("gramps_add_child_to_family", {"family_id": gramps_id, "child_id": child})
        self.families.append(
            {
                "gramps_id": gramps_id,
                "spouse_a": spouse_a,
                "spouse_b": spouse_b,
                "children": list(children),
            }
        )
        return gramps_id

    def article(self, title: str, body: str) -> str:
        """One blog post. The body is recorded because Stage 2 asserts against its text."""
        gramps_id = self.call("gramps_create_blog_post", {"title": title, "body": body})
        self.sources.append({"gramps_id": gramps_id, "title": title, "body": body})
        return gramps_id

    def set_surname(self, gramps_id: str, surname: str, name_type: str) -> None:
        self.call(
            "gramps_set_surname",
            {"gramps_id": gramps_id, "surname": surname, "name_type": name_type},
        )

    def add_alternate_name(
        self, gramps_id: str, surname: str, first_name: str, name_type: str
    ) -> None:
        self.call(
            "gramps_add_alternate_name",
            {
                "gramps_id": gramps_id,
                "surname": surname,
                "first_name": first_name,
                "name_type": name_type,
            },
        )

    def wipe(self, rest: GrampsRest) -> None:
        """Empty the tree with the product's own wipe.

        The cousins branch for uc19 is grown and exported first, from this same instance; the
        canonical tree then has to start from nothing, or its ids would begin above the
        cousins' and `cast.py` would no longer start at `I0000`.
        """
        self.call("gramps_delete_all_objects", {"confirm": True, "expected_count": rest.total()})

    def import_file(self, filename: str) -> str:
        return self.call("gramps_import_file", {"filename": filename})

    def grow(self) -> None:
        """Three generations: 3 founding couples, their children, and theirs. 42 / 21 / 21."""
        second: list[tuple[str, str]] = []
        for index, surname in enumerate(FOUNDER_SURNAMES):
            year = FOUNDER_BIRTH_YEAR + index
            father = self.person(MEN[index], surname, MALE, year)
            mother = self.person(WOMEN[index], INLAW_SURNAMES[index], FEMALE, year + 2)
            children = tuple(
                self.person(
                    MEN[child + 1] if child % 2 else WOMEN[child + 1],
                    surname,
                    MALE if child % 2 else FEMALE,
                    year + GENERATION_SPAN + child,
                )
                for child in range(CHILDREN_PER_FOUNDER)
            )
            self.family(father, mother, children)
            second += [(child, surname) for child in children]

        third: list[tuple[str, str]] = []
        for index, (child, surname) in enumerate(second):
            inlaw = self.person(
                WOMEN[index % len(WOMEN)],
                INLAW_SURNAMES[index % len(INLAW_SURNAMES)],
                FEMALE,
                FOUNDER_BIRTH_YEAR + GENERATION_SPAN + index,
            )
            grandchild = self.person(
                MEN[index % len(MEN)],
                surname,
                MALE,
                FOUNDER_BIRTH_YEAR + 2 * GENERATION_SPAN + index,
            )
            self.family(child, inlaw, (grandchild,))
            third.append((grandchild, surname))

        for index, (grandchild, _surname) in enumerate(third):
            inlaw = self.person(
                WOMEN[(index + 3) % len(WOMEN)],
                INLAW_SURNAMES[(index + 2) % len(INLAW_SURNAMES)],
                FEMALE,
                FOUNDER_BIRTH_YEAR + 2 * GENERATION_SPAN + index,
            )
            self.family(grandchild, inlaw)

        for index in range(len(self.families)):
            title = f"Chronicle entry {index:02d}"
            self.article(title, f"Invented note {index:02d} for the E2E fixture.")
