# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""Writes `cast.py` and the backup-input manifest out of a finished build (plan D2, D17).

`cast.py` is generated, never edited: it is the record of what one real build actually
produced, ids included. Everything in it that could have been *assumed* instead is measured
here and written down with the measurement — the import delta of the cousins file, and the
shape the API hands back for a name type — because both were open `[U]` items in the Stage-2
design and both decide whether a use-case assertion is expressible at all.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

CAST_HEADER = '''"""Every id in `synthetic-tree.gramps` — generated by `build_fixture.py`, do not edit.

No test may hardcode a Gramps id: they are assigned by the server in creation order,
and the probe already caught one design that assumed they start at I0001 (they start
at I0000). Import from here instead."""

from __future__ import annotations

'''

COUNTS_NOTE = (
    "# Every namespace, as observed on the instance this tree was grown on. The whole dict\n"
    "# is asserted after the import: a dropped `<family>` element is *not* visible in the\n"
    "# family count (people carry `<parentin>`, so the importer rebuilds it) — it shows up\n"
    "# as one extra note, because Gramps records the repair. Measured, not assumed.\n"
)

COUSINS_NOTE = (
    "# The uc19 import input, and what importing it into *this* tree actually moves. Measured\n"
    "# rather than derived: the file carries the `Unbestätigt` tag its people were created\n"
    "# with, and whether Gramps merges that tag by name or keeps a second one is not something\n"
    "# a per-namespace delta assertion may guess. `landed` records whether the ids collide or\n"
    "# get remapped — the Stage-2 design left that open, so uc19 asserts on names.\n"
)

NAME_TYPE_NOTE = (
    "# How the API hands a name type back, read from the person the fixture writes one on.\n"
    "# The client *writes* a bare string (gramps_client.py:269); if the server normalises it\n"
    "# to a NameType object on read, every assertion about `Married Name` / `Birth Name` has\n"
    "# to go through that shape. This is the answer for the instance the fixture was built on.\n"
)


FAMILIES_NOTE = (
    "# `spouse_a`/`spouse_b` are the *arguments* gramps_add_family was called with;\n"
    "# `father`/`mother` are the slots the server actually put them in, read back off the\n"
    "# built tree. They are not the same thing and for six of these families they disagree:\n"
    "# `_assign_parent_handles` moves a person to the mother slot only for gender Female, so\n"
    "# two female spouses fall through to call order and `spouse_a` becomes the father. Read\n"
    "# the slot, never deduce it — deducing it means re-deriving the product's rule inside a\n"
    "# test and calling the result independent evidence.\n"
)

GRAPH_NOTE = (
    "# The four-generation lineage the family-graph matrix runs on, and three things about it\n"
    "# that are the server's decision rather than the fixture's. `family_order` and\n"
    "# `parent_family_order` decide what get_descendants and get_ancestors return, in that\n"
    "# order, so they are measured. `reverse_refs` answers the design's U-2: every read tool\n"
    "# consults the person-side family_list, every write tool PUTs only the family object, and\n"
    "# if the API did not maintain the link between them the whole group would be broken in a\n"
    "# way no mocked test could see. `childref_rel` is U-4, the shape a ChildRefType reads\n"
    "# back as. The build refuses to write this file if reverse_refs is not 'api'.\n"
)


def render_cast(
    people: list[dict[str, Any]],
    families: list[dict[str, Any]],
    sources: list[dict[str, Any]],
    counts: dict[str, int],
    cousins: dict[str, Any],
    name_types: dict[str, Any],
    graph: dict[str, Any],
) -> str:
    """Emit `cast.py`: every id lives here so no test body has to carry a literal."""
    return (
        CAST_HEADER
        + f"PEOPLE = {people!r}\n\n"
        + FAMILIES_NOTE
        + f"FAMILIES = {families!r}\n\n"
        + f"SOURCES = {sources!r}\n\n"
        + COUNTS_NOTE
        + f"COUNTS = {dict(sorted(counts.items()))!r}\n\n"
        + COUSINS_NOTE
        + f"COUSINS = {cousins!r}\n\n"
        + NAME_TYPE_NOTE
        + f"NAME_TYPES = {name_types!r}\n\n"
        + GRAPH_NOTE
        + f"GRAPH = {graph!r}\n"
    )


def write_manifest(files: list[Path], manifest_file: Path) -> dict[str, str]:
    """The committed backup-input set, digests included (D17).

    Regenerated by the build rather than by hand: the manifest exists to catch a fixture that
    drifted, and a digest someone typed in from a failure message would catch nothing.
    """
    manifest = {path.name: hashlib.sha256(path.read_bytes()).hexdigest() for path in sorted(files)}
    manifest_file.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return manifest
