# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

"""Record shapes for the Docker-free grading tests (plan T2.5).

Hand-built rather than recorded, and pinned from both ends: every path used here is one the
suite already reads off a live instance (`test_05_fixture.py` asserts `primary_name`,
`surname_list[0].surname`, `alternate_names[].type`, `child_ref_list[].ref` against the real
tree, and `rest.py` documents `note["text"]["string"]`). A grader tested against invented shapes
would be a grader that agrees with itself.
"""

from __future__ import annotations

from typing import Any

from stage2.state import NAMESPACES, State

FEMALE, MALE = 0, 1
BIRTH_NAME, MARRIED_NAME = "Birth Name", "Married Name"


def person(
    gramps_id: str,
    first_name: str,
    surname: str,
    *,
    gender: int = FEMALE,
    name_type: str = BIRTH_NAME,
    alternates: tuple[tuple[str, str], ...] = (),
    tags: tuple[str, ...] = (),
    families: tuple[str, ...] = (),
) -> dict[str, Any]:
    return {
        "gramps_id": gramps_id,
        "handle": f"h-{gramps_id}",
        "gender": gender,
        "primary_name": {
            "first_name": first_name,
            "surname_list": [{"surname": surname}],
            "type": name_type,
        },
        "alternate_names": [
            {"surname_list": [{"surname": name}], "type": kind} for name, kind in alternates
        ],
        "tag_list": [f"h-tag-{name}" for name in tags],
        "family_list": list(families),
    }


def family(
    gramps_id: str,
    *,
    father: str = "",
    mother: str = "",
    children: tuple[str, ...] = (),
) -> dict[str, Any]:
    return {
        "gramps_id": gramps_id,
        "handle": f"h-{gramps_id}",
        "father_handle": f"h-{father}" if father else None,
        "mother_handle": f"h-{mother}" if mother else None,
        "child_ref_list": [{"ref": f"h-{child}"} for child in children],
    }


def source(gramps_id: str, title: str, *, notes: tuple[str, ...] = ()) -> dict[str, Any]:
    return {
        "gramps_id": gramps_id,
        "handle": f"h-{gramps_id}",
        "title": title,
        "author": "",
        "note_list": [f"h-{note}" for note in notes],
    }


def note(gramps_id: str, text: str) -> dict[str, Any]:
    return {"gramps_id": gramps_id, "handle": f"h-{gramps_id}", "text": {"string": text}}


def tag(name: str) -> dict[str, Any]:
    return {"gramps_id": "", "handle": f"h-tag-{name}", "name": name}


def state(**namespaces: tuple[dict[str, Any], ...]) -> State:
    """A capture whose counts are derived from its records, so the two cannot disagree."""
    records = {name: tuple(namespaces.get(name, ())) for name in NAMESPACES}
    return State(
        counts={name: len(values) for name, values in records.items()},
        records=records,
    )
