# Generated by OrchestKit Claude Plugin
# Created: 2026-07-30

"""The two assertions every Stage-1 test is allowed to make (plan D16, D17).

**A tool's own report is never evidence.** `_guarded_write` takes its `before`/`after` from
the **local dict** it just mutated (`gramps_client.py:699-704`), so `before != after` holds
whether or not the PUT was sent: delete `self._put_person(...)` and seven write tools become
silent no-ops that certify themselves as successful. The same check false-reds on a legitimate
no-op — `confirm_person` on an already-confirmed person writes nothing and must still pass.
So `before != after` is not used here at all. What replaces it:

1. an **independent** count and identity delta read over REST around the call,
2. a **mandatory re-read** of the named fields over REST afterwards (`expect_person`),
3. and only then a cross-check that the tool's story matches what the tree says
   (`self_report.py`, one branch per return shape).

Step 2 only means anything if the expectation is falsifiable, which "an argument was passed"
does not guarantee. `_reject_unusable_call` therefore checks coverage, not presence: no empty
field map, no `None` where `ABSENT` is meant, and no `bulk` call that leaves part of its own
`items` unnamed. Each of those three used to open the gate and then compare nothing.

`assert_refusal` is deliberately the *single* helper that looks at error text, and its
`contains=` must be a fragment authored in this repo — `vocabulary.py` enforces that
mechanically, because asserting framework wording makes one `pip install -U` a mass-red.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from types import MappingProxyType
from typing import Any

from .gate import Expectation, merge_expectations, reject_uncovered_removal, reject_unusable_call
from .mcp_session import ToolResult
from .movement import EVERYTHING, Declared, assert_tree_moved_exactly
from .rest import GrampsRest
from .self_report import SelfReport, assert_self_report
from .wire import ABSENT, payload, payload_list, resolve_path

__all__ = [
    "ABSENT",
    "EVERYTHING",
    "GuardedWrite",
    "NO_DELTA",
    "SelfReport",
    "assert_guarded_write",
    "assert_refusal",
    "assert_tree_moved_exactly",
    "payload",
    "payload_list",
    "resolve_path",
]

NO_DELTA: Mapping[str, int] = MappingProxyType({})


@dataclass(frozen=True)
class GuardedWrite:
    """What the call did, as the *oracle* saw it — plus the tool's report for the message."""

    tool: str
    before: dict[str, int]
    after: dict[str, int]
    delta: dict[str, int]
    # Which objects moved, not just how many — handed back because a caller that cannot diff
    # the snapshots itself has to take the counts on trust (checkpoint B1).
    added: dict[str, list[str]]
    removed: dict[str, list[str]]
    result: ToolResult
    payload: Any


def assert_guarded_write(
    rest: GrampsRest,
    mcp: Any,
    tool: str,
    arguments: Mapping[str, Any],
    *,
    expect_delta: Mapping[str, int],
    self_report: SelfReport,
    expect_person: Mapping[str, Mapping[str, Any]] | None = None,
    expect_record: Mapping[str, Any] | None = None,
    expect_added: Declared | None = None,
    expect_removed: Declared | None = None,
    id_namespace: str | None = None,
    label: str | None = None,
    timeout: float = 60.0,
) -> GuardedWrite:
    """Call a write tool and prove, from the tree, that it did exactly what it claims.

    `expect_delta` is signed movement per `object_counts` key; `{}` means nothing may move.
    `expect_person` maps `gramps_id -> {field path: value}` and is **mandatory** for the
    `person` and `bulk` shapes. `self_report` names the return shape, because there are five
    of them and a caller who guesses silently gets no cross-check at all.

    A count is not an identity, so `expect_removed={ns: [gramps_id, …]}` (or `EVERYTHING`) is
    **mandatory for every namespace that loses objects** — "one person fewer" is satisfied by
    the wrong person leaving, and the delete report only echoes the id it was handed
    (checkpoint B1). Creates cannot be declared, so a positive delta is held to "exactly that
    many appeared, none left"; `expect_added` exists for the one case that needs it, a
    namespace that gains *and* loses in the same call.

    "Mandatory" means covering, not merely present — three ways it used to be hollow are now
    usage errors (checkpoint B2-B4): an entry with no field (`{"I0001": {}}`) checks nothing
    behind the open gate; an expected `None` is satisfied by a mistyped path just as well as by
    a real absence, so absence is written `ABSENT`; and a `bulk` call must name **every** id in
    `arguments["items"]`, because a field write moves no count and an unnamed item is invisible
    to every other check in this module.
    """
    name = label or f"{tool}{dict(arguments)}"
    wanted = merge_expectations(name, expect_person, expect_record)
    reject_unusable_call(name, tool, arguments, self_report, wanted, id_namespace)
    reject_uncovered_removal(name, expect_delta, expect_removed)

    pre = _read_before(rest, wanted)

    before = rest.snapshot()
    result = mcp.call(tool, dict(arguments), timeout=timeout)
    assert not result.is_error, (
        f"{name}: expected a successful write, the server said: {result.text[:400]}"
    )
    after = rest.snapshot()

    reported = payload(result)
    note = f"the tool said: {result.text[:400]}"
    moved = assert_tree_moved_exactly(
        name,
        before,
        after,
        expect_delta,
        note,
        expect_added=expect_added,
        expect_removed=expect_removed,
    )
    _assert_fields_landed(name, rest, wanted, note)
    assert_self_report(
        name,
        self_report,
        reported,
        wanted.get("people", {}),
        pre.get("people", {}),
        before,
        after,
        rest,
        id_namespace,
        moved,
    )

    return GuardedWrite(
        tool=tool,
        before=before["counts"],
        after=after["counts"],
        delta={key: value for key, value in moved.delta.items() if value},
        added=dict(moved.added),
        removed=dict(moved.removed),
        result=result,
        payload=reported,
    )


def assert_refusal(
    rest: GrampsRest,
    mcp: Any,
    tool: str,
    arguments: Mapping[str, Any],
    *,
    contains: str,
    expect_delta: Mapping[str, int] = NO_DELTA,
    expect_record: Mapping[str, Any] | None = None,
    expect_added: Declared | None = None,
    expect_removed: Declared | None = None,
    label: str | None = None,
    timeout: float = 60.0,
) -> ToolResult:
    """A tool that must refuse: it errors, it says why in wording this repo authored, and it did
    not do the thing it refused to do.

    The third check is the one that matters — a refusal that already changed something reads
    exactly like a clean rejection to `is_error` and to the text, and it is the worse bug. But
    counts and identity only show what *arrived or left*: a field written in place before the
    raise moves neither, so "the tree did not move" is more than that evidence supports
    (checkpoint B6). `expect_record` is how a case says which leaf must still hold its old
    value; without it, this asserts no object was created or destroyed, and nothing more.
    """
    name = label or f"{tool}{dict(arguments)}"
    wanted = merge_expectations(name, None, expect_record)
    reject_uncovered_removal(name, expect_delta, expect_removed)
    before = rest.snapshot()
    result = mcp.call(tool, dict(arguments), timeout=timeout)
    after = rest.snapshot()

    assert result.is_error, f"{name}: did not refuse — the server answered: {result.text[:400]}"
    assert contains in result.text, f"{name}: {contains!r} not in the refusal: {result.text[:400]}"
    assert_tree_moved_exactly(
        name,
        before,
        after,
        expect_delta,
        f"refusal was: {result.text[:400]}",
        expect_added=expect_added,
        expect_removed=expect_removed,
    )
    _assert_fields_landed(name, rest, wanted, f"refusal was: {result.text[:400]}")
    return result


def _read_before(rest: GrampsRest, wanted: Expectation) -> dict[str, dict[str, Any]]:
    """The prior state of every named record, for the shapes that report a `before` of their own."""
    return {
        namespace: {gramps_id: _try_record(rest, namespace, gramps_id) for gramps_id in records}
        for namespace, records in wanted.items()
    }


def _try_record(rest: GrampsRest, namespace: str, gramps_id: str) -> dict[str, Any] | None:
    try:
        return rest.by_gramps_id(namespace, gramps_id)
    except LookupError:
        return None  # created by the call under test — there is no prior state to compare


def _assert_fields_landed(name: str, rest: GrampsRest, wanted: Expectation, note: str) -> None:
    """D16 itself: a claim counts only once the tree repeats it back — in any namespace."""
    for namespace, records in wanted.items():
        for gramps_id, fields in records.items():
            record = rest.by_gramps_id(namespace, gramps_id)
            for path, value in fields.items():
                actual = resolve_path(record, path, default=ABSENT)
                assert actual == value, (
                    f"{name}: the tree says {namespace}/{gramps_id}.{path} == {actual!r}, "
                    f"expected {value!r}\n  {note}"
                )
