# Generated by OrchestKit Claude Plugin
# Created: 2026-07-30

"""The two assertions every Stage-1 test is allowed to make (plan D16, D17).

**A tool's own report is never evidence.** `_guarded_write` takes its `before`/`after` from
the **local dict** it just mutated (`gramps_client.py:699-704`), so `before != after` holds
whether or not the PUT was sent: delete `self._put_person(...)` and seven write tools become
silent no-ops that certify themselves as successful. The same check false-reds on a legitimate
no-op — `confirm_person` on an already-confirmed person writes nothing and must still pass.
So `before != after` is not used here at all. What replaces it:

1. an **independent** count and identity delta read over REST around the call,
2. a **mandatory re-read** of the named fields over REST afterwards (`expect_person`),
3. and only then a cross-check that the tool's story matches what the tree says
   (`self_report.py`, one branch per return shape).

`assert_refusal` is deliberately the *single* helper that looks at error text, and its
`contains=` must be a fragment authored in this repo — `vocabulary.py` enforces that
mechanically, because asserting framework wording makes one `pip install -U` a mass-red.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from types import MappingProxyType
from typing import Any, Literal

from .docker_util import ProbeError
from .mcp_session import ToolResult
from .rest import GrampsRest
from .self_report import assert_self_report
from .wire import payload, payload_list, resolve_path

__all__ = [
    "GuardedWrite",
    "NO_DELTA",
    "SelfReport",
    "assert_guarded_write",
    "assert_refusal",
    "payload",
    "payload_list",
    "resolve_path",
]

SelfReport = Literal["counts", "person", "bulk", "delete", "id", "unguarded"]

# The two shapes that write to a person and report about it — exactly the shapes a skipped PUT
# makes invisible, so both must name what the tree has to say afterwards.
NEEDS_EXPECT_PERSON = ("person", "bulk")
NO_DELTA: Mapping[str, int] = MappingProxyType({})


@dataclass(frozen=True)
class GuardedWrite:
    """What the call did, as the *oracle* saw it — plus the tool's report for the message."""

    tool: str
    before: dict[str, int]
    after: dict[str, int]
    delta: dict[str, int]
    result: ToolResult
    payload: Any


def assert_guarded_write(
    rest: GrampsRest,
    mcp: Any,
    tool: str,
    arguments: Mapping[str, Any],
    *,
    expect_delta: Mapping[str, int],
    self_report: SelfReport,
    expect_person: Mapping[str, Mapping[str, Any]] | None = None,
    id_namespace: str | None = None,
    label: str | None = None,
    timeout: float = 60.0,
) -> GuardedWrite:
    """Call a write tool and prove, from the tree, that it did exactly what it claims.

    `expect_delta` is signed movement per `object_counts` key; `{}` means nothing may move.
    `expect_person` maps `gramps_id -> {field path: value}` and is **mandatory** for the
    `person` and `bulk` shapes. `self_report` names the return shape, because there are five
    of them and a caller who guesses silently gets no cross-check at all.
    """
    name = label or f"{tool}{dict(arguments)}"
    _reject_unusable_call(name, tool, self_report, expect_person, expect_delta, id_namespace)

    wanted = dict(expect_person or {})
    pre = {gramps_id: _try_person(rest, gramps_id) for gramps_id in wanted}

    before = rest.snapshot()
    result = mcp.call(tool, dict(arguments), timeout=timeout)
    assert not result.is_error, (
        f"{name}: expected a successful write, the server said: {result.text[:400]}"
    )
    after = rest.snapshot()

    reported = payload(result)
    note = f"the tool said: {result.text[:400]}"
    delta = assert_tree_moved_exactly(name, before, after, expect_delta, rest, note)
    _assert_fields_landed(name, rest, wanted, note)
    assert_self_report(name, self_report, reported, wanted, pre, before, after, rest, id_namespace)

    return GuardedWrite(
        tool=tool,
        before=before["counts"],
        after=after["counts"],
        delta=delta,
        result=result,
        payload=reported,
    )


def assert_refusal(
    rest: GrampsRest,
    mcp: Any,
    tool: str,
    arguments: Mapping[str, Any],
    *,
    contains: str,
    expect_delta: Mapping[str, int] = NO_DELTA,
    label: str | None = None,
    timeout: float = 60.0,
) -> ToolResult:
    """A tool that must refuse: it errors, it says why in wording this repo authored, and the
    tree did not move.

    The third check is the one that matters. A refusal that already changed something reads
    exactly like a clean rejection to `is_error` and to the text, and it is the worse bug.
    """
    name = label or f"{tool}{dict(arguments)}"
    before = rest.snapshot()
    result = mcp.call(tool, dict(arguments), timeout=timeout)
    after = rest.snapshot()

    assert result.is_error, f"{name}: did not refuse — the server answered: {result.text[:400]}"
    assert contains in result.text, f"{name}: {contains!r} not in the refusal: {result.text[:400]}"
    assert_tree_moved_exactly(
        name, before, after, expect_delta, rest, f"refusal was: {result.text[:400]}"
    )
    return result


def assert_tree_moved_exactly(
    name: str,
    before: dict[str, Any],
    after: dict[str, Any],
    expect_delta: Mapping[str, int],
    rest: GrampsRest,
    note: str,
) -> dict[str, int]:
    """The independent half: counts say *how many*, the fingerprint says *which*."""
    counts_before, counts_after = before["counts"], after["counts"]
    keys = set(counts_before) | set(counts_after)
    delta = {key: counts_after.get(key, 0) - counts_before.get(key, 0) for key in keys}
    moved = {key: value for key, value in delta.items() if value}
    want = {key: value for key, value in dict(expect_delta).items() if value}

    assert moved == want, (
        f"{name}: the tree moved {moved}, expected {want}\n"
        f"  before={counts_before}\n  after={counts_after}\n  {note}"
    )
    if not want:
        # Identity, not content: one object created and another deleted leaves every count
        # unchanged, and a counts-only guard would call that "nothing happened".
        assert rest.fingerprint(before) == rest.fingerprint(after), (
            f"{name}: the counts held but the objects changed identity\n  {note}"
        )
    return moved


def _reject_unusable_call(
    name: str,
    tool: str,
    self_report: SelfReport,
    expect_person: Mapping[str, Mapping[str, Any]] | None,
    expect_delta: Mapping[str, int],
    id_namespace: str | None,
) -> None:
    """Usage errors are raised, not asserted: a misused helper must never read as a pass."""
    if self_report in NEEDS_EXPECT_PERSON and not expect_person:
        raise ProbeError(
            f"{name}: self_report={self_report!r} requires expect_person={{gramps_id: {{path: value}}}} "
            "— without that REST re-read the helper certifies a tool that never wrote (D16)"
        )
    if self_report == "unguarded" and any(dict(expect_delta).values()):
        raise ProbeError(
            f"{name}: self_report='unguarded' means the tool takes no count snapshot and reports no "
            f"before/after ({tool} is one of three, gramps_client.py:979-1048) — assert its effect "
            "structurally in the test instead of claiming a delta nothing corroborates"
        )
    if self_report == "id" and not id_namespace:
        raise ProbeError(f"{name}: self_report='id' requires id_namespace= to look the new id up")


def _try_person(rest: GrampsRest, gramps_id: str) -> dict[str, Any] | None:
    try:
        return rest.person(gramps_id)
    except LookupError:
        return None  # created by the call under test — there is no prior state to compare


def _assert_fields_landed(
    name: str, rest: GrampsRest, wanted: Mapping[str, Mapping[str, Any]], note: str
) -> None:
    """D16 itself: a claim counts only once the tree repeats it back."""
    for gramps_id, fields in wanted.items():
        record = rest.person(gramps_id)
        for path, value in fields.items():
            actual = resolve_path(record, path, default=None)
            assert actual == value, (
                f"{name}: the tree says {gramps_id}.{path} == {actual!r}, expected {value!r}\n  {note}"
            )
