# Generated by OrchestKit Claude Plugin
# Created: 2026-07-30

"""The MCP container: which image, wired how, and gone again afterwards (plan D8, D21).

Split out of `mcp_session.py` so that three concerns stop sharing one constructor:

* **Which image (D8, two legs).** The working-tree leg builds `gramps-remote-mcp:e2e-<runid>`
  and answers "does the tree work"; the released leg runs the shipped artifact and answers
  "does the artifact work". They are not interchangeable, and an unknown leg is refused rather
  than falling back to `:latest` — a stale `:latest` has already once looked exactly like "the
  new tools are missing". Whichever leg runs, the resolved image **id** is recorded, because a
  tag is a moving name and a run report that only names one proves nothing.
* **Reuse.** One container serves every call of a test. The alternative — one per call, as the
  T1.4 oracle did — pays a container start and a JWT mint per seeded object, and the token
  endpoint is rate-limited to 1/second.
* **Teardown that looks.** `--rm` is not a teardown: a wedged process leaves the container
  standing. So removal is verified and survivors are recorded, the same way `GrampsInstance`
  learned to after a green run leaked four resources.
"""

from __future__ import annotations

import subprocess
import time
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .docker_util import (
    E2E_IMAGE_GLOB,
    E2E_IMAGE_PREFIX,
    NAME_PREFIX,
    ProbeError,
    assert_ours,
    docker,
    resource_exists,
)
from .mcp_session import McpSession, ToolResult
from .runid import LABEL_KEY, label_args

__all__ = [
    "E2E_IMAGE_GLOB",
    "LEG_RELEASED",
    "LEG_WORKING_TREE",
    "ImageRef",
    "McpContainer",
    "container_name",
    "image_from_env",
    "resolve_image",
]

REPO_ROOT = Path(__file__).resolve().parents[3]

LEG_WORKING_TREE = "working-tree"
LEG_RELEASED = "released"
LEGS = (LEG_WORKING_TREE, LEG_RELEASED)

RELEASED_IMAGE = "gramps-remote-mcp:latest"
LEG_ENV = "GRAMPS_E2E_IMAGE_LEG"
RELEASED_ENV = "GRAMPS_E2E_IMAGE"
BUILD_TIMEOUT_S = 900.0

# Every container started and not yet cleanly closed. The session guard in
# tests/e2e/conftest.py reads this, so a leak is a red run rather than a stray container.
STARTED: list[McpContainer] = []


@dataclass(frozen=True)
class ImageRef:
    """What ran, as resolved rather than as asked for."""

    reference: str
    image_id: str
    leg: str

    @property
    def run_reference(self) -> str:
        """What `docker run` is handed: the id, so the container is pinned to this image.

        A concurrent run's reaper sweeps `gramps-remote-mcp:e2e-*` by name, and the release
        ritual re-points `:latest` by hand. Both move a tag out from under a run in flight;
        neither can move an id.
        """
        return self.image_id


def container_name(runid: str, label: str = "") -> str:
    return f"{NAME_PREFIX}{runid}-mcp" + (f"-{label}" if label else "")


def image_id(reference: str) -> str:
    return docker("image", "inspect", reference, "--format", "{{.Id}}", check=False).strip()


def resolve_image(
    runid: str,
    *,
    leg: str = LEG_WORKING_TREE,
    released: str = RELEASED_IMAGE,
    repo_root: Path = REPO_ROOT,
) -> ImageRef:
    """Pick the image for this run and record the id it actually resolved to."""
    if leg not in LEGS:
        raise ProbeError(f"unknown image leg {leg!r} — expected one of {LEGS}")

    if leg == LEG_WORKING_TREE:
        reference = f"{E2E_IMAGE_PREFIX}{runid}"
        docker(
            "build",
            "-t",
            reference,
            "--label",
            f"{LABEL_KEY}={runid}",
            str(repo_root),
            timeout=BUILD_TIMEOUT_S,
        )
    else:
        reference = released

    resolved = image_id(reference)
    if not resolved:
        raise ProbeError(
            f"image {reference!r} is not present locally — build or pull it first; "
            "`docker run` would otherwise fail deep inside the first call"
        )
    return ImageRef(reference=reference, image_id=resolved, leg=leg)


def image_from_env(runid: str, environ: Mapping[str, str], **kwargs: Any) -> ImageRef:
    """Pick the leg from the environment. CI and the release ritual set `GRAMPS_E2E_IMAGE_LEG`;
    a developer sets nothing and gets their working tree built, which is D8's default."""
    leg = environ.get(LEG_ENV, LEG_WORKING_TREE)
    released = environ.get(RELEASED_ENV, RELEASED_IMAGE)
    return resolve_image(runid, leg=leg, released=released, **kwargs)


class McpContainer:
    """One `docker run -i <image>` container and the session that speaks to it."""

    def __init__(
        self,
        name: str,
        image: str,
        env: dict[str, str],
        *,
        network: str | None = None,
        mounts: tuple[tuple[str, str], ...] = (),
        runid: str | None = None,
    ) -> None:
        self.name = assert_ours(name)
        self.image = image
        self.env = dict(env)
        self.network = network
        self.mounts = tuple(mounts)
        self.runid = runid
        self.leftovers: list[str] = []
        self.initialize_reply: dict[str, Any] | None = None
        self._session: McpSession | None = None

    def run_args(self) -> list[str]:
        """Exactly the argv the real client spawns — `.mcp.json` in list form."""
        args = ["docker", "run", "--rm", "-i", "--name", self.name]
        if self.runid:
            args += label_args(self.runid)
        if self.network:
            args += ["--network", self.network]
        for host_path, container_path in self.mounts:
            args += ["-v", f"{host_path}:{container_path}"]
        for key, value in self.env.items():
            args += ["-e", f"{key}={value}"]
        args.append(self.image)
        return args

    def start(self) -> McpSession:
        """Start once and hand out the same session afterwards."""
        if self._session is not None:
            return self._session
        proc = subprocess.Popen(
            self.run_args(),
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1,
        )
        self._session = McpSession(proc)
        STARTED.append(self)
        self.initialize_reply = self._session.initialize()
        return self._session

    @property
    def session(self) -> McpSession:
        return self.start()

    @property
    def stderr(self) -> list[str]:
        return self._session.stderr if self._session is not None else []

    def call(
        self, tool: str, arguments: dict[str, Any] | None = None, *, timeout: float = 60.0
    ) -> ToolResult:
        return self.session.call(tool, arguments, timeout=timeout)

    def list_tools(self, cursor: str | None = None) -> dict[str, Any]:
        return self.session.list_tools(cursor)

    def close(self) -> list[str]:
        """Close the session, force the container away, and *check*. Returns the survivors."""
        if self._session is not None:
            self._session.close()
            self._session = None
        docker("rm", "-f", assert_ours(self.name), check=False)

        self.leftovers = [f"container:{self.name}"]
        for attempt in (0, 1):
            if not resource_exists("container", self.name):
                self.leftovers = []
                break
            if attempt == 0:
                time.sleep(1.0)

        if not self.leftovers and self in STARTED:
            STARTED.remove(self)
        return self.leftovers
