# Generated by OrchestKit Claude Plugin
# Created: 2026-07-30

"""Cross-checking what a tool *says* against what the tree *shows* — one branch per shape.

There are five return shapes, not one (measured against the product):

* `person` — `{gramps_id, before, after}` where before/after are **person snapshots**, not
  counts (`gramps_client.py:693-712`)
* `bulk` — `{count_before, count_after, count_guard_ok, results, errors}`, guard **reported**
  rather than raised (`:714-743`)
* `delete` — `{…, deleted, count_before, count_after}` (`:1050-1083`, `:1120-1150`,
  `gramps_blog.py:193-219`)
* `id` — a bare `str` (`:900-975`, `gramps_blog.py:60-95`)
* `counts` — `{before, after}` as `object_counts` (`:290-330`, `:500-613`)
* `unguarded` — `add_child_to_family`, `remove_child_from_family`, `set_family_parent` take no
  count snapshot and report no before/after at all (`:979-1048`)

None of these checks is sufficient on its own — they run *after* the independent REST re-read
in `assertions.py`, never instead of it.
"""

from __future__ import annotations

import re
from collections.abc import Mapping
from typing import Any

from .rest import GrampsRest
from .wire import ABSENT, resolve_path

# Gramps ids are one letter plus digits. Measured: they start at `I0000`, not `I0001` — the
# original use-case drafts hardcoded the wrong first id.
ID_PATTERN = re.compile(r"[A-Z]\d+")


def assert_self_report(
    name: str,
    self_report: str,
    reported: Any,
    wanted: Mapping[str, Mapping[str, Any]],
    pre: Mapping[str, dict[str, Any] | None],
    before: dict[str, Any],
    after: dict[str, Any],
    rest: GrampsRest,
    id_namespace: str | None,
) -> None:
    if self_report == "unguarded":
        return
    if self_report == "person":
        _assert_person(name, reported, wanted, pre)
    elif self_report == "bulk":
        _assert_bulk(name, reported, wanted, pre, before, after)
    elif self_report == "delete":
        _assert_delete(name, reported)
    elif self_report == "counts":
        _assert_counts(name, reported, before, after)
    elif self_report == "id":
        assert_new_id_resolves(name, reported, rest, str(id_namespace))


def _assert_person(
    name: str,
    reported: Any,
    wanted: Mapping[str, Mapping[str, Any]],
    pre: Mapping[str, dict[str, Any] | None],
) -> None:
    for gramps_id, fields in wanted.items():
        assert reported["gramps_id"] == gramps_id, (
            f"{name}: reported gramps_id={reported['gramps_id']!r}, wrote about {gramps_id!r}"
        )
        assert_story_matches(name, gramps_id, fields, pre.get(gramps_id), reported)


def _assert_bulk(
    name: str,
    reported: Any,
    wanted: Mapping[str, Mapping[str, Any]],
    pre: Mapping[str, dict[str, Any] | None],
    before: dict[str, Any],
    after: dict[str, Any],
) -> None:
    assert reported["count_guard_ok"] is True, (
        f"{name}: count_guard_ok={reported['count_guard_ok']!r}"
    )
    assert reported["count_before"] == before["counts"].get("people"), (
        f"{name}: reported count_before={reported['count_before']}, tree had {before['counts'].get('people')}"
    )
    assert reported["count_after"] == after["counts"].get("people"), (
        f"{name}: reported count_after={reported['count_after']}, tree has {after['counts'].get('people')}"
    )
    by_id = {item["gramps_id"]: item for item in reported["results"]}
    for gramps_id, fields in wanted.items():
        item = by_id.get(gramps_id)
        assert item is not None, f"{name}: the batch reported no result for {gramps_id}"
        assert_story_matches(name, gramps_id, fields, pre.get(gramps_id), item)


def _assert_delete(name: str, reported: Any) -> None:
    assert reported["deleted"] is True, f"{name}: reported deleted={reported['deleted']!r}"
    assert reported["count_after"] == reported["count_before"] - 1, (
        f"{name}: reported {reported['count_before']} -> {reported['count_after']}, "
        "which is not a delete of exactly one"
    )


def _assert_counts(name: str, reported: Any, before: dict[str, Any], after: dict[str, Any]) -> None:
    assert reported["before"] == before["counts"], (
        f"{name}: reported before={reported['before']}, the tree had {before['counts']}"
    )
    assert reported["after"] == after["counts"], (
        f"{name}: reported after={reported['after']}, the tree has {after['counts']}"
    )


def assert_story_matches(
    name: str,
    gramps_id: str,
    fields: Mapping[str, Any],
    was: dict[str, Any] | None,
    reported: Mapping[str, Any],
) -> None:
    """Compare the *named leaves*, never whole records.

    The product snapshots the person it fetched from `/api/people/?gramps_id=…` while the
    oracle re-reads `/api/people/<handle>`; comparing those two dicts wholesale would grade the
    difference between two server projections instead of the write.

    A leaf that is not there resolves to `ABSENT`, never to `None`: as a default, `None` made a
    mistyped path compare equal to an expected `None` and pass in both halves of the check.
    """
    for path, value in fields.items():
        if was is not None:
            said_before = resolve_path(reported["before"], path, default=ABSENT)
            actually_was = resolve_path(was, path, default=ABSENT)
            assert said_before == actually_was, (
                f"{name}: {gramps_id}.{path} before the call was {actually_was!r}, "
                f"the tool reported before={said_before!r}"
            )
        said_after = resolve_path(reported["after"], path, default=ABSENT)
        assert said_after == value, (
            f"{name}: the tool reported after {gramps_id}.{path} == {said_after!r}, expected {value!r}"
        )


def assert_new_id_resolves(name: str, reported: Any, rest: GrampsRest, namespace: str) -> None:
    """A well-shaped id is not evidence, and neither is a correct count delta."""
    assert isinstance(reported, str), f"{name}: expected a bare id, got {type(reported).__name__}"
    gramps_id = reported.strip()
    assert ID_PATTERN.fullmatch(gramps_id), f"{name}: {gramps_id!r} is not a gramps id"
    try:
        rest.by_gramps_id(namespace, gramps_id)
    except LookupError as exc:
        raise AssertionError(
            f"{name}: handed back {gramps_id}, but no {namespace} record carries that id — "
            "every later step of the use case would key off an id that does not exist"
        ) from exc
