# Generated by OrchestKit Claude Plugin
# Created: 2026-07-30

"""The suite's refusal vocabulary: which error text may be asserted, and which tests are
refusal cases (plan T1.7, T4.0).

`assert_refusal(contains=…)` is the only helper in this suite that looks at wire text, and
this module is what keeps that privilege honest: every `contains=` literal must appear
verbatim in a module this repo ships. Framework wording — FastMCP's envelope, pydantic's
validation prose — belongs to a dependency pinned as a *range*, so asserting it means one
`pip install -U` reds the suite without a single thing being wrong with this server.

The second half answers the neighbouring question. Refusal cases are excluded from both PR
legs by `@pytest.mark.refusal`, so the marker decides what runs on a pull request — and a
marker that decides that has to be linted, or it becomes the quiet way to take a test out of
CI. Both halves key on the same call, so they share one scanner rather than walking the tree
twice with two ideas of what a refusal is.

Pure functions over an AST, deliberately: no Docker, no imports of the code under test, so
the guard runs in the same second as the linters.
"""

from __future__ import annotations

import ast
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

HELPER = "assert_refusal"
KEYWORD = "contains"
# A non-literal `contains=` — an f-string, a variable, a `.format()` — would let arbitrary
# wording through while still looking compliant, so it is recorded as a violation rather than
# skipped. Not a valid fragment either way: it can never be found in a product module.
NOT_A_LITERAL = "<not a literal>"


@dataclass(frozen=True)
class Fragment:
    """One asserted piece of wire text, and where the suite asserts it."""

    origin: str
    lineno: int
    value: str


def product_sources(repo_root: Path) -> dict[str, str]:
    """Every root-level module, read from disk.

    Derived rather than listed. The Dockerfile's COPY list is an explicit enumeration and has
    shipped a broken image twice by falling behind the tree; a hardcoded list here would fall
    behind the same way, and the failure mode is worse — a *silent* one, where a legitimate
    fragment is reported as unauthored and someone deletes the guard to make it stop.
    """
    return {path.name: path.read_text(encoding="utf-8") for path in sorted(repo_root.glob("*.py"))}


def scan_source(tree: ast.AST, origin: str) -> list[Fragment]:
    """Every `contains=` handed to the refusal helper in one parsed module."""
    found: list[Fragment] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call) or _called_name(node.func) != HELPER:
            continue
        for keyword in node.keywords:
            if keyword.arg != KEYWORD:
                continue
            value = keyword.value
            literal = value.value if isinstance(value, ast.Constant) else None
            found.append(
                Fragment(
                    origin=origin,
                    lineno=node.lineno,
                    value=literal if isinstance(literal, str) else NOT_A_LITERAL,
                )
            )
    return found


def scan_tree(root: Path) -> list[Fragment]:
    """The same scan over every Python file in the suite."""
    found: list[Fragment] = []
    for path in sorted(root.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        source = path.read_text(encoding="utf-8")
        found.extend(scan_source(ast.parse(source), str(path.relative_to(root))))
    return found


def unauthored(fragments: list[Fragment], sources: dict[str, str]) -> list[Fragment]:
    """The fragments no product module contains — i.e. the ones nobody here wrote."""
    return [
        fragment
        for fragment in fragments
        if not any(fragment.value in source for source in sources.values())
    ]


def _called_name(func: ast.expr) -> str | None:
    """`assert_refusal(...)` and `assertions.assert_refusal(...)` are the same call."""
    if isinstance(func, ast.Name):
        return func.id
    if isinstance(func, ast.Attribute):
        return func.attr
    return None


# -- refusal cases ------------------------------------------------------------------------

MARKER = "refusal"
# The other way a test can prove a refusal. Several honest negative cases cannot go through
# `assert_refusal(contains=…)` at all: where the server answers a bare gramps id, a tuple
# repr or pydantic prose, there is no authored fragment to name, and `unauthored()` above is
# right to reject one. Those cases assert on the wire flag instead, and a lint that did not
# know that would push them out of the marker they belong in.
ERROR_FLAG = "is_error"


@dataclass(frozen=True)
class Case:
    """One test function, seen the way the refusal lint has to see it."""

    origin: str
    name: str
    lineno: int
    markers: frozenset[str]
    refuses: bool
    reads_error_flag: bool

    @property
    def proves_a_refusal(self) -> bool:
        return self.refuses or self.reads_error_flag


def scan_cases(tree: ast.Module, origin: str) -> list[Case]:
    """Every function in one parsed module, with the markers that actually apply to it.

    Markers are inherited, so they are collected the way pytest applies them: module-level
    `pytestmark`, then the class, then the function. A lint reading only the decorator line
    would report a whole class of marked tests as unmarked.
    """
    found: list[Case] = []

    def visit(node: ast.stmt, inherited: frozenset[str]) -> None:
        if isinstance(node, ast.ClassDef):
            marks = inherited | _marker_names(node.decorator_list)
            for child in node.body:
                visit(child, marks)
            return
        if not isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            return
        refuses = any(
            isinstance(inner, ast.Call) and _called_name(inner.func) == HELPER
            for inner in ast.walk(node)
        )
        found.append(
            Case(
                origin=origin,
                name=node.name,
                lineno=node.lineno,
                markers=inherited | _marker_names(node.decorator_list),
                refuses=refuses,
                reads_error_flag=_reads_error_flag(node),
            )
        )

    inherited = module_markers(tree)
    for node in tree.body:
        visit(node, inherited)
    return found


def scan_cases_tree(root: Path, skip: Iterable[str] = ()) -> list[Case]:
    """The same scan over every Python file in the suite."""
    skipped = set(skip)
    found: list[Case] = []
    for path in sorted(root.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        origin = str(path.relative_to(root))
        if origin in skipped:
            continue
        found.extend(scan_cases(ast.parse(path.read_text(encoding="utf-8")), origin))
    return found


def linted_modules(cases: Iterable[Case]) -> set[str]:
    """The modules the marker is in force in — the ones that already use it.

    Deliberately not "every module": six committed functions call `assert_refusal` to prove
    the *helper* works, two of them against a live instance, and they are the positive control
    for every marked case that trusts the helper. Demanding the marker there would move the
    control into the leg it controls. A module opts in by marking one case; from then on the
    lint requires it to be consistent, which is the state that actually goes wrong — half a
    matrix marked, the other half quietly on the PR tier.
    """
    return {case.origin for case in cases if MARKER in case.markers}


def unproven(cases: Iterable[Case]) -> list[Case]:
    """Marked as a refusal case, with nothing in the body that proves a refusal.

    The dangerous direction. The marker takes a test off both PR legs, so a positive case
    wearing it is a test that stopped running on pull requests and still reads as coverage.
    """
    return [case for case in cases if MARKER in case.markers and not case.proves_a_refusal]


def unmarked(cases: Iterable[Case]) -> list[Case]:
    """Refuses, in a module the marker is in force in, and does not carry it."""
    scanned = list(cases)
    linted = linted_modules(scanned)
    return [
        case
        for case in scanned
        if case.origin in linted
        and case.name.startswith("test_")
        and case.refuses
        and MARKER not in case.markers
    ]


def module_markers(tree: ast.Module) -> frozenset[str]:
    """The markers a module applies to everything in it — `pytestmark`, in either spelling.

    Public because it answers a question outside this module's subject: *which* leg a module
    belongs to. `test_00_id_literals.py` scopes itself to the `gramps`-marked modules, and
    reading the marker with the parser that already exists here is the difference between one
    scanner and two that disagree the day somebody writes `pytestmark = [ ... ]`.
    """
    names: set[str] = set()
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == "pytestmark" for target in node.targets
        ):
            names |= _marks_in(node.value)
    return frozenset(names)


def _marker_names(decorators: list[ast.expr]) -> frozenset[str]:
    names: set[str] = set()
    for node in decorators:
        names |= _marks_in(node)
    return frozenset(names)


def _marks_in(node: ast.expr) -> set[str]:
    """`pytest.mark.x`, `pytest.mark.x(...)` and lists of either."""
    if isinstance(node, ast.Call):
        return _marks_in(node.func)
    if isinstance(node, ast.List | ast.Tuple):
        names: set[str] = set()
        for element in node.elts:
            names |= _marks_in(element)
        return names
    if (
        isinstance(node, ast.Attribute)
        and isinstance(node.value, ast.Attribute)
        and node.value.attr == "mark"
    ):
        return {node.attr}
    return set()


def _reads_error_flag(node: ast.AST) -> bool:
    return any(
        (isinstance(inner, ast.Attribute) and inner.attr == ERROR_FLAG)
        or (isinstance(inner, ast.Name) and inner.id == ERROR_FLAG)
        for inner in ast.walk(node)
    )
